#+LATEX_HEADER: \usepackage{mathrsfs} 
#+LATEX_HEADER: \usepackage{amstex} 
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{comment} 
#+LATEX_HEADER: \usepackage{caption} 
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{dcolumn}
#+LATEX_CLASS: article
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \setlength{\parindent}{0}
#+TITLE: Cease and Disperse: The spatial distribution of deforestation
#+AUTHOR: Dan Hammer
#+OPTIONS:     toc:nil num:nil
#+LATEX: \renewcommand{\E}{\mathbb{E}}
#+LATEX: \renewcommand{\rpp}{r^{\prime\prime}}
#+LATEX: \renewcommand{\cpp}{c^{\prime\prime}}

* Introduction

There is an urgent need for reliable and open information on
deforestation.  The dialogue on forest resources between government,
industry, and environmental advocates is consistently characterized by
defensive positioning, rather than productive collaboration.  Much of
the dissonance is a result of disparate and often conflicting data
sources; each side claiming foul play in the reporting or monitoring
of clearing activity.  In the meantime, the deforestation rate is
excessively high and accelerating: almost 15% of annual greenhouse gas
emissions can be attributed to forest clearing activity.  In addition,
forest landscapes are becoming increasingly fragmented, threatening
ecosystem reslience and biodiversity.  Without viable oversight and
enforcement, the rate and spatial distribution of deforestation will
continue to be socially suboptimal.  A /necessary/, though far from
sufficient, condition for informed conservation policy is a common
platform of information on forest clearing activity.\\

To date, a reliable monitoring system has not existed.  Enforcement
costs are relatively high.

* Model

Let $A_i$ be the amount of the forested land in pixel $i$, and let
$a_{it}$ indicate the proportion of the land that has been cleared by
time $t$.  The profit $\pi(a_i) = r(a_i) - c(a_i)$, where $\rpp < 0$
and $\cpp = 0$.  We assume a relatively high fixed cost of clearing,
so that $c(a_i) = F + \gamma a_i$ with $\gamma$ constant in land
cleared. Consider two separate plots such that $i \in \{1,2\}$.  

$$V(z) = \underset{x,\lambda}{\max}\{\pi(z - x) - g(\lambda) + \beta
\E[V(x + \lambda \omega)]\}$$

* Empirical strategy

\begin{figure}[h] 
        \centering
        \includegraphics[width=0.55\textwidth]{images/sample-area.png}
        \caption{Sample area, Malaysia in green and Indonesia in
        orange.  Borders indicate subprovinces.}  
\label{fig:zoom}
\end{figure}


\begin{figure}[h]
        \centering
        \begin{subfigure}[b]{0.55\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/elev.png}
                \label{fig:raw}
        \end{subfigure} \hspace{-30pt} \vline
        \begin{subfigure}[b]{0.5\textwidth}
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/slope.png}
                        \label{fig:raw}
                 \end{subfigure} \hspace{-25pt}
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/flow.png}
                        \label{fig:smoothed}
                 \end{subfigure} \\
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/hill.png}
                        \label{fig:raw}
                 \end{subfigure} \hspace{-25pt}
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/drop.png}
                        \label{fig:smoothed}
                 \end{subfigure}
        \end{subfigure}
        
        \caption{DEM elevation map (left) with derived data sets (right). Derived maps, clockwise
        from top left: slope, water flow direction, aspect, and maximum drop
        within each 90m pixel.}
\label{fig:kali}
\end{figure}


\begin{figure}[h]
        \centering
        \begin{subfigure}[b]{0.45\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/shade.png}
                \caption{Hillshade}
                \label{fig:raw}
        \end{subfigure} \hspace{8pt}
        \begin{subfigure}[b]{0.45\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/fill.png}
                \caption{Flow direction}
                \label{fig:smoothed}
        \end{subfigure}
        \caption{Detailed images of two derived data sets for the same area.}
\label{fig:zoom}
\end{figure}


* Results



\begin{table}[h]
\begin{center}
\begin{tabular}{l D{.}{.}{3.5} @{}}
\toprule
            & \multicolumn{1}{c}{Model 1} \\
\midrule
(Intercept) & 5.48^{*}     \\
            & (2.88)       \\
pd          & 0.00         \\
            & (0.04)       \\
cid         & 13.50^{***}  \\
            & (4.07)       \\
mora        & 2.80         \\
            & (6.88)       \\
pd:cid      & -0.10^{*}    \\
            & (0.05)       \\
pd:mora     & -0.02        \\
            & (0.06)       \\
cid:mora    & -37.27^{***} \\
            & (9.73)       \\
pd:cid:mora & 0.33^{***}   \\
            & (0.09)       \\
\midrule
R$^2$       & 0.35         \\
Adj. R$^2$  & 0.33         \\
Num. obs.   & 202          \\
\bottomrule
\vspace{-2mm}\\
\multicolumn{2}{l}{\textsuperscript{***}$p<0.01$, \textsuperscript{**}$p<0.05$, \textsuperscript{*}$p<0.1$}
\end{tabular}
\end{center}
\caption{Statistical models}
\label{table:coefficients}
\end{table}

# * Ideas

# 1. Use Borneo as the sample area, since a border separates the top
#    third (Malaysia) from the bottom two thirds (Indonesia).

# 2. The moratorium on new deforestation was announced in May 2010.
#    Norway promised to give $1 billion in aid to Indonesia, contingent
#    on successfully reducing the deforestation rate over a two-year
#    period.

# 3. The moratorium was actually enacted on January 1, 2011.

# 4. It is widely known that deforestation has continued despite the
#    moratorium, with industry taking advantage of loopholes and minimal
#    enforcement.  We can check to see if the deforestation rate
#    actually changed over this period, although it will be difficult to
#    ascribe any shift in the overall /rate/ to the moratorium. Why?
#    There are many issues with expectations, prices, and other sources
#    of endogeneity.

# 5. We can, however, see if there was an appreciable shift in the
#    /type/ or spatial dispersion of clearing activity.  Hypothesis: The
#    expectation of increased enforcement, or even just the cost of
#    counter-lobbying when deforestation is found out, is enough to make
#    the clusters of deforestation disperse.  Question: Did the
#    moratorium change the composition of deforestation in Indonesia?
#    Was there a shift toward smaller clusters, i.e., a break in the
#    time series of new cluster creation along prexisting roads, even
#    with potentially higher costs of clearing or lower returns to
#    agriculture?

# 6. Use a type of diff-in-diff-in-diffs approach with the rate of
#    cluster formation in Malaysia.

# * Data sources

# [[http://www.indexmundi.com/commodities/?commodity=palm-oil][Palm oil Monthly Price - US Dollars per Metric Ton]]
