#+LATEX_HEADER: \usepackage{mathrsfs} 
#+LATEX_HEADER: \usepackage{amstex} 
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{comment} 
#+LATEX_HEADER: \usepackage{caption} 
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{dcolumn}
#+LATEX_HEADER: \usepackage{wrapfig}
#+LATEX_CLASS: article
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \setlength{\parindent}{0}
#+LATEX_HEADER: \definecolor{aqua}{RGB}{3,168,158}
#+TITLE: /Cease and Disperse/: An empirical study of targeted conservation and its impact on the optimal development of resource pools
#+AUTHOR: Dan Hammer
#+OPTIONS:     toc:nil num:nil email:on

#+EMAIL: \texttt{danhammer@berkeley.edu}, Department of Agricultural and Resource Economics, UC Berkeley and the World Resources Institute. The author thanks Jeff Hammer and David Wheeler for invaluable comments.  All mistakes are theirs alone.  Thanks also to Max Auffhammer, Peter Berck, George Judge, Robin Kraft, and Wolfram Schlenker, among others who have unwittingly helped to defer blame for mistakes made in this paper.  All code to process the data for this paper is published as an open source project at \href{http://github.com/danhammer/empirical-paper}{\texttt{github.com/danhammer/empirical-paper}} with the full revision history.

#+LATEX: \renewcommand{\pix}[1]{{\bf \textcolor{red}{#1}}}
#+LATEX: \renewcommand{\E}{\mathbb{E}}
#+LATEX: \renewcommand{\X}{{\bf X}}
#+LATEX: \renewcommand{\x}{{\bf x}}
#+LATEX: \renewcommand{\rpp}{r^{\prime\prime}}
#+LATEX: \renewcommand{\cpp}{c^{\prime\prime}}
#+LATEX: \renewcommand{\xb}{\bar{x}}
#+LATEX: \renewcommand{\pot}{p_{1}(t)}
#+LATEX: \renewcommand{\xot}{x_{1}(t)}
#+LATEX: \renewcommand{\ptt}{p_{2}(t)}
#+LATEX: \renewcommand{\xtt}{x_{2}(t)}
#+LATEX: \renewcommand{\Rod}{\dot{R}_{1}}
#+LATEX: \renewcommand{\Rtd}{\dot{R}_{2}}

#+LATEX: \begin{abstract}
This paper examines the impact of the 2011 Indonesian moratorium on
the spatial distribution of deforestation.  We take advantage of the
national border that splits the island of Borneo into Malaysia and
Indonesia, and examine the composition of incremental deforestation.
Specifically, we track the proportion of newly cleared areas that are
in new clusters, rather than on the periphery of existing clusters.
We findn that the moratorium reduced responsiveness of the creation of
new clusters to relevant agricultural prices.  However, we also find
that the overall rate of deforestation increased, even after
controlling for agricultural prices, suggesting that developers merely
shifted deforestation to the periphery of existing clusters.
#+LATEX: \end{abstract}

* $\mbox{}$

Deforestation accounts for 10-15% of annual carbon emissions, as much
as the combined emissions from the global transportation sector.  Any
viable effort to mitigate climate change must address deforestation,
especially in Indonesia and Brazil which made up over 40% of global
deforestation in 2011.  The forest sector, however, is a non-trivial
component of tropical economies.  In Indonesia, it is estimated that
4% of annual GDP and 5% of national employment are associated with
forest clearing activity.  There exist incentives at every level to
convert standing forest to financially productive land.  As part of a
grand Coasian bargain, Norway pledged US$1 billion in aid to
Indonesia, conditional on a significant reduction of its deforestation
rate.  The Indonesian government immediately announced its intention
to stop issuing new permits for the exploitation of primary forest.
The two-year moratorium on new concessions was enacted in May 2011.\\

In this paper, we evaluate the impact of the moratorium on the spatial
distribution of deforestation in Indonesia, using the island of Borneo
as our sample area.  The theoretical support for this study comes
directly from Weitzman's (1975) model of the optimal development of
resource pools.  Weitzman describes the optimal extraction rule for
multiple resource pools with arbitrary extraction costs.  His model
can be reformulated and extended to model a land developer's choice to
expand existing clusters of deforestation or to begin a new cluster.
Hartwick, /et al./ (1986) extend the general resource pool model to an
exhaustible, non-reproducible resource with significant set-up costs
to develop a new deposit.  The authors show that there exist
conditions that would destroy the incentive to develop new clusters,
given the return on extraction.  The conditions surrounding the
moratorium are in constant flux, creating conditions of high risk to
investment and lowering expected return.  The map of affected areas
is, in fact, up for review every six months.  We would expect that the
moratorium on new concessions would therefore reduce the expected
return to the new clusters of deforestation.  The land may or may not
be eligible for development, even after exploration costs are
incurred.  It is conceivable that the land may actually be /targeted/
for re-zoning in the presence of rent-seeking, corrupt politicians.\\

Previous theoretical studies indicate that the development of new
clusters should be reduced with the enactment of the moratorium.  The
intent of the moratorium, however, was to reduce overall
deforestation, not just that which occurs in new clusters.  Meyfroidt
/et al./ (2010) show that narrowly defined conservation efforts will
displace deforestation to other, unprotected areas.  Busch (2011)
reports that a significant portion of forest in existing concessions
remains untouched, even as new clusters are developed.  The modeling
of this storage behavior will not be addressed in this study; but it
is clear that these forests are not directly impacted by the
moratorium, which only restricts clearing activity in new concessions.
The marginal rate of technical substitution between the two types of
clearing activity toward a final agricultural product is dependent on
the fixed and marginal costs of extraction.  The impact on the
/overall/ rate of clearing is therefore an empirical question.\\

Empirical studies of deforestation, and the optimal development of
resource pools in general, have been limited by available
data. Satellite data provides a new opportunity for an overhead and
objective assessment of forest conversion.  Still, these data have not
been previously accessible, given constraints on computational
facilities to process the very large data sets.  Chomitz and Nelson
(2011) and Burgess /et al./ (2012) have utilized remotely sensed data
to assess the impact of protected areas and political cycles on the
conversion of forests.  Even these studies, however, have been severly
limited by the spatial and temporal resolution of the data on land use
change.  We are able to overcome these constraints with an original
data set on tropical deforestation at 500-meter, 16-day resolution
from satellite imagery.\\

The paper is organized as follows: (1) A description of the regulatory
framework behind the Indonesian moratorium, (2) A brief description of
the remotely sensed data on deforestation, (3) A presentation of the
empirical strategy and (4) the results of the impact evaluation.
Finally, we (5) suggest possible implications of the study, and its
importance in broader conservation policy design.

# http://www.pnas.org/content/early/2010/11/05/1014773107.abstract


# The evaluation of conservation policies have been severely limited by
# lack of timely data on deforestation.  Chomitz and Nelson (2011) have
# shown that strict protected areas are less effective at managing
# forests than multi-use or indigenous areas, where local actors have a
# vested interest in the long-term management of forests. The authors
# were forced to use fires as a proxy for deforestation, since data on
# deforestation in the tropics was only available at five year
# intervals.  The results may be subject to systematic measurement error
# across the sample countries, especially since the use of fires to
# clear forests differ dramatically by region.  Other studies have shown
# the relationship between deforestation and infrastructure development,
# using the results to illustrate the tradeoff between development and
# conservation [citations]. But the study of forest resource use has
# been largely theoretical, relying on the study of the time-optimal
# path of extraction.  \\

* Regulatory background

The United Nations has proposed an offset scheme to reduce tropical
deforestation, under the REDD (Reducing Emissions from Deforestation
and Degradation) framework.  The initial intent was to "support
countries' efforts to ... transform their forest sectors so as to
contribute to human well-being and meet climate change mitigation and
adaptation aspirations ... through performance-based payments."  This
(paraphrased) mission statement is exceedingly vague; and prospects
for a comprehensive and global REDD program have begun to dwindle.
Instead, bilateral agreements under the REDD framework have begun to
materialize, most notably through Norway's pledge to support
Indonesia's pledge to reduce carbon emissions by 26% between 2010
and 2020. With 80% of Indonesian carbon emissions emanating from land
use change, Norway has promised US$1 billion in aid, contingent on
verified emissions reductions from forest conversion.  The first stage
of the partnership has been the two-year suspension of new concessions
for natural forest conversion.  The total area affected by the
moratorium amounts to 64 million hectares, roughly twice the size of
Great Britain. \\

There were three stages to the enactment of the moratorium.  (1)
Indonesia signed a letter of intent with Norway on May 29, 2010,
pledging to halt new land conversion concessions in primary forest.
(2) The moratorium was supposed to take effect in January 2011, but
after significant argument between the government, industry, and
environmental groups, the moratorium was not actually implemented (3)
until May 2011. Still, the extent of the moratorium is far from
settled; and, in fact, every six months a /new/ map of the affected
forests is released.  Uncertainty surrounding the parameters of the
moratorium is non-trivial, and likely has implications for the
development of forested land.  Many reports have surfaced about
illegal land clearing operations after May 2011 and associated bribes,
potentially harming the release of Norway's promised funds.

* Data

The foundational data for this paper report deforestation for each
500-meter pixel and each 16-day interval between January 1, 2008 and
September 23, 2012 for Indonesian and Malaysian Borneo.  The algorithm
to identify deforestation from satellite imagery is described in a
forthcoming paper by Hammer, /et al./ (2012).  Each pixel-interval is
assigned a normalized measure of forest clearing activity, based on
the spectral signals from NASA's Moderate Resolution Image
Spectrometer (MODIS) sensor on the Terra satellite.  A pixel is
flagged for clearing activity if the measure registers above 0.50.
Only pixels that are in Borneo and were forested in January 2000 are
considered in the analysis.[fn:: The definition of forest is based on
the Vegetation Continuous Field (VCF) index from the MODIS sensor.
The pixel is forested in 2000 if the VCF index is greater than 25.
This standard also defines the study area for the Hansen /et al./
(2008) data set, which serves as the training data set in our
algorithm.  Additionally, Brunei is not included in the study, as the
addition of another country only serves to complicate the analysis,
and the small country only amounts to 1% of land area in Borneo.] The
deforestation data therefore constitute a panel with The deforestation
data constitute a panel with $N = 2,384,095$ pixels and $T=109$ time
intervals, a total of about 260 million records.  By September 23,
2012, there were $207,578$ pixels flagged with forest clearing
activity in Borneo, indicating that approximately 8.71% of the study
area has been subject to clearing activity since February 2000.[fn::
The precise interpretation of the deforestation identification measure
can be found in Hammer /et al./ (2012).  MODIS data are available from
February 2000 onwards, but the incremental deforestation measure only
begins in January 2008, to allow for training of the algorithm.]  For
reference, only 29% of forested area in Indonesia remained untouched
by forest clearing activity in 2010 from baseline area estimates
in 1900.  \\


The overall rate of deforestation in Malaysian and Indonesian Borneo
is presented in Figure \ref{fig:total}.  The time series indicates the
number of pixels detected in each 16-day interval.  The shaded regions
indicate the three stages of the moratorium, noting that there may be
a two-month lag in the detection of clearing activity.  Within each
interval, the identified pixels are categorized into one of two
groups: (1) pixels on the periphery of previously cleared clusters of
deforestation, and (2) pixels that constitute a new, emerging cluster.
Consider, for example, the illustration in Figure
\ref{fig:illust}. The black, unlabeled pixels represent an existing
cluster, while the red, labeled pixels indicate newly cleared areas.
The red pixels would be counted toward the measure in Figure
\ref{fig:total} for the current interval.  The five newly identified
pixels are grouped according to their distance to the nearest,
existing cluster.  The clustering rule that is used throughout this
paper would classify pixels \pix{A}, \pix{B}, and \pix{C} into Group
1, and pixels \pix{D} and \pix{E} into Group 2.  The pixels are
clustered using a hierarchical clustering algorithm, with Euclidean
distance cutoffs to create discrete clusters.  The predominant cutoff
in this paper is roughly 1km between pixel centroids, or $2 \times
(\mbox{\emph{pixel dimension}})$.  The results in this paper are
robust to other buffer lengths.  And, in fact, there are interesting
patterns in the data that can be uncovered by examining the slight
differences in the results based on various buffer lengths.  The
proportion of clearing activity in new clusters for each interval is
plotted in Figure \ref{fig:sprop}.  Specifically, the proportion is
$P_t = G_{2t}/(G_{1t} + G_{2t})$, where $G_{kt}$ indicates the number of
pixels in Group $k \in \{1,2\}$ during time interval $t$.\\

\begin{figure}[h!]
        \centering

        \begin{subfigure}[b]{0.9\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/ggplot-total.png}

                \caption{Total number of alerts for each 16-day
                period.}

                \label{fig:total}
        \end{subfigure} \\

        \begin{subfigure}[b]{0.9\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/ggplot-prop.png}

                \caption{Two month moving average of proportion of new
                clearing activity that occurs in new clusters, rather
                than on the periphery of old clusters of
                deforestation.}

                \label{fig:sprop}
        \end{subfigure}

        \caption{Time series of overall deforestation and the spatial
        distribution of deforestation.  Indonesia is in
        \textcolor{red}{red} and Malaysia is in
        \textcolor{aqua}{blue}.  Shaded bars indicate the three stages
        of the moratorium.}

\label{fig:defor-ts}
\end{figure}

#+LATEX: \begin{wrapfigure}{r}{0.38\textwidth}
#+LATEX: \centering
                                                                                
#+LATEX: \begin{picture}(100,80)(0,0)

#+LATEX: \thicklines

#+LATEX: \multiput(0,0)(10,0){3}{\line(0,1){10}}
#+LATEX: \multiput(10,10)(10,0){3}{\line(0,1){10}}

#+LATEX: \multiput(0,0)(0,10){2}{\line(1,0){30}}
#+LATEX: \put(10,20){\line(1,0){20}}

#+LATEX: \color{red}
#+LATEX: \put(30,0){\line(1,0){10}}
#+LATEX: \put(30,10){\line(1,0){10}}
#+LATEX: \put(30,0){\line(0,1){10}}
#+LATEX: \put(40,0){\line(0,1){10}}

#+LATEX: \put(0,20){\line(1,0){10}}
#+LATEX: \put(0,30){\line(1,0){10}}
#+LATEX: \put(10,20){\line(0,1){10}}
#+LATEX: \put(0,20){\line(0,1){10}}

#+LATEX: \put(20,30){\line(1,0){10}}
#+LATEX: \put(20,40){\line(1,0){10}}
#+LATEX: \put(30,30){\line(0,1){10}}
#+LATEX: \put(20,30){\line(0,1){10}}

#+LATEX: \color{red}
#+LATEX: \put(80,70){\line(1,0){10}}
#+LATEX: \put(80,80){\line(1,0){10}}
#+LATEX: \put(80,70){\line(0,1){10}}
#+LATEX: \put(90,70){\line(0,1){10}}

#+LATEX: \put(90,70){\line(1,0){10}}
#+LATEX: \put(90,80){\line(1,0){10}}
#+LATEX: \put(100,70){\line(0,1){10}}

#+LATEX: \put(0,32.5){{\bf B}}
#+LATEX: \put(42,1){{\bf A}}
#+LATEX: \put(32.25,31.5){{\bf C}}
#+LATEX: \put(81,60){{\bf D}}
#+LATEX: \put(92,60){{\bf E}}

#+LATEX: \end{picture}
#+LATEX: \caption{Illustration of clusters}
#+LATEX: \label{fig:illust}
#+LATEX: \end{wrapfigure}

Let $\E(\pi_{it})$ be the expected profit on the conversion of pixel
$i$.  The profit is a function of agricultural prices, risk of
expropriation, and cost structure of the pixel, which is in turn
dependent on the physical characteristics of the land. The response of
$P_t$ to changes in $\E(\pi_{it})$ will depend on the relative profit
functions of pixels in Groups 1 and 2, and cannot be determined /a
priori/.  We therefore utilize data on (1) the price palm oil, the
main agricultural product in Borneo, shown in Figure
\ref{fig:palm-price}; (2) physical characteristics of the land,
derived from the Shuttle Radar Topography Mission (SRTM), shown in
Figure \ref{fig:kali}; and (3) rainfall from the NOAA Precipitation
Reconstruction over Land (PREC/L) data set, which provides a
relatively coarse grid of precipitation meatures (0.5 degree
resolution) at monthly intervals.  The data are processed and aligned
at different resolutions, and snapped to the MODIS grid.  The
resampling procedures will be described in a follow-up paper; but have
significant effects, given that some of the data sets are at much
higher spatial resolution, as seen in the zoomed image in Figure
\ref{fig:zoom}.

\begin{figure}[t]
        \centering
        \includegraphics[width=0.9\textwidth]{images/price.png}

        \caption{Palm oil price.  Shaded regions indicate the three
        stages of the moratorium.}

        \label{fig:palm-price}
\end{figure}


\begin{figure}[t]
        \centering
        \begin{subfigure}[b]{0.55\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/elev.png}
                \caption{Elevation}
                \label{fig:raw}
        \end{subfigure} \hspace{-30pt} \vline
        \begin{subfigure}[b]{0.5\textwidth}
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/slope.png}
                        \caption{Slope}
                        \label{fig:raw}
                 \end{subfigure} \hspace{-25pt}
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/flow.png}
                        \caption{Accumulation}
                        \label{fig:smoothed}
                 \end{subfigure} \\
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/hill.png}
                        \caption{Aspect}
                        \label{fig:raw}
                 \end{subfigure} \hspace{-25pt}
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/drop.png}
                        \caption{Drop}
                        \label{fig:smoothed}
                 \end{subfigure}
        \end{subfigure}
        
        \caption{Map of the digital elevation model (left) with
         derived data sets (right) indicating slope, water
         accumulation, direction of slope (aspect), and the steepest
         drop at 90m resolution. }
        
        \label{fig:kali}
\end{figure}

\begin{figure}[b]
        \centering
        \begin{subfigure}[b]{0.45\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/old/shade.png}
                \caption{Hillshade}
                \label{fig:raw}
        \end{subfigure} \hspace{2pt}
        \begin{subfigure}[b]{0.45\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/old/fill.png}
                \caption{Flow direction}
                \label{fig:smoothed}
        \end{subfigure}
        \caption{Detailed images of two derived data sets for the same area.}
\label{fig:zoom}
\end{figure}

* Empirical strategy

Our goal is to identify the impact of the moratorium on the
spatiotemporal patterns of deforestation in Indonesia.  Specifically,
we attempt to identify the impact on

1. The overall rate of deforestation $R_t$
2. The proportion $P_t$ of deforestation that occurs in new clusters

We focus our attention on the island of Borneo, which is divided into
Indonesia (73%) and Malaysia (26%) by the central Borneo highlands,
seen in Figure \ref{fig:sample-area}.  The land use change on both
sides of the border is primarily driven by palm oil plantations.
Likewise, the terrain is roughly similar, despite the fact that
Indonesian Borneo is roughly three times the size of Malaysian
Borneo.[fn:: This fact will be shown in forthcoming versions of this
paper by rigorously comparing the raster images in Figure
\ref{fig:kali}] The difference in area between the treatment and
control areas may introduce systematic error into the analysis, since
developers in Indonesia Borneo may have more opportunity for
exploration and cluster dispersion than their counterparts in
Malaysian Borneo.  We show later, however, that this would only serve
to dampen the observed and significant results.\\

\begin{figure}[h] 
        \centering
        \includegraphics[width=0.55\textwidth]{images/old/sample-area.png}
        \caption{Sample area, Malaysia in green and Indonesia in
        orange.  Borders indicate subprovinces.}  
        \label{fig:sample-area}
\end{figure}

We utilize the basic difference-in-differences method to estimate the
impact of the moratorium on overall deforestation.  Let $M$ be a
binary variable that indicates the time interval of the moratorium.
We will allow this time period to vary, given the three stages of the
moratorium.  Let $C$ be the group indicator for Indonesia.  The
standard difference-in-differences model is given by 

\begin{equation}
R_{it} = \gamma_0 + \gamma_1 M_t + \gamma_2 C_i + \tau (M_t \cdot C_i) +
\beta\x + \epsilon_{it},
\label{eq:total}
\end{equation} where $\x$ is a vector of cofactors.  The identifying
assumption is that in the absence of the moratorium, the relative time
trends in $R_t$ between Indonesia and Malaysia would be relatively
stable after controlling for confounding variables.  The crucial
variables are the price of palm oil and the relative value of the
Indonesian and Malaysian currency, which are the primary drivers of
the difference between deforestation rates in the two countries.  The
price peaked at the same time that the moratorium was enacted, as
shown in Figure \ref{fig:total}.  

We employ a similar strategy to identify the impact of the moratorium
on the spatial dispersion of deforestation.  The reference model is
almost identical to the model reported in Equation (\ref{eq:total}),
except that the proportion of new deforestation in new clusters is the
dependent variable:

\begin{equation}
P_{it} = \gamma_0 + \gamma_1 M_t + \gamma_2 C_i + \tau (M_t \cdot C_i) +
\beta\x + \epsilon_{it}
\label{eq:prop}
\end{equation} Note that the average effect of the treatment for the
treated (read: the moratorium for Indonesian Borneo) is estimated by
$\hat{\tau}$.  Abadie (2005) considers the case when differences in
observed characteristics create non-parallel outcome dynamics between
treated and controls.  Abadie reveals the severe assumptions that
underlie difference-in-differences estimation, especially with respect
to lag structures of responses to exogenous shocks across the treated
and controls.  Take, for example, the current context, where a
developers in the treated and control groups may have difference
response times to a /sustained/ or /short-term/ increase in palm oil
price.  Standard difference-in-differences will not yield a consistent
estimate of the treatment effect.  Abadie proposes a semi-parametric
correction based on the observables in $\x$ to account for
non-parallel effects in the outcome variable.  Still, this correction
is based on the trends of observable characteristics, whereas there
may be dynamics that are dependent on the error structure.  Any
non-parallel shifting or stretching in the $P_{it}$ time series of the
treated and control groups will yield a misspecified impact estimate
of the treatment on the treated.\\

We propose an information theoretic approach to identification.
Specifically, we attempt to uncover broad trends in the outcome
variable within the treated and control groups using temporal patterns
in the observed.  Through a non-parametric matching technique called
dynamic time warping, we attempt to "snap" the treated series to
comparable responses in the control series.  This method is commonly
used in time series classification and language detection, searching
for discernable patterns in speech waveforms through idiosyncratic
amplitudes and frequencies.  A rigorous treatment of this method and
its empirical properties is beyond the scope of this paper.[fn:: The
method will be described in detail, with extensions and asymptotic
properties, will be described in forthcoming versions.]  Instead, we
present a very basic illustration of the outcome of the matching in
Figure \ref{fig:match}. A standard, uncorrected
difference-in-differences estimator relies on a perfectly vertical
comparison of values in time, i.e., a comparison of values in the
exact same time period.  Time warping allows for flexible slopes, with
different penalties associated with distance between values and
slope. The dashed lines in Figure \ref{fig:match} between the
treatment and control $P_{it}$ series show the result of this search
for like values between the series.  If we reconstruct the Indonesian
$P_{it}$ series based on the error dynamics in the Malaysian series,
we can achieve a new series that is purged of error that results from
shifting lag structures.  This new series, the aligned series, may
better characterize the comparable differences between the treatment
and control groups that result from the treatment.  The assumption,
now, is that the unobserved microdynamics are /similar/ across groups;
but we don't need to assume that they are parallel or constant.

\begin{figure}[b] 
        \centering
        \includegraphics[width=0.95\textwidth]{images/match.png}

        \caption{Dynamic time warping of the Indonesian (black, solid)
        series and the Malaysian (red, dashed) series.  The grey
        matching lines match similar values across the two series,
        based on a set of matching penalties.  The dates are replaced
        with index values.}

        \label{fig:match}
\end{figure}

* Results

The results of the difference-in-differences estimation to examine the
total rate of deforestation and described in Equation (\ref{eq:total})
are reported in Table \ref{tab:total}. Column (1) defines the
treatment period as occuring after the first stage of the moratorium,
when it was first announced.  This specification observes that
investment in new clusters is greatly affected by expectations on
returns.  A credible announcement six months prior to enactment of a
policy that could affect a long-term investment process could have
just as much impact as the enforcement of the policy.  Column (2)
defines the treatment period as occuring after the second stage, and
Column (3) after the final stage, when it was actually enacted.  After
May 20, 2011, no new concessions for clearing activity in primary
forests should have been granted by local governments.  There were
some highly criticized exceptions; but the issuance of such
concessions in the specified areas was abruptly halted.\\  

The results in Table \ref{tab:total} report that 

 Model 2 defines the treatment period to
be when it was supposed to be enacted; and Model 3 when it was
actually enacted.It is clear that after controlling for palm oil
prices, the treatment effect is both positive and significant.  The
moratorium actually increased the difference between the Indonesian
and Malaysian deforestation rates, over what would have been
determined by price alone.  Moreover, the results in Table
\ref{tab:total} indicate that price has a positive but diminishing
effect on the rate of deforestation in Borneo.  \\

\begin{table}[h!]
    \centering
    \input{tables/screened-rates.tex}
    \caption{Total rate of deforestation.}
    \label{tab:total}
\end{table}

The opportunity to create new clusters of deforestation, then, is
higher in Indonesia than in Malaysia, and is reflected by the higher
$P_t$ in Indonesia in Figure \ref{fig:sprop}.  If anything, however,
this would only serve to increase the upper bound for $P_t$ and
support the following findings.


\begin{table}[h!]
    \centering
    \input{tables/prop-res.tex}
    \caption{Proportion of deforestation in new clusters}
    \label{tab:prop}
\end{table}

\begin{table}[h!]
    \centering
    \input{tables/warped-prop.tex}
    \caption{Warped proportion of deforestation in new clusters}
    \label{tab:prop}
\end{table}

# \begin{table}[h!]
#     \centering
#     \input{tables/warped-res.tex}
#     \caption{Proportion of deforestation in new clusters}
#     \label{tab:prop}
# \end{table}


* Policy implications

\begin{comment}
# * Introduction

# There are conditions such that, as Hartwick, /et al./ (1986, pp. 219)
# note, the set-up costs will destroy the optimal schedule of
# extraction.  The optimality, here, is not the important part, but
# rather that there are price and set-up costs conditions such that the
# second resource pool will not be extracted, given the relatively high
# set-up costs and the relatively low price.  A somewhat higher price,
# however, will yield a mix of the two resource pools.  The current
# cluster may be extracted up to a point where the marginal cost of
# extraction is higher than it would have been if both resources pools
# were being utilized.  As soon as the price increases to the point to
# "turn on" the second resource pool (and incur the set-up costs) then
# the developer will switch to the new resource pool, and the proportion
# of new aggregate clearing activity in new clusters will rise (since
# some clusters will come online that weren't being exploited before,
# turning off the overexploited resource pools).

# Indonesia has become increasingly active in managing its forests,
# which account for over 10% of the world's remaining tropical forests.
# This increased oversight is part of a broader trend in Indonesia's
# shift toward stronger regulation in important economic sectors since
# the mid-1990s; but the forestry sector has become a central focus with
# international scrutiny of deforestation as a driver of climate change.
# The forestry sector in Indonesia contributes about 3.5% to gross
# domestic product, and employs about 4% of the workforce.  Carbon
# emissions from global deforestation represent over 15% of total annual
# emissions, more than the global transportation sector.  Various
# international initiatives to reduce the rate of forest clearing have
# been announced, shot down, announced again, but there is still no
# unifying approach to addressing global emissions from deforestation.
# The first major, bilateral pledge that is tied to a reduction in
# deforestation is between Norway and Indonesia.  Norway has promised
# USD$1 billion in aid if Indonesia is able to reduce its emissions from
# deforestation.\\

# In response, Indonesia enacted a moratorium on new concessions for the
# exploitation of primary natural forests and peat lands in May 2011.
# The moratorium was announced a year prior, and was set to be enacted
# in January 2011, but was delayed by almost 6 months because of
# continued arguments about the parameters of the moratorium.  The
# moratorium has been widely attacked as having had no effect on the
# deforestation rate.  The Jakarta Globe reported on the "continuing
# forest destruction by several companies despite the moratorium" in May
# 2012, exactly one year into the two-year moratorium.  Environmental
# advocates blame the anemic reduction on a "series of loopholes" and
# changing concession maps, even after the moratorium was enacted.
# Every six months, the maps indicating the extent of the moratorium are
# amended, creating uncertainty that must have economic implications.
# Additionally, the two-year moratorium does not apply to existing
# concessions and secondary forests, allowing for new investment and
# continued development.\\

# "The worst thing about the moratorium," according to the REDD monitor,
# "is that it has not reduced deforestation."  It is true that the rate
# of deforestation has increased since May 2011.  But it is likely that
# this opinion is so simple that it misses contours of the economic
# response to the moratorium that may affect the evaluation of its
# overall efficacy. The purpose of this paper is to examine the impact
# of the moratorium on the spatial distribution of deforestation.  We
# split forest clearing activity into two groups based on whether the
# deforestation results in a new cluster or whether it occurs on the
# periphery of existing clusters.  We find that the moratorium
# diminished new investment in deforestation clusters, but increased
# clearing activity on the periphery of existing clusters.  The policy
# focused on one type of clearing activity merely pushed deforestation
# toward a different class of clearing activity, one that does not
# require as much upfront investment.

# * Data

# Data on clusters of deforestation is derived from satellite imagery.
# The spectral signals from the raw imagery are interpreted toward a
# tractable measure of forest clearing activity; and the flagged pixels
# are subsequently grouped into discrete clusters using a hierarchical
# clustering algorithm.  Reliable information on forest clearing
# activity ranges from January 1, 2008 through September 23, 2012.  The
# result is a time series of deforestation that can be decomposed into
# incremental clearing activity (1) that occurs on the periphery of
# existing clusters, and (2) that constitute new clusters of
# deforestation.  Consider, for example, the illustration in Figure
# \ref{fig:illust} where the black, unlabeled pixels constitute an
# existing cluster and the red, labeled pixels indicate newly cleared
# areas.  Within this sample area, the rate of clearing would be five
# pixels, which can be further decomposed into two groups, based on
# distance from the existing cluster.  The standard specification for
# analysis throughout the rest of the paper would place pixels \pix{A},
# \pix{B}, and \pix{C} on the periphery of the existing cluster and
# define pixels \pix{D} and \pix{E} as a new cluster.  This study
# attempts to identify the effect of Indonesia's moratorium on the
# composition of incremental clearing activity, indicated here by $2/5$,
# as well as the effect on the overall rate.  The results are robust to
# different specifications of clusters, which could include pixels
# \pix{D} and \pix{E} in the existing cluster, depending on the
# buffer.  New pixels clusters require, on average, more up-front
# investment to clear than pixels on the periphery of existing clusters.
# We assume economies of scale, with decreasing average costs.

# * Modeling considerations

# Empirical evidence suggests that the cost of extraction is constant
# within a cluster.  That is, pixels deforested at a later time tend to
# have the same physical attributes (e.g., slope and elevation) as
# pixels deforested earlier.  This indicates constant cost of extraction
# within a cluster.  Between clusters, however, there are increasing
# costs.  Suppose for example that $q_1$ and $q_2$ indicate the
# quantites extracted from clusters 1 and 2, where clearing activity is
# currently in cluster 1 but not yet in cluster 2.  If $C(\cdot)$ is the
# total cost function, then $C^{\prime}(q_1) = c_1 < c_2 =
# C^{\prime}(q_2)$.  This is supported by the data. \\

# We cannot assume that deforestation is a classically exhaustible
# resource, since the decrease in available (read: profitable) clusters
# goes down with the moratorium.  An exhaustible resource situation
# would imply that the rate of extraction in current clusters would
# decrease, since it has to last longer.  However, we don't see this.  I
# think that this has to do with the temporary nature of the moratorium,
# that $t_1$ is now restricted.  More of the resource in cluster 1 may
# be consumed before switching -- does this imply that the short term
# rate increases in a discrete way?\\

# What about the factors of "production" of deforestation.  If there is
# a decrease in demand on one type of production, the factors become
# cheaper for the other -- for existing clusters.  The lower marginal
# cost will also mean that more can be produced with factors that had
# previously been working in higher-cost extraction.\\

# Increase in price implies shorter time frame to switch to new
# clusters.  Higher rate of clearing in new and on the periphery of old
# clusters.  Shorter time frame to switch.

# Option value?  Storage models?

# * Initial analysis

# The attacks on the efficacy of the moratorium often ignore the
# increased price of palm oil, which peaked in January 2011.  The
# baseline rate of clearing should be conditional on the price of the
# agricultural products, which drive investment in cleared land, rather
# than the unconditional, pre-moratorium rate.  The palm oil price is
# charted in Figure \ref{fig:palm-price}.  The palm prices track the
# general trend in global agricultural prices, suggesting that the price
# increases were exogenous, despite the fact that Indonesian palm oil
# accounts for about 40% of global supply. \\

# Empirical evidence suggests that the moratorium shifted the spatial
# distribution of clearing away from the counterfactual.  Increases in
# output price generally increase the spatial dispersion of clearing.  A
# larger proportion of clearing activity takes place in new clusters,
# rather than on the periphery of existing clusters when the price is
# high.  This makes sense.  A higher price will slowly begin to shift
# developers' expectiations on the return to cleared land, which is an
# input to production of agricultural products.  Assuming a constant and
# stable marginal cost of clearing, the fixed costs of clearing become
# more palatable as the price of agricultural products increase: there
# is more of a chance of a positive return on investment (all in
# expectation).  The proportion of new clearing in /new/ clusters, then,
# will increase with the expected return (price of oil palm) --- there
# is more of a chance that the investment will be made.  There will be
# some lag, some time for developers' expectations to adjust, but even
# looking at the contemporaneous data, the signal is reasonably
# clear. \\

# The moratorium reduced the price responsiveness of deforestation in
# new clusters, relative to old clusters.  Less of incremental clearing
# occurred in new clusters than we would expect, given the sustained and
# rapid price increase of oil palm.  This makes sense, too.  The
# moratorium restricted new concessions for deforestation, but did not
# restrict clearing activity within existing concessions.  On average,
# only 70% of existing concessions had been cleared; much of the
# concession area remained untouched, presumably stored for future
# exploitation [citation needed].   \\

# The natural next question is "what are the assumptions that would
# cause the shift to old clusters to completely offset the overall
# reduction in new clusters?"  The data suggest that the total or
# overall rate of clearing may have increased after the moratorium was
# enacted, or equivalently that the /more than offset/ the reduction of
# clearing in new clusters.

# \vspace{10pt} *Points to make* (in no particular order):

# 1. Tropical deforestation accounts for roughly 15% of annual carbon
#    emissions, more than the combined emissions from road, rail, air,
#    and marine transportation, worldwide.

# 2. Borneo is 73% Indonesia, 26% Malaysia, and 1% Brunei (which is not
#    considered in this study to keep it compact).  It is home to one of
#    the oldest rainforests in the world.

# 3. The moratorium constrained investment in new deforestation
#    clusters, shifting the spatial distribution of deforestation and
#    ultimately increasing the overall rate of deforestation.

# 4. Indonesia announced the two-year moratorium in May 2010 to be
#    enacted in January 2011, but it wasn't actually enacted until March
#    2011 after disputes between government, industry, and environmental
#    advocates.  Three stages of the moratorium.

# 5. The moratorium was catalyzed by a $1 billion promise from Norway,
#    cash on delivery to Indonesia, contingent on a reduction in the
#    deforestation rate.  The promise of aid made the government's
#    previously feeble attempts to manage deforestation much more
#    credible.

# 6. We use the island of Borneo as a social lab, of sorts, given that
#    Malaysian Borneo is similar in weather and agricultural output as
#    Indonesian Borneo, but was not subject to the moratorium.  While
#    the border was drawn based on physical attributes of the land -- to
#    divide the watersheds -- the similarity of the two sides is
#    reasonable.  The one complication may be that Indonesian Borneo is
#    three times the size of Malasian Borneo, potentially affecting the
#    possible spatial dispersion.

# 7. The overall effect of the moratorium was an /increase/ in the rate
#    of deforestation, relative to Malaysia, but to decrease the
#    proportion of deforestation due to new clusters.  The spatial
#    pattern of deforestation became more condensed, with clearing
#    occuring disproportionately on the periphery of pre-existing
#    clusters.

# 8. The new paradigm under the moratorium resembles the short-term
#    response to increased supply of cleared land, on the outskirts of
#    existing clusters.  Lower cost to clear, no investment.  Short-term
#    response to quick changes in the demand for cleared land are met
#    with deforestation near previously cleared clusters.

# 9. Intertemporal leakage.  Induced short-term behavior in place of
#    long-term behavior, potentially waiting out the two-year
#    moratorium. Similar to spatial leakage: Restrictions on clearing in
#    a certain time or place will just induce clearing in a different
#    time or place.

# 10. The theoretical structure should have the ability to distinguish
#     between alternatives, to select a model based on testable
#     hypotheses: (a) race to the bottom? (b) lower productivity of land
#     near existing clusters? (c) freed up resources due to a lower
#     fixed cost?

# 11. Use the physical layout of the land to help distinguish between
#     hypotheses.  Examine the attributes of the land that was cleared
#     near existing clusters over time, before and after the moratorium
#     was enacted.

# 12. Potentially cluster the rate-proportion graph, looking to see if
#     the inclusion in each group was sequenced.  A different approach
#     to the standard diff-n-diff, potentially providing more intuition
#     about the way the data are clustered through time.

# 13. Disney has stopped sourcing from suppliers with a poor track
#     record on deforestation.  

# \vspace{10pt}
# *Model Considerations*:

# 1. Areas around clusters should be modelled with option value,
#    reflecting the fact that short term supply of cleared land is
#    mainly around existing clusters.

# 2. The return on land cleared around existing clusters is lower than
#    that of new clusters.  Thus, to get the same amount of product out
#    of the land, more has to be cleared.  *Check this, ask someone
#    else.* Examine the characteristics of land cleared /around existing
#    clusters/ to see if the moratorium had an appreciable impact on,
#    say, the slope of cleared land (something related to yield).

# 3. Dynamic programming problem, with option value and stochastic
#    element.  Two types of resources and one investment term that
#    determines the next period's level of new land.

# 4. Look at the effect of increasing the risk of appropriation
#    associated with new land, drastically lowering the expected return.

# 5. There is intertia in the data, allow for time to adjust
#    expectations and to realize gains from previous investment.

# 6. Is the elasticity of supply of cleared land near /existing/
#    clusters greater than the elasticity of supply of cleared land in
#    /new/ clusters.  Different cost structures of clearing.  If so,
#    then a shock in demand will have a more than proportionate effect
#    on the land around existing clusters.  (This is seen in the data.)
#    The greater supply elasticity may be due to (a) less time to
#    mobilize resources and (b) excess capacity or inventory of land
#    near existing clusters.  Lower marginal costs will imply a greater
#    elasticity of supply.  

# 7. The supply shock that came with restricting new clearing will
#    induce a more than proportionate response in supply (?)  Inelastic
#    demand for cleared land.  Why doesn't the new supply just flood the
#    market, immediately driving back down the price?

# 8. Ultimately, the firms will have to invest in new clusters; but they
#    are content to use up their reserves now, knowing that the
#    moratorium is set to expire in May 2013.

# \vspace{10pt}
# *Basic results*:

# 1. The moratorium had the unintending consequence of /increasing/
#    short-term clearing activity by shifting the spatial ditribution of
#    deforestation to the periphery of exisiting clusters. Potential
#    cause: lower returns on land around existing clusters, and steady
#    demand for the yield from cleared land.

# 2. Deforesters are treating the set moratorium period as a short term
#    hit to investment activity, such that they are responding as if
#    there was a short-term increase in the demand for cleared land
#    (which would and has happened in the past).  This can be seen from
#    the stratified scatter plots.

# 3. The implication is that if the moratorium is lifted after two
#    years, then there will be temporal leakage -- restricting clearing
#    in one period only pushed it into another.  If the moratorium is
#    maintained, however, it may actually reduce long-term clearing,
#    since investment hasn't been made.  Another prediction: way more
#    outcry from industry over a long-term moratorium extension than for
#    the initial two-year enactment to respond to the Norwegian aid
#    promise.

# 4. Much of the effect happens when the moratorium was /supposed/ to be
#    enacted, the other half, so far, has occured after the moratorium
#    was /actually/ enacted.

# Let $\xot$ and $\xtt$ be the amount of land cleared in time $t$, where
# the subscript 1 indicates that the land is on the periphery of an
# existing cluster and the 2 indicates that the land constitutes a new
# cluster.  Let $\pot$ and $\ptt$ be the respective prices for the
# cleared land, which are functions of the physical characteristics of
# the land.  We expect that $\pot < \ptt$, since new sites of land
# clearing will tend to locate in land with the highest net return.
# Landowners will progressively clear less valuable land according to an
# option value approach, effectively storing the forested land until the
# return is high enough to merit the marginal cost of clearing. For now,
# though, consider the simple dynamic programming problem to
# \begin{equation}
# \underset{x_1, x_2, I}{\max} \int^{T}_0 \pi_1 (\xot) + \pi_2 (\xtt) - I(t) \, dt 
# \hspace{8pt} \mbox{subject to} \hspace{8pt} 
# \Rtd = f(I(t)) 
# \hspace{8pt} \mbox{and} \hspace{8pt} 
# \Rod = f(I(t-1)) - \xtt
# \end{equation}

# where $I(t)$ indicates the level of investment in infrastructure or
# exploration costs in order to create new clusters of cleared land in
# the following period.  For a given amount of land, $\xb$, we assume
# that $\pi_2(\xb) > \pi_1(\xb)$.  The profit from the newly cleared
# land is greater than that of land near older clusters.  This gives
# landowners an extra incentive to clear new land, above and beyond the
# incentive to expand production.  The function $f$ is increasing and
# maps investment costs into the amount of land available in the new
# area.



# * Introduction

Tropical deforestation accounts for roughly 10% of annual carbon
emissions, more than the combined emissions from road, rail, air, and
marine transportation, worldwide.  Any viable effort to mitigate
climate change will have to address tropical deforestation.  The
external costs of deforestation are not incorporated into the private
decision to convert forests for agriculture, suggesting that public
intervention might be necessary to curb the rate of clearing.  An
array of alternatives have been specified to reduce new clearing
activity, ranging from portecting selected areas to a full moratorium
on new clearing activity.  To date, however, the efficacy of these
measures has been minimal.  


Deforestation in Indonesia was responsible for 25% of total emissions
from tropical deforestation between 2000 and 2005.  The proportion is
projected to be higher for 2005 through 2010.  The  



Any viable response to climate change must address the deforestation
rate, which is almost certainly above the social optimum.  Carbon
sequestration is just one of many environmental services provided by
standing forests that are not incorporated into the private cost of
clearing.  Other environmental services include nurturing biodiversity
and habitats for ranging mammals.  These services are functions of the
spatial distribution of forests, rather than just the level.


# Climate scientists warn that annual emissions must be quickly and
# drastically cut to avert severe climate change.  Any viable response
# to climate change will have to address the deforestation rate, which
# is almost certainly above the social optimum.  Forests provide many
# environmental services, including carbon sequestration, that are not
# incorporated into the private cost of clearing.  This paper estimates
# the impact of Indonesia's 2011 moratorium on deforestation.  We find
# the short-term, unintended consequences of a broad moratorium may have
# increased the deforestation rate, but created more clustering.


# The release of stored carbon is perhaps the most apparent externality
# imposed by clearing forest.  Another set of services that are
# disregarded by individual landowners is tied to the spatial
# distribution of standing forest.  Forest landscapes are becoming
# increasingly fragmented, threatening ecosystem reslience and
# biodiversity.  Contiguous forests that foster ranging mammals and
# birds are broken up for the relatively homogenous agricultural plots.
# The goods and services provided by biodiversity are invaluable, and
# often overlooked.  In the frenzy to curb the overall deforestation
# /rate/, the spatial distribution may be suffering. This paper does not
# present an argument on the relative value of ecosystem services for
# habitat destruction versus fragmentation, only that there may be
# unintended consequences of an overall prohibition of new clearing. \\

# This paper examines the effect of Indonesia's 2011 moratorium on new
# deforestation on the spatial dispersion of clearing activity.
# Specifically, it examines the choice of landowners to expand on
# previously cleared clusters or to move to new, untouched areas.  We
# find that the moratorium with weak enforcement scattered
# deforestation, disproportionately increasing the creation rate of new
# clusters in Kalimantan, the Indonesian side of the island of Borneo.
# We also examine the character of those clusters over time, how the
# physical attributes of new clusters change, potentially indicating a
# push toward more marginal land.\\

# The first section describes the socio-political context for the
# moratorium.  The second section introduces a simple, dynamic
# programming model that illustrates the choice to clear new forests.
# The third section compares the rates of cluster formation in Indonesia
# and Malaysia, proposing that the observed difference indicates a
# dispersion effect in Indonesia.  The final section offers analysis and
# limits of inference.\\

# * Background

In May 2010, Indonesia announced a moratorium on new deforestation,
with an array of caveats.  Industry has used the uncertainty in land
use maps to find loopholes in the moratorium and the rate of
deforestation has fallen only slightly [insert citation, time series
graph].  Norway offered US$1 billion in aid contingent on a
demonstrated reduction in the deforestation rate.  

# * Model

Let $R_t = R_{1t} + R_{2t}$ be the amount of total amount of land
available to a single agent, split between equal-sized plots $i \in
\{1,2\}$. \\

Figure (\ref{fig:diag}) illustrates the effect of reducing the
expected returns of new clusters on the composition of incremental
deforestation.  The value $\bar{\gamma}$ is a fixed level of
production targeted by the firm.  The expected profit from land that
is close to previously cleared land is given by $\gamma_0$.  The
marginal profit is diminishing, perhaps because of increasing marginal
costs or decreasing marginal returns for (marginal profit should be
zero at $\hat{\gamma}$?).




# Let $R_t = R_{1t} + R_{2t}$ be the amount of resource in plots $i \in
# \{1,2\}$.  We assume a relatively high fixed cost of clearing, so that
# $c(a_i) = F + \gamma a_i$ with $\gamma$ constant in land cleared. The
# probability of getting caught $\delta_i$ and immediately paying a fine
# is an increasing function of $a_i$, but a decreasing function of the
# size of the other plot.  The rationale is that more condensed clearing
# is more likely to raise alarms with enforcement agents; and clearing
# activity in another pixel will divert attention.  We want to study the
# decision point at which the agent decides to begin clearing in the new
# plot, and how that varies with the increased overall probability of
# paying a fine (the moratorium).\\

#  The $\delta$ parameter is plot-specific, and $$\frac{\partial
# \delta_1 (a_1, a_2)}{\partial a_1} < 0 \hspace{8pt} \mbox{and}
# \hspace{8pt} \frac{\partial \delta_1 (a_1, a_2)}{\partial a_2} > 0,$$
# which implies that the larger the proportion cleared within a plot
# (the more densely clustered), the greater the risk of expropriation by
# the government.  It's more noticeable.  Likewise, given the scarce
# resources and constant costs of enforcement, the likelihood of getting
# caught decreases in the size of /another/ cluster.  The clustering in
# another plot acts as a diversion, of sorts, and reduces the likelihood
# of enforcement agents noticing other activity.


# The individual firm takes price $p(t)$ as given and, for $i \in \{1,2\}$ attempts to
# \begin{eqnarray}
# \max \int_0^T \left[ p(t)q_{i}(t) - c(R(t))q_{i}(t) \right]e^{-rt}\,dt 
# \end{eqnarray}
# The total reserves $R(t) = R_1(t) + R_2(t)$.

# * Empirical strategy
# * Results

# * Ideas

# 1. Use Borneo as the sample area, since a border separates the top
#    third (Malaysia) from the bottom two thirds (Indonesia).

# 2. The moratorium on new deforestation was announced in May 2010.
#    Norway promised to give $1 billion in aid to Indonesia, contingent
#    on successfully reducing the deforestation rate over a two-year
#    period.

# 3. The moratorium was actually enacted on January 1, 2011.

# 4. It is widely known that deforestation has continued despite the
#    moratorium, with industry taking advantage of loopholes and minimal
#    enforcement.  We can check to see if the deforestation rate
#    actually changed over this period, although it will be difficult to
#    ascribe any shift in the overall /rate/ to the moratorium. Why?
#    There are many issues with expectations, prices, and other sources
#    of endogeneity.

# 5. We can, however, see if there was an appreciable shift in the
#    /type/ or spatial dispersion of clearing activity.  Hypothesis: The
#    expectation of increased enforcement, or even just the cost of
#    counter-lobbying when deforestation is found out, is enough to make
#    the clusters of deforestation disperse.  Question: Did the
#    moratorium change the composition of deforestation in Indonesia?
#    Was there a shift toward smaller clusters, i.e., a break in the
#    time series of new cluster creation along prexisting roads, even
#    with potentially higher costs of clearing or lower returns to
#    agriculture?

# 6. Use a type of diff-in-diff-in-diffs approach with the rate of
#    cluster formation in Malaysia.

# * Data sources

# [[http://www.indexmundi.com/commodities/?commodity=palm-oil][Palm oil Monthly Price - US Dollars per Metric Ton]]

# * Discussion

# Policy acts on people with incentives, not on inanimate objects.  You
# cannot simply legislate a reduction of deforestation.  The paper
# indicates that there is some /leakage/ associated with local (not just
# in space like a protected area, but in scope of policy) conservation
# policy.  This paper suggests that measures should be taken to dampen
# the incentives of both plots, reduce the incentive to clear at all.
# Maybe that would push people to the black market, though, just as
# deforestation was pushed to new areas in this study.  The scope is not
# wide enough.  This also offers an argument for an overhead and
# comprehensive monitoring system.

# + in the presence of the moratorium, deforestation patterns revert to
#   short-term clearing, extended.
  
\end{comment}

\pagebreak

#+LATEX: \nocite{*}
#+LATEX: \bibliographystyle{abbrv}
#+LATEX: \bibliography{empiricalpaper}
