#+LATEX_HEADER: \usepackage{mathrsfs} 
#+LATEX_HEADER: \usepackage{amstex} 
#+LATEX_HEADER: \usepackage{amsfonts} 
#+LATEX_HEADER: \usepackage{caption}
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{comment} 
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{dcolumn}
#+LATEX_HEADER: \usepackage{wrapfig}
#+LATEX_HEADER: \usepackage[font=small,labelfont=bf]{caption}
#+LATEX_CLASS: article
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \setlength{\parindent}{0}
#+LATEX_HEADER: \definecolor{aqua}{RGB}{3,168,158}
#+TITLE: /Cease and Disperse/: An empirical study of targeted conservation and its impact on the optimal development of resource pools
#+AUTHOR: Dan Hammer
#+OPTIONS:     toc:nil num:nil email:on

#+EMAIL: \texttt{danhammer@berkeley.edu}, Department of Agricultural and Resource Economics, UC Berkeley and the World Resources Institute. The author thanks Jeff Hammer and David Wheeler for invaluable comments.  All mistakes are theirs alone.  Thanks also to Max Auffhammer, Peter Berck, George Judge, Robin Kraft, and Wolfram Schlenker, among others who have unwittingly helped to defer blame for mistakes made in this paper.  All code to process the data for this paper is published as an open source project at \href{http://github.com/danhammer/empirical-paper}{\texttt{github.com/danhammer/empirical-paper}} with the full revision history.

#+LATEX: \renewcommand{\pix}[1]{{\bf \textcolor{red}{#1}}}
#+LATEX: \renewcommand{\E}{\mathbb{E}}
#+LATEX: \renewcommand{\X}{{\bf X}}
#+LATEX: \renewcommand{\x}{{\bf x}}
#+LATEX: \renewcommand{\K}{{\bf K}}
#+LATEX: \renewcommand{\zero}{{\bf 0}}
#+LATEX: \renewcommand{\I}{{\bf I}}
#+LATEX: \renewcommand{\rpp}{r^{\prime\prime}}
#+LATEX: \renewcommand{\cpp}{c^{\prime\prime}}
#+LATEX: \renewcommand{\xb}{\bar{x}}
#+LATEX: \renewcommand{\pot}{p_{1}(t)}
#+LATEX: \renewcommand{\xot}{x_{1}(t)}
#+LATEX: \renewcommand{\ptt}{p_{2}(t)}
#+LATEX: \renewcommand{\xtt}{x_{2}(t)}
#+LATEX: \renewcommand{\L}{\mathscr{L}}

#+LATEX: \renewcommand{\xoh}{\hat{k}_{1}}
#+LATEX: \renewcommand{\xth}{\hat{k}_{2}}
#+LATEX: \renewcommand{\xohp}{\hat{k}_{1}^{\prime}}
#+LATEX: \renewcommand{\xthp}{\hat{k}_{2}^{\prime}}
#+LATEX: \renewcommand{\xohpp}{\hat{k}_{1}^{\prime\prime}}
#+LATEX: \renewcommand{\xthpp}{\hat{k}_{2}^{\prime\prime}}

#+LATEX: \renewcommand{\wp}{w^{\prime}}
#+LATEX: \renewcommand{\wpp}{w^{\prime\prime}}

#+LATEX: \renewcommand{\kb}{\bar{\kappa}}
#+LATEX: \renewcommand{\ob}{\bar{\omega}}
#+LATEX: \renewcommand{\kp}{\kb^{\prime}}
#+LATEX: \renewcommand{\op}{\ob^{\prime}}
#+LATEX: \renewcommand{\kpp}{\kb^{\prime\prime}}
#+LATEX: \renewcommand{\opp}{\ob^{\prime\prime}}

#+LATEX: \renewcommand{\Rod}{\dot{R}_{1}}
#+LATEX: \renewcommand{\Rtd}{\dot{R}_{2}}

#+LATEX: \renewcommand{\st}{\hspace{8pt} \mbox{subject to} \hspace{8pt}}
#+LATEX: \renewcommand{\and}{\hspace{8pt} \mbox{and} \hspace{8pt}}
#+LATEX: \renewcommand{\Kd}{\dot{\K}}

#+LATEX: \begin{abstract}
This paper examines the impact of the 2011 Indonesian moratorium on
the spatial distribution of deforestation.  We take advantage of the
national border that splits the island of Borneo into Malaysia and
Indonesia, and examine the composition of deforestation from January
2008 through September 2012.  Specifically, we track the proportion of
newly cleared areas that are in new clusters, rather than on the
periphery of existing clusters.  We find that the moratorium reduced
responsiveness of the creation of new clusters to agricultural prices.
However, we also find that the overall rate of deforestation increased
after controlling for agricultural prices, suggesting that developers
merely shifted deforestation to the periphery of existing clusters.
#+LATEX: \end{abstract}

* $\mbox{}$

Deforestation accounts for 12% of annual carbon emissions, as much as
the combined emissions from the global transportation sector.  Any
viable effort to mitigate climate change must address deforestation,
especially in Indonesia and Brazil which together accounted for 40% of
global deforestation in 2011.  The forest sector, however, is a
non-trivial component of tropical economies.  In Indonesia, it is
estimated that 4% of annual GDP and 5% of national employment are
associated with forest clearing activity.  There exist incentives at
every level to convert standing forest to financially productive land.
As part of a grand Coasian bargain, Norway pledged US$1 billion in aid
to Indonesia, conditional on a significant reduction of its
deforestation rate.  The Indonesian government immediately announced
its intention to stop issuing new permits for the exploitation of
primary forest.  The two-year moratorium on new concessions was
enacted in May 2011.\\

In this paper, we evaluate the impact of the moratorium on the spatial
distribution of deforestation in Indonesia, using the island of Borneo
as our sample area.  The theoretical support for this study comes
directly from Weitzman's (1975) model of the optimal development of
resource pools.  Weitzman describes the optimal extraction rule for
multiple resource pools with arbitrary extraction costs.  His model
can be reformulated and extended to model a land developer's choice to
expand existing clusters of deforestation or to begin a new cluster.
Hartwick, /et al./ (1986) extend the general resource pool model to an
exhaustible, non-reproducible resource with significant set-up costs
to develop a new deposit.  The authors show that there exist
conditions that would destroy the incentive to develop new clusters,
given the return on extraction.  \\

The intent of the moratorium was to reduce overall deforestation, not
just clearing activity in previously unexploited forest landscapes.
The moratorium's scope, however, was limited to new concessions.
Meyfroidt /et al./ (2010) show that narrowly defined conservation
efforts will displace deforestation to other, unprotected areas.
Busch (2011) reports that a significant portion of forest in existing
concessions remains untouched, even as new clusters are developed.
This land, which could be modeled with storage or option value models,
may serve as an alternative to new clearing activity in order to
smooth the supply of newly cleared land for agriculture.  While these
lands may not be directly impacted by the moratorium, we examine the
indirect effect on forests within existing and irrefutable
concessions.  The marginal rate of technical substitution between the
two types of clearing activity toward a final agricultural product is
dependent on the fixed and marginal costs of extraction on both types
of land.  The impact on the /overall/ rate of clearing is therefore an
empirical question.\\

Economic studies of the optimal development of resource pools have
largely been limited to theoretical exercises.  Objective data on
resource extraction at a time scale commensurate with economic
decision making have not been available.  Recent developments in cloud
computation and satellite imaging have allowed for a new class of data
for empirical study.  Chomitz and Nelson (2011) and Burgess /et al./
(2012) have utilized remotely sensed data to assess the impact of
protected areas and political cycles on the conversion of forests.
Even these studies, however, have been severely limited by the spatial
and temporal resolution of the data on land use change.  We are able
to overcome these constraints with an original data set on tropical
deforestation at 500-meter, 16-day resolution from satellite imagery.
These data provide new information on the choice to intensify
production in current resource pools or to open new pools for
development.  The ultimate objective of this study --- which may not
be fully addressed in this draft --- is to provide empirical evidence
toward or against standing theory on the pattern of resource
extraction in the presence of large set-up costs and heterogeneous
marginal costs..\\

The paper is organized as follows: (1) A description of the regulatory
framework behind the Indonesian moratorium, (2) A brief description of
the remotely sensed data on deforestation, (3) A presentation of the
empirical strategy and (4) the results of the impact evaluation.
Finally, we (5) suggest possible implications of the study, and its
importance in broader conservation policy design.

# http://www.pnas.org/content/early/2010/11/05/1014773107.abstract


# The evaluation of conservation policies have been severely limited by
# lack of timely data on deforestation.  Chomitz and Nelson (2011) have
# shown that strict protected areas are less effective at managing
# forests than multi-use or indigenous areas, where local actors have a
# vested interest in the long-term management of forests. The authors
# were forced to use fires as a proxy for deforestation, since data on
# deforestation in the tropics was only available at five year
# intervals.  The results may be subject to systematic measurement error
# across the sample countries, especially since the use of fires to
# clear forests differ dramatically by region.  Other studies have shown
# the relationship between deforestation and infrastructure development,
# using the results to illustrate the tradeoff between development and
# conservation [citations]. But the study of forest resource use has
# been largely theoretical, relying on the study of the time-optimal
# path of extraction.  \\

* Regulatory background

The United Nations has proposed an offset scheme to reduce tropical
deforestation, under the REDD (Reducing Emissions from Deforestation
and Degradation) framework.  The initial intent was to "support
countries' efforts to ... transform their forest sectors so as to
contribute to human well-being and meet climate change mitigation and
adaptation aspirations ... through performance-based payments."  This
(paraphrased) mission statement is exceedingly vague; and prospects
for a comprehensive and global REDD program have begun to dwindle.  In
its place, bilateral agreements under the REDD framework have
materialized, most notably through Norway's pledge to support
Indonesia's pledge to reduce carbon emissions by 26% between 2010
and 2020. With 80% of Indonesian carbon emissions emanating from land
use change, Norway has promised US$1 billion in aid to Indonesia,
contingent on verified emissions reductions from forest conversion.
The first stage of the partnership has been the two-year suspension of
new concessions for natural forest conversion.  The total area
affected by the moratorium amounts to 64 million hectares, roughly
twice the size of Great Britain. \\

The conditions surrounding the moratorium are in constant flux. The
map of affected areas is up for review every six months.  These
conditions create a climate of high risk to development of new
clusters, whether or not they are in forest that is eligible for new
concessions (secondary or degraded forests).  The risk of re-zoning
may be enough to deter new development.  It is conceivable that
initial clearing activity in new forests, even forests with legal
concessions, may actually be /targeted/ for re-zoning in the presence
of rent-seeking, corrupt politicians.\\

There were three stages to the enactment of the moratorium.  (1)
Indonesia first signed a letter of intent with Norway on May 29, 2010,
pledging to halt new land conversion concessions in primary forest.
(2) The moratorium was supposed to take effect in January 2011, but
after significant argument between the government, industry, and
environmental groups, the moratorium was not actually implemented (3)
until May 2011. Still, the extent of the moratorium is far from
settled; and, in fact, every six months a new map of the affected
forests is released.  Uncertainty surrounding the parameters of the
moratorium is substantial and likely has implications for the
development of forested land.  Many reports have surfaced about
illegal land clearing operations after May 2011 and associated bribes,
potentially forestalling the release of Norway's pledged aid.

* Data
\label{sec:data}

The foundational data for this study is an original data set of
deforestation for each 500-meter, forested pixel and each 16-day
interval between January 1, 2008 and September 23, 2012 for Indonesian
and Malaysian Borneo.  The algorithm to identify deforestation from
satellite imagery is described in a forthcoming paper by Hammer, /et
al./ (2012).  Each pixel and time interval is assigned a normalized
measure of forest clearing activity, based on daily images from NASA's
Moderate Resolution Image Spectrometer (MODIS) sensor on the Terra
satellite.  A pixel is flagged for clearing activity if the measure
registers above 0.50.  Only pixels that are in Borneo and were
forested in January 2000 are considered in the analysis.[fn:: The
definition of forest is based on the Vegetation Continuous Field (VCF)
index from the MODIS sensor.  The pixel is forested in 2000 if the VCF
index is greater than 25.  This standard also defines the study area
for the Hansen /et al./ (2008) data set, which serves as the training
data set in our algorithm.  Additionally, Brunei is not included in
the study, as the addition of another country only serves to
complicate the analysis, and the small country only amounts to 1% of
land area in Borneo.] The deforestation data constitute a panel with
$N = 2,384,095$ pixels and $T=109$ time intervals, a total of about
260 million records.  By September 23, 2012, there were $207,578$
pixels flagged with forest clearing activity in Borneo, indicating
that approximately 8.71% of the study area has been subject to
clearing activity since February 2000.[fn:: The precise interpretation
of the deforestation identification measure can be found in Hammer /et
al./ (2012).  MODIS data are available from February 2000 onwards, but
the incremental deforestation measure only begins in January 2008, to
allow for training of the algorithm.]  For reference, only 29% of
forested area in Indonesia remained untouched by forest clearing
activity in 2010 from baseline area estimates in 1900.\\

The overall rate of deforestation in Malaysian and Indonesian Borneo
is presented in Figure \ref{fig:total}.  The time series indicates the
number of pixels detected in each 16-day interval.  The shaded regions
indicate the three stages of the moratorium, noting that there may be
up to a two-month lag in the detection of clearing activity.  Within
each interval, the identified pixels are categorized into one of two
groups: (1) pixels on the periphery of previously cleared clusters of
deforestation, and (2) pixels that constitute a new, emerging cluster.
Consider, for example, the illustration in Figure
\ref{fig:illust}. The black, unlabeled pixels represent an existing
cluster, while the red, labeled pixels indicate newly cleared areas.
The red pixels would be counted toward the pixel count in Figure
\ref{fig:total}.  The five newly identified pixels are grouped
according to their distance to the nearest, existing cluster.  The
clustering rule that is used throughout this paper would classify
pixels \pix{A}, \pix{B}, and \pix{C} into Group 1, and pixels \pix{D}
and \pix{E} into Group 2.  The pixels are clustered using a
hierarchical clustering algorithm, with Euclidean distance cutoffs to
create discrete clusters.  The distance cutoff in this paper is
roughly 1km between pixel centroids, or $2 \times (\mbox{\emph{pixel
dimension}})$.  The results in this paper are robust to other buffer
lengths.  And, in fact, there are interesting patterns in the data
that can be uncovered by examining the slight differences in the
results based on various buffer lengths.  The proportion of clearing
activity in new clusters for each interval is plotted in Figure
\ref{fig:sprop}.  Specifically, the proportion is $P_t =
G_{2t}/(G_{1t} + G_{2t})$, where $G_{kt}$ indicates the number of
pixels in Group $k \in \{1,2\}$ during time interval $t$.\\

\begin{figure}[h!]
        \centering

        \begin{subfigure}[b]{0.9\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/ggplot-total.png}

                \caption{Total number of alerts for each 16-day
                period.}

                \label{fig:total}
        \end{subfigure} \\

        \begin{subfigure}[b]{0.9\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/ggplot-prop.png}

                \caption{Two month moving average of proportion of new
                clearing activity that occurs in new clusters, rather
                than on the periphery of old clusters of
                deforestation.}

                \label{fig:sprop}
        \end{subfigure}

        \caption{Time series of overall deforestation and the spatial
        distribution of deforestation.  Indonesia is in
        \textcolor{red}{red} and Malaysia is in
        \textcolor{aqua}{blue}.  Shaded bars indicate the three stages
        of the moratorium.}

\label{fig:defor-ts}
\end{figure}

#+LATEX: \begin{wrapfigure}{r}{0.38\textwidth}
#+LATEX: \centering
                                                                                
#+LATEX: \begin{picture}(100,80)(0,0)

#+LATEX: \thicklines

#+LATEX: \multiput(0,0)(10,0){3}{\line(0,1){10}}
#+LATEX: \multiput(10,10)(10,0){3}{\line(0,1){10}}

#+LATEX: \multiput(0,0)(0,10){2}{\line(1,0){30}}
#+LATEX: \put(10,20){\line(1,0){20}}

#+LATEX: \color{red}
#+LATEX: \put(30,0){\line(1,0){10}}
#+LATEX: \put(30,10){\line(1,0){10}}
#+LATEX: \put(30,0){\line(0,1){10}}
#+LATEX: \put(40,0){\line(0,1){10}}

#+LATEX: \put(0,20){\line(1,0){10}}
#+LATEX: \put(0,30){\line(1,0){10}}
#+LATEX: \put(10,20){\line(0,1){10}}
#+LATEX: \put(0,20){\line(0,1){10}}

#+LATEX: \put(20,30){\line(1,0){10}}
#+LATEX: \put(20,40){\line(1,0){10}}
#+LATEX: \put(30,30){\line(0,1){10}}
#+LATEX: \put(20,30){\line(0,1){10}}

#+LATEX: \color{red}
#+LATEX: \put(80,70){\line(1,0){10}}
#+LATEX: \put(80,80){\line(1,0){10}}
#+LATEX: \put(80,70){\line(0,1){10}}
#+LATEX: \put(90,70){\line(0,1){10}}

#+LATEX: \put(90,70){\line(1,0){10}}
#+LATEX: \put(90,80){\line(1,0){10}}
#+LATEX: \put(100,70){\line(0,1){10}}

#+LATEX: \put(0,32.5){{\bf B}}
#+LATEX: \put(42,1){{\bf A}}
#+LATEX: \put(32.25,31.5){{\bf C}}
#+LATEX: \put(81,60){{\bf D}}
#+LATEX: \put(92,60){{\bf E}}

#+LATEX: \end{picture}
#+LATEX: \caption{Illustration of clusters}
#+LATEX: \label{fig:illust}
#+LATEX: \end{wrapfigure}

Let $\E(\pi_{it})$ be the expected profit on the conversion of pixel
$i$.  The profit is a function of agricultural prices, risk of
expropriation, and cost structure of the pixel, which is in turn
dependent on the physical characteristics of the land. The response of
$P_t$ to changes in $\E(\pi_{it})$ will depend on the relative profit
functions of pixels in Groups 1 and 2, and cannot be determined /a
priori/.  We therefore utilize data on (1) the price palm oil, the
main agricultural product in Borneo, shown in Figure
\ref{fig:palm-price}; (2) physical characteristics of the land,
derived from the Shuttle Radar Topography Mission (SRTM), shown in
Figure \ref{fig:kali}; and (3) rainfall from the NOAA Precipitation
Reconstruction over Land (PREC/L) data set, which provides a
relatively coarse grid of precipitation measures (0.5 degree
resolution) at monthly intervals.  The data are processed and aligned
at different resolutions, and snapped to the MODIS grid.  The
resampling procedures will be described in a follow-up paper; but have
significant effects, given that some of the data sets are at much
higher spatial resolution, as seen in the zoomed image in Figure
\ref{fig:zoom}.

\begin{figure}[t]
        \centering
        \includegraphics[width=0.9\textwidth]{images/price.png}

        \caption{Palm oil price.  Shaded regions indicate the three
        stages of the moratorium.}

        \label{fig:palm-price}
\end{figure}


\begin{figure}[t]
        \centering
        \begin{subfigure}[b]{0.55\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/elev.png}
                \caption{Elevation}
                \label{fig:raw}
        \end{subfigure} \hspace{-30pt} \vline
        \begin{subfigure}[b]{0.5\textwidth}
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/slope.png}
                        \caption{Slope}
                        \label{fig:raw}
                 \end{subfigure} \hspace{-25pt}
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/flow.png}
                        \caption{Accumulation}
                        \label{fig:smoothed}
                 \end{subfigure} \\
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/hill.png}
                        \caption{Aspect}
                        \label{fig:raw}
                 \end{subfigure} \hspace{-25pt}
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/drop.png}
                        \caption{Drop}
                        \label{fig:smoothed}
                 \end{subfigure}
        \end{subfigure}
        
        \caption{Map of the digital elevation model (left) with
         derived data sets (right) indicating slope, water
         accumulation, direction of slope (aspect), and the steepest
         drop at 90m resolution. }
        
        \label{fig:kali}
\end{figure}

\begin{figure}[b]
        \centering
        \begin{subfigure}[b]{0.45\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/old/shade.png}
                \caption{Hillshade}
                \label{fig:raw}
        \end{subfigure} \hspace{2pt}
        \begin{subfigure}[b]{0.45\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/old/fill.png}
                \caption{Flow direction}
                \label{fig:smoothed}
        \end{subfigure}
        \caption{Detailed images of two derived data sets for the same area.}
\label{fig:zoom}
\end{figure}

* The optimal development of deforestation clusters

Consider a two-factor production model with the two types of cleared
land described in the previous section as two inputs to agricultural
production.  The static cost minimization problem is inadequate to
model behavior of a profit maximizing firm, since deforestation is an
investment that will pay out over time.  Moreover, there are two types
of investment, distinct from the recurring costs after the land has
been cleared: (1) the investment to begin a new cluster of
deforestation, including the cost to build branching roads; and (2)
the investment to clear each new pixel, once the cluster has been
started.  Both the costs and benefits of a deforestation cluster are
borne over time; and we therefore adapt the two-factor production
model to explicitly incorporate time-dependent decisions.  It will
become clear, though, that the stationary problem is very similar to
the static problem.  The purpose of generating this new machinery is
to ensure that the stationary specification of the optimization is
robust to its dynamic specification, albeit less detailed.

** Framework

Following Weitzman's notation, define $G(\K, \I)$ as the net current
"take home" cash flow, where $\K$ is a vector of capital inputs and
$\I$ is a vector of the associated fixed-cost investments.  Dynamic
optimization of $G(\cdot)$, or optimal control of $\I$, will define
the time-path of capital development.  This detailed information is
incidental, however, for our relatively simple application to identify
the impact of the moratorium on the aggregate rate of capital
investment.  For this type of application, Weitzman suggests an "old
economist's trick" to collapse the dynamic problem to its stationary
equivalent.\\

Consider the prototypical optimal control problem of the form:
nn\begin{equation}
\max \int_{0}^{\infty} e^{-\rho t}G(\K_t, \I_t)\, dt \\
\begin{center}
\begin{array}{rl}
\st  & \Kd_t = \I_t \\ 
\and & \K_t \geq 0  \nonumber
\end{array}
\end{center}
\label{eq:dyn}
\end{equation}

where $\K_t$ is a vector of the cumulative stock for all capital
inputs in time $t$ and $\I_t$ is the level of investment for the
corresponding capital inputs. The fundamental equation of capital
theory sets the stationary rate of capital return /for each capital
input/ equal to the discount rate.  The stationary rate of return,
denoted $R(\hat{\K})$, is the relative value of capital when optimal
investment is zero for all periods.  The stationary solution will
satisfy the system of equations:
\begin{equation}
R(\hat{\K}) = \frac{\partial G(\K, \zero) / \partial \K}{\partial
G(\K, \zero) / \partial \I} = \rho
\label{eq:rate}
\end{equation}

The firm will incur the immediate cost of capital only if the imputed
net gain from capital exceeds the market rate for lending.  The
investment mix is subject to this external valve, such that the
decision to invest in any type of capital will be weighed against the
going interest rate. Weitzman notes that while a firm may never
actually achieve the stationary state, the investment decisions push
the outcome in that direction.\\

Consider the standard two-factor production model, where $k_1$ is land
on the periphery of existing cleared land and $k_2$ indicates land
that would constitute a new cluster of cleared land.  Further, let
$\xoh$ and $\xth$ be the stationary states associated with each
capital input for agricultural production, noting that $\xoh$ and
$\xth$ are highly substitutable.  Let $v(\xoh, \xth)$ be a function
that indicates the revenue product of the stationary capital levels,
which is equivalent to the gross gain in the $G(\cdot)$ function.  We
are effectively extending Weitzman's framework by splitting the gain
function in order to examine the dynamic substitution between capital
inputs. Finally, let $\hat{v}(\cdot) = v(\cdot)/\rho$ indicate the
present value of the revnue product.  The purpose of setting up this
machinery is to ensure that the stationary specification of the
optimization problem is robust to its dynamic specification.\\

Figure (\ref{fig:isoquant}) represents the tradeoff between stationary
levels of inputs.  The isoquant $\hat{v}(\xoh, \xth) = \bar{v}$
represents the present value of a fixed level of revenue, which is the
revenue side of the net gain function $G(\cdot)$.  The optimized,
stationary input mix is determined by the tangency of the
present-value isocost line to the present-value isoquant curve.  This
is equivalent to where the ratio of the discounted marginal costs of
the investments is equal to the marginal rate of technical
substitution in present value terms.  This allows for the two-tiered
investment structure: an investment to open a new cluster and another
investment for each pixel to expand the cluster.  The annuitized value
of the initial, cluster-level investment can be rolled into the
present value.  The initial pixel of a cluster -- the seed -- serves
as an indicator for the nascent cluster.  This framework is consistent
with the implicit cost framework built by Weitzman (1976).  The
optimality of the tangency can be seen by the following:

\begin{equation}
\frac{\partial G(\K, \zero) / \partial \K_1}{\partial G(\K, \zero) / \partial \I_1} = \rho = 
\frac{\partial G(\K, \zero) / \partial \K_2}{\partial G(\K, \zero) / \partial \I_2} 
\end{equation}

This implies, in turn, that the present value of the marginal rate of
technical substution is equal to the relative expense of investment
between the two land types.
\begin{equation}
\frac{\partial G(\K, \zero) / \partial \K_1}{\partial G(\K, \zero) / \partial \K_2} = 
\frac{\partial G(\K, \zero) / \partial \I_1}{\partial G(\K, \zero) / \partial \I_2} 
\end{equation}

What is the impact of a change in the relative investment cost?  The
original stationary input mix $(\xohp, \xthp)$ in Figure
(\ref{fig:isoquant}) reflects the original investment cost regime.
The increase in the cost of investment to land type 2 will move the
optimized miz along the curve to $(\xohpp, \xthpp)$, assuming a
concave isoquant and high rate of substitution.  \\

Note that the units of both $\xoh$ and $\xth$ are land area,
specifically pixels at 500-meter spatial resolution.  The aggregate
area in each time interval indicates the observed deforestation rate.
A primary question of this paper is whether an increase in the the
cost of an investment can /increase/ the overall deforestation rate.
Figure (\ref{fig:isoquant}) indicates that, given the high
substitution rate between land inputs, this behavior is theoretically
possible, and in fact somewhat common.  The isoquant reflects a
scenario where $\xth$ tends to be more productive than $\xoh$.  This
property is not hard to imagine.  In fact, it is more likely than the
alternative for many reasons.  One reason, for example, is that the
production of palm oil requires processing of the harvested kernels
within 24 hours of picking.  The proportion of spoiled product
increases with the time between harvesting and processing.  The
processing facility is almost tautologically located closer to the
early clearings than to the later clearings.  The amount of product
extracted for palm oil extracted from cleared land at the beginning of
the cluster is greater.  And the marginal product associated with the
land will decline thereafter.  The discounted value of the revenue
product associated with a yet uncleared cluster will include the gains
from the early pixels that are omitted from the forward gains of an
existing cluster.[fn::The productivity could be modeled in the cost
structure; but we separate the investment costs from the ongoing
productivity.  investment to get land to as productive as it will be.
Once productive, the land will be more productive across pixels if it
is near the processing plant.]\\

It is also empirically true that land in new deforestation clusters
tends to be at higher elevation and slope than land cleared on the
periphery of existing clusters.  Land with these characteristics is
harder to prepare for agriculture; and the investment to employ this
type of land is higher.  Figure (\ref{}) shows the difference in
elevation for Indonesian and Malaysian Borneo over time by clearing
type. A difference in means test indicates that both the slope and
elevation of land clearing is statistically different in Borneo. Taken
together, these facts corroborate the higher investment costs
indicated for $\xth$ in Figure (\ref{fig:isocost}) as seen in the
slopes.

# We will assume concavity of the isoquant; many reasons that this would
# reflect standard, static theory in the dynamic context of diminishing
# marginal returns (e.g., risk considerations) but we ignore this for
# now.

# The impact of investment on net current gain is already discounted;
# it is the cost side of hiring capital.  the net gain function when
# split into revenue and cost is represented by the isoquant curve.

# Stationary state on both axes.
# discounted marginal revenue product fixed (gross part of gain function)
# The relative discounted costs of investment define budget constraint

# All we need is diminishing marginal returns; but this is exaggerated
# by the distance to oil palm plantations.

# There are two levels of investment: opening a new cluster and
# clearing new land.  We can roll these together in the discounted
# cost and benefit structure of each capital input, where the x_2
# indicates the seed for further, peripheral development.  

# ; but The dynamic optimizaton problems detailed in his book
# define the time path of capital development; but this is extraneous
# information for our relatively straightforward application.  Instead,
# we are interested only in the aggregate impact of an investment price
# shift on the optimized input mix.\\

# For this application, Weitzman suggests an "old economist's trick" to
# collapse a dynamic problem to its stationary equivalent.  Consider the 

# The decision to clear forest is the result of a dynamic optimization
# problem.  The gain from cleared land is realized over time; and the
# initial set-up costs are a substantial component of the cost to
# increase extensive agricultural production.  Land is an input in the
# production of palm oil or rubber.  Weitzman notes that the developer
# will invest in capital as long as the stationary rate of return on
# capital exceeds the interest rate.  This is such a basic concept in
# investment that he names this decision condition "the fundamental
# equation of capital theory."  A slight reimagining of the equation
# yields a powerful insight into the decision to clear on the periphery
# of existing deforestation clusters or to create new clusters.\\

# Weitzman presents a simple heuristic to illustrate that the rate of
# return on an investment at the margin is equal to the interest rate
# $\rho$. The interest rate in a stationary equilibrium, he explains, is
# equivalent the imputed rental price.  
# \begin{equation}

# \end{equation}

# Consider a standard two-factor production model, where $x_1$ is
# cleared land on the periphery of existing clusters and $x_2$ is land
# in still nonexistent clusters.  A developer will be indifferent
# between hiring $x_1$ and $x_2$ if the stationary rate of return on
# either investment is equivalent.  At the margin and in stationary
# terms, the input mix will be determined according to the well-known
# cost minimization problem, which ultimately sets the marginal rate of
# transformation between the two inputs equal to the relative wage
# rates.  This is what Weitzman calls an "old economist's trick" to
# collapse a dynamic problem into its stationary equivalent.



# The difference between the new and old deforestation clusters is a
# matter of timing.  The land developer has already incurred the fixed
# costs of setting up a new resource pool with any incremental clearing
# activity on the periphery of existing clusters.  The new clusters,
# however, are defined by the fixed costs.  The two types of clearing
# are disjoint sets --- resource pools already opened, and those not yet
# opened --- the difference lies in where they exist on the clearing
# curve.



# Consider a standard two-factor production model in a competitive
# market for palm oil.  The cost-minimizing firm in the long-run will
# hire each factor up to the point where the marginal cost equals the
# marginal revenue product.  Let $x_1$ indicate cleared land on the
# periphery of existing deforestation clusters and let $x_2$ indicate
# cleared land that constitutes a new cluster of deforestation.  There
# is an immense literature on the optimal development of resource pools,
# along with the decision to invest in new factories or foreign direct
# investment.  Through the context-specific algebra, there is a common
# theme of choosing the input mix based on the relative characteristics.
# This is what we develop here.\\




# The profit-maximizing firm will determine the
# optimal input mix according to the constrained minimization problem:
# \begin{equation}
# \L = w_1 x_1 + w_2 x_2 + \lambda \left[f(x_1, x_2) - q \right]
# \label{eq:lagrange}
# \end{equation}
# Let $x_1$ 

#   Let $\omega$ and $\kappa$ denote the two factors
# of production.  The derived demand for $\omega$ and $\kappa$ are based
# on a cost minimization problem, which ultimately sets cost equal to
# revenue for the last unit hired.  The common approach to this problem
# separates fixed and marginal costs to illustrate input decisions at
# the margin.  This separation, however, cannot adequately represent the
# decision to utilize land in new clusters, since the cost of the next
# unit includes the fixed costs.  Separation would mask the investment
# decision.  We will adapt the two-factor production model to account
# for the dynamic decision to invest, using the concept of stationary
# cost, developed by Weitzman (1976). \\

# Let $\omega$ denote cleared land on the periphery of existing
# deforestation clusters, and let $\kappa$ denote cleared land that
# constitutes a new cluster.  The cost of hiring the next unit of
# $\kappa$ land will, by definition, be the fixed cost of creating the
# cluster.  Any subsequent clearing activity to expand that cluster is
# considered $\omega$ land.  The decision to hire a new unit of $\kappa$
# is the manifestation of a dynamic determination to invest in a new
# cluster.\\

# The standard development of the two-factor production model can be
# extended to dynamic considerations, using concepts developed by
# Weitzman (1976). Weitzman asserts that "it is easy to characterize the
# optimal rule in a classical environment where every pool has
# nondecreasing extraction costs. At any time simply draw the required
# amount from the source with lowest marginal cost."  He then presents a
# generalization, describing the optimal rule of resource pools with
# arbitrary extraction costs.  To do so, he develops a concept that he
# calls /equivalent stationary cost/, which is effectively the average
# marginal cost over a given time horizon.  We will show that the useful
# two-factor production model can be extended to incorporate the fixed
# cost considerations.

# Following Weitzman's paper, let $F_i(m)$ be the cost of extracting one
# more unit of resource from pool $i$ after $m$ units have already been
# extracted.  The equivalent stationary cost of extracting the next $n$
# units in a row is the weighted average:
# \begin{equation}
# \Psi_i^n(m) = \frac{\sum_{j=0}^{n-1} \alpha^j F_i(m + j)}{\sum_{j=0}^{n-1} \alpha^j}
# \label{eq:stationary}
# \end{equation} Define the implicit cost to be the minimum stationary
# cost, based on the optimal time horizon $\hat{n}$:
# \begin{equation}
# \Phi_i(m) = \Psi_i^{\hat{n}}(m) = \min_{n} \Psi_i^n(m)
# \label{eq:implicit}
# \end{equation} Weitzman's rule is to \textit{always extract the next
# resource unit from the pool with lowest implicit cost}.  If $F_i(m)$
# is nondecreasing everywhere, then this is equivalent to the
# marginalist rule. \\

# We can prove this by induction.  Let $P(0)$ indicate the truth of the
# the proposition when $j = 0$.  


# In the standard cost minimization problem, the firm will hire a factor
# until its marginal productivity is equal to its marginal cost.
# Consider the same problem, except over an infinite time horizon.
# Intuitively, the firm should hire a factor up to the point where its
# implicit productivity is equal to its implicit cost.  If the time
# horizon is prematurely halted, then this rule may not hold.
# \begin{equation}
# TC_n = \kappa \Phi_\kappa(m) + \omega \Phi_\omega(m)
# \end{equation}

# The difference is introduced through
# the flexible specification of time; a unit of time over which
# "marginal" costs are incurred varies and is optimized by the firm. We
# will utilize this concept to extend the two-factor production model in
# order to understand the effect of a change in the relative extraction
# cost associated with different resource pools.\\

# close substitutes, indicating that the marginal rate of technical
# substitution (MRTS) is near constant along the isoquant.  This
# relationship is exhibited by $q(\kappa, \omega)$ in Figure
# \ref{fig:isoquant}.  The rate of substitution between new and old
# cluster deforestation is based on empirical observation, something to
# be estimated.\\

# It is reasonable to assume, however, that the marginal product of new
# clusters is greater than the marginal product of old clusters.

# The magnitude of the substitution may not be one-to-one,
# howver, and the production of palm oil suggests that.  Let $\wp$ be
# the price of input $\omega$ relative to the price of $\kappa$.

# The regulation differentially impacts the expected price of
# utilization of land in new clusters.  The relative input price of
# $\kappa$ increases.  With a low and constant marginal rate of
# technical substitution the aggregate use of the two inputs --- in the
# same units --- increases.

# \begin{equation} \op + \kp < \opp + \kpp \Leftrightarrow
# -\frac{\kp - \kpp}{\op - \opp} = -\frac{\Delta \kappa}{\Delta \omega} < 1
# \end{equation}

# Note that $- \Delta \kappa / \Delta \omega$ is the average marginal
# rate of substitution between the optimized input mixes $(\op, \kp)$
# and $(\opp, \kpp)$.  By assumption, the marginal rate of substituion
# is near constant, such that the marginal rate of technical
# substitution is less than one over the range of input mixes,
# conditional on a well-behaved production function.  Land in new
# clusters tends to be more productive toward oil palm, since the land
# is by definition closer to the center of the cluster --- and
# presumably the oil palm processing plant.  More travel over poor roads
# and lost product in the rough terrain back to the center of clusters
# implies a less productive yield per acre.\\

# The marginal cost of utilizing land in new clusters tends to be
# higher, as shown by the difference in the physical attributes of the
# land.  The cost to clear and ready the land for production is higher;
# but the yield is also higher, making the higher rate paid for the
# input worth it (i.e., holding $pMP_\kappa = 1/w$).  The question, now,
# is how to show that the new clusters are subject to expectations on
# price, that in fact the optimal development of resource pools will
# restrict new pools if the prices becomes excessively high.  This is
# shown in Hartwick, Kemp, et al. (1980).

\begin{figure}[t]
        \centering
        
        \begin{picture}(300,150)(0,0)
        
        \put(-15,140){$\xth$}
        \put(307,8){$\xoh$}

        \put(-15,76){$\xthp$}
        \put(105,8){$\xohp$}

        \put(-15,46){$\xthpp$}
        \put(213,8){$\xohpp$}

        \put(307,37){$\hat{v}(\xoh, \xth) = \bar{v}$}

        \thicklines

        \put(0,20){\vector(1,0){300}}
        \put(0,20){\vector(0,1){130}}

        \thinlines
        
        \qbezier(0,140)(130,45)(300,40)

        \put(110,20){\line(0,1){58}}
        \put(0,78){\line(1,0){110}}

        \put(218,20){\line(0,1){28}}
        \put(0,48){\line(1,0){218}}

        \end{picture}

        \caption{Illustration of an isoquant where the inputs exhibit
        a high degree of substitution in production and a low marginal
        rate of technical substitution.}

        \label{fig:isoquant}
\end{figure}


\begin{figure}[h!]
        \centering

        \begin{subfigure}[b]{0.45\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/idn-elev.png}

                \caption{Elevation for Indonesian land clearing}

                \label{fig:idnelev}
        \end{subfigure}
        \begin{subfigure}[b]{0.45\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/mys-elev.png}

                \caption{Elevation for Malaysian land clearing}

                \label{fig:myselev}
        \end{subfigure}

        \caption{Elevation of land clearing for different cluster
        types over time.}

\label{fig:elev}
\end{figure}


** Empirical rates of substitution



* Empirical strategy

Our goal is to identify the impact of the moratorium on the
spatiotemporal patterns of deforestation in Indonesia.  Specifically,
we attempt to identify the impact on

1. The overall rate of deforestation $R_t$
2. The proportion $P_t$ of deforestation that occurs in new clusters

We focus our attention on the island of Borneo, which is divided into
Indonesia (73%) and Malaysia (26%) by the central Borneo highlands,
seen in Figure \ref{fig:sample-area}.  The land use change on both
sides of the border is primarily driven by large-scale palm oil
production.  Likewise, the terrain is similar, even though Indonesian
Borneo is roughly three times the size of Malaysian Borneo.[fn:: This
fact will be shown in forthcoming versions of this paper by rigorously
comparing the raster images in Figure \ref{fig:kali}] The difference
in area between the treatment and control areas may introduce
systematic and unobserved component in the residual variance, since
developers in Indonesia Borneo may have more opportunity for
exploration and cluster dispersion than their counterparts in
Malaysian Borneo.  This component, however, would only serve to
increase the difference in dispersion between Indonesia and Malaysia
during the treatment period.  Our analysis in later sections will show
that the moratorium dampened the difference in dispersion, such that
the relative sizes of the treatment and control groups do not
appreciably affect the found conclusions.\\

\begin{figure}[h] 
        \centering
        \includegraphics[width=0.55\textwidth]{images/old/sample-area.png}
        \caption{Sample area, Malaysia in green and Indonesia in
        orange.  Borders indicate subprovinces.}  
        \label{fig:sample-area}
\end{figure}

We utilize the basic difference-in-differences method to estimate the
impact of the moratorium on overall deforestation.  Let $M$ be a
binary variable that indicates the time interval of the moratorium,
i.e., the treatment.  We will allow this time period to vary to
accommodate the three stages of the moratorium.  Let $C$ be the group
indicator for Indonesia.  The standard difference-in-differences model
is given by

\begin{equation}
R_{it} = \gamma_0 + \gamma_1 M_t + \gamma_2 C_i + \tau (M_t \cdot C_i) +
\beta\x + \epsilon_{it},
\label{eq:total}
\end{equation} where $\x$ is a vector of cofactors.  The identifying
assumption is that in the absence of the moratorium, the time trends
in $R_t$ between Indonesia and Malaysia would be stable after
controlling for confounding variables.  The crucial variables are the
price of palm oil and the relative value of the Indonesian and
Malaysian currency, which are the primary drivers of the difference
between deforestation rates in the two countries.  The price peaked at
the same time that the moratorium was enacted, as shown in Figure
\ref{fig:total}. In this initial study, the vector $\x$ includes the
price of oil palm and the relative exchange rate of Indonesia's rupiah
to Malaysia ringgit.\\

We employ a similar strategy to identify the impact of the moratorium
on the spatial dispersion of deforestation.  The reference model is
almost identical to the model reported in Equation (\ref{eq:total}),
except that the proportion of new deforestation in new clusters is the
dependent variable:

\begin{equation}
P_{it} = \gamma_0 + \gamma_1 M_t + \gamma_2 C_i + \tau (M_t \cdot C_i) +
\beta\x + \epsilon_{it}
\label{eq:prop}
\end{equation} Note that the average effect of the treatment for the
treated is estimated by $\hat{\tau}$.  Abadie (2005) considers the
case when differences in observed characteristics create non-parallel
outcome dynamics between treated and control groups.  Abadie discusses
the severe assumptions that underlie difference-in-differences
estimation, especially with respect to lag structures of responses to
exogenous shocks across the treated and controls.  Take, for example,
the current context, where a developers in the treated and control
groups may have difference response times to either a sustained or
short-term increase in palm oil price.  Standard
difference-in-differences will not yield a consistent estimate of the
treatment effect.  Abadie proposes a semi-parametric correction based
on the observables in $\x$ to account for non-parallel effects in the
outcome variable.  Still, this correction is based on the trends of
observable characteristics, whereas there may be dynamics that are
dependent on the error structure.  Any non-parallel shifting or
stretching in the $P_{it}$ time series of the treated and control
groups will yield a mis-specified impact estimate of the treatment on
the treated.\\

We propose an information theoretic approach to identification.
Specifically, we attempt to uncover broad trends in the outcome
variable by using common patterns in the residual variation.  Through
a non-parametric matching technique called dynamic time warping, we
"snap" the treated series to comparable observations in the control
series.  This method is commonly used in time series classification
and language detection, searching for discernible patterns in speech
waveforms through idiosyncratic amplitudes and frequencies.  A
rigorous treatment of this method and its empirical properties is
beyond the scope of this paper, but will be included as an appendix in
subsequent versions of the paper. Instead, we present a very basic
illustration of the outcome of the matching in Figure
\ref{fig:match}. A standard, uncorrected difference-in-differences
estimator relies on a perfectly vertical comparison of observations.
In other words, the dashed matching lines in Figure \ref{fig:match}
would all be vertical, associating values within the same time period
only. Time warping allows for flexible slopes, given constraints on
the slope and distance of the matching lines. Figure \ref{fig:match}
shows the result of the matching algorithm between the treatment and
control $P_{it}$ series.  We can reconstruct the treated $P_{it}$
series based on the matching lines toward a new series that is purged
of non-constant lag structures in the error term.  This new series,
the aligned series, may better characterize the comparable differences
between the treatment and control groups that result from the
treatment.  The assumption, now, is that the unobserved micro-dynamics
are /similar/ across groups; but we don't need to assume that they are
parallel or constant.  This is a much looser and more tenable
assumption.

\begin{figure}[t] 
        \centering
        \includegraphics[width=0.95\textwidth]{images/match.png}

        \caption{Dynamic time warping of the Indonesian (black, solid)
        series and the Malaysian (red, dashed) series.  The gray
        matching lines match similar values across the two series,
        based on a set of matching penalties.  The dates are replaced
        with index values.}

        \label{fig:match}
\end{figure}

* Results

The results of the aggregate deforestation regression in Equation
(\ref{eq:total}) are reported in Table \ref{tab:total}. Column (1)
defines the treatment period as occurring after the first stage of the
moratorium, when it was first announced.  This specification
acknowledges that investment in new clusters is affected by expected
returns.  A credible announcement six months prior to enactment of a
policy that could affect a long-term investment process could have
just as much impact as the enforcement of the policy.  Column (2)
defines the treatment period as occurring after the second stage, and
Column (3) after the final stage, when it was actually enacted.  After
May 20, 2011, no new concessions for clearing activity in primary
forests should have been granted by local governments.  There were
some highly criticized exceptions; but the issuance of such
concessions in the specified areas abruptly decreased.\\

The results in Table \ref{tab:total} suggest that the overall rate of
deforestation /increased/ as a result of the moratorium in Indonesia,
after controlling for palm oil price.  The price spiked when the
moratorium was enacted and remained high throughout the treatment
period, such that much of the variation in price is collinear with the
treatment period indicator.  Thus, given the multicollinearity, the
price effect is not significant, but the parameters suggest that the
effect of contemporaneous price is positive but with diminishing
marginal effect.  The somewhat surprising insignificance may also be
the result of a lag structure that is not included in the
regression.\\

The results of the proportion regression in Equation \ref{eq:prop} are
reported in Table \ref{tab:prop}.  The results of the regression
/after the Indonesia series was warped/ are reported in Table
\ref{tab:warped-prop}.  First note that the proportion of
deforestation in new clusters is persistently higher in Indonesian
Borneo than in Malaysian Borneo, revealed by the coefficient on
=country=.  This is surely derived from the relative sizes of the two
countries in Borneo: the opportunity to create new clusters of
deforestation is higher in Indonesian Borneo than in Malaysian Borneo
because it is three times larger.  The effect of the moratorium,
however, was to reduce the responsiveness of $P_{it}$ in Indonesia to
economic indicators that generally drive dispersion of deforestation.
Table \ref{tab:prop} presents the results for the raw $P_{it}$ with
the columns specified as they were in Table \ref{tab:total}.  Given
the high prices of oil palm, and the associated incentive to create
new clusters of deforestation, the proportion in Indonesia /should
have/ hovered around 8.5%; but instead it has remained at around 7.5%,
as if the price did not increase at all.\\

\begin{minipage}{\textwidth}
  \begin{minipage}[b]{0.49\textwidth}
    \centering
    \input{tables/screened-rates.tex}
    \captionof{table}{Total deforestation, $R_{it}$}
    \label{tab:total}
  \end{minipage}
  \hfill
  \begin{minipage}[b]{0.49\textwidth}
    \centering
    \input{tables/prop-res.tex}
    \captionof{table}{Proportion in new clusters, $P_{it}$}
    \label{tab:prop}
  \end{minipage}
\\
\end{minipage}

The results for the warped $P_{it}$ series in Table
\ref{tab:warped-prop} further support the conclusion that the
moratorium reduced investment in new clusters of deforestation
relative to the expansion of existing clusters, given the price of
palm oil.  The coefficient for the treatment effect, $\hat{\tau}$, is
negative and highly significant.  As in the previous tables, Columns
(1), (2), and (3) define the treatment period based on the three
different phases of the moratorium.  The coefficient becomes less
negative as the treatment period is shortened.  One possible
explanation is that, as time has progressed, the threat of enforcement
of the moratorium has become less credible.  The rate of violations
reported in the Jakarta Post has certainly increased dramatically,
with little official response.  \\

The decreasing magnitude of the treatment in Columns (1), (2), and (3)
of Table \ref{tab:warped-prop} could also be a statistical artifact.
The time series plots in Figure \ref{fig:sprop} suggest that there may
be multiple but discrete equilibria for investment patterns, based
primarily on the return to investment in Indonesia.  The difference
between the Malaysian and Indonesian time series is first very large,
and is commensurate the 2008 palm oil price spike and the subsequent
rupiah devaluation.  The difference does not respond to the 2010 price
increase; but instead hovers at the lower equilibrium levels.  In this
context, extending the treatment period back to the first phase in May
2010 may falsely ascribe the persistent, lower equilibrium to the
treatment.  Columns (4), (5), and (6) add the relative exchange rate,
the Indonesian rupiah over the Malaysian ringgit.  The treatment
effect does not change at all, but the price effect becomes more
discernible as positive with diminishing marginal effect.\\

\begin{table}[t!]
    \centering
    \input{tables/warped-prop.tex}
    \caption{Warped proportion of deforestation in new clusters}
    \label{tab:warped-prop}
\end{table}

* Policy implications

The primary objective of the 2011 moratorium was to reduce the overall
rate of forest clearing activity in Indonesia.  Our analysis of Borneo
suggest that the moratorium may have had the opposite effect.
Specifically, that the narrowly defined moratorium merely reduced the
formation of new clusters of deforestation (conditional on high palm
oil prices) but disproportionately increased deforestation around
existing clusters.  Land developers adjusted their development
schedule in response to the moratorium; and in this readjustment,
total deforestation increased, counter to the intentions of the
moratorium.  This study illustrates the need to consider broader
definitions of additionality, permanence, and leakage when designing
conservation policy. \\

The analysis also suggests that efforts to extend the two-year
moratorium will be met with strong industry resistance, perhaps at an
even greater intensity than was exhibited after the announcement of
the original plan.  Instead of pursuing new clusters of deforestation,
developers may have used forest stock within existing concessions to
smooth the supply of cleared land for agriculture.  Extending the
moratorium may actually disrupt the supply of cleared land, rather
than forcing a short-term depletion of forested land.  The fight over
extending the moratorium has already begun; and we can expect that the
agriculture sector will not accept further disruptions to development
of primary forests.  The Jakarta Post reported on December 7, 2012
that "Indonesias Forestry Minister announced that he will recommend
to the President that the moratorium be extended when it expires in
May 2013.  But in response, lawmakers in the House of Representatives
threatened to freeze the budget for reforestation projects should
Yudhoyono decide to extend the ban until the end of his term in 2014."
Taken together, recent newspaper articles suggest that aggregate
supply of cleared land was not significantly impacted by the
moratorium, but merely reallocated through space and time.  Extending
the moratorium may actually have an appreciable effect on agriculture,
as indicated by the increasing resistance to further conservation.\\

Reducing dispersion of deforestation may have secondary environmental
benefits that run counter to the environmental degradation of
aggregate clearing activity.  Forest fragmentation threatens ecosystem
resilience and biodiversity, and condensing deforestation may actually
mitigate other unintended consequences of REDD programs that focus
exclusively on aggregate forest clearing. Forest scientists assert
that REDD may have "disastrous consequences for biodiversity" because
of a singular focus on aggregate forest stocks, rather than the
spatial distribution of clearing activity.  At the very least, this
fact supports the further study of the spatial distribution of
deforestation, rather than a relatively narrow view of conservation.

\begin{comment}

# "The worst thing about the moratorium," according to the REDD monitor,
# "is that it has not reduced deforestation."  

# Empirical evidence suggests that the cost of extraction is constant
# within a cluster.  That is, pixels deforested at a later time tend to
# have the same physical attributes (e.g., slope and elevation) as
# pixels deforested earlier.  This indicates constant cost of extraction
# within a cluster.  Between clusters, however, there are increasing
# costs. 

# We cannot assume that deforestation is a classically exhaustible
# resource, since the decrease in available (read: profitable) clusters
# goes down with the moratorium.  An exhaustible resource situation
# would imply that the rate of extraction in current clusters would
# decrease, since it has to last longer.  However, we don't see this.  I
# think that this has to do with the temporary nature of the moratorium,
# that $t_1$ is now restricted.  More of the resource in cluster 1 may
# be consumed before switching -- does this imply that the short term
# rate increases in a discrete way?\\

# What about the factors of "production" of deforestation.  If there is
# a decrease in demand on one type of production, the factors become
# cheaper for the other -- for existing clusters.  The lower marginal
# cost will also mean that more can be produced with factors that had
# previously been working in higher-cost extraction.\\

# Increase in price implies shorter time frame to switch to new
# clusters.  Higher rate of clearing in new and on the periphery of old
# clusters.  Shorter time frame to switch.

# Option value?  Storage models?

# The palm prices track the general trend in global agricultural
# prices, suggesting that the price increases were exogenous, despite
# the fact that Indonesian palm oil accounts for about 40% of global
# supply. 

# Empirical evidence suggests that the moratorium shifted the spatial
# distribution of clearing away from the counter factual.  Increases in
# output price generally increase the spatial dispersion of clearing.  A
# larger proportion of clearing activity takes place in new clusters,
# rather than on the periphery of existing clusters when the price is
# high.  This makes sense.  A higher price will slowly begin to shift
# developers' expectations on the return to cleared land, which is an
# input to production of agricultural products.  Assuming a constant and
# stable marginal cost of clearing, the fixed costs of clearing become
# more palatable as the price of agricultural products increase: there
# is more of a chance of a positive return on investment (all in
# expectation).  The proportion of new clearing in /new/ clusters, then,
# will increase with the expected return (price of oil palm) --- there
# is more of a chance that the investment will be made.  There will be
# some lag, some time for developers' expectations to adjust, but even
# looking at the contemporaneous data, the signal is reasonably
# clear. 

# The moratorium reduced the price responsiveness of deforestation in
# new clusters, relative to old clusters.  Less of incremental clearing
# occurred in new clusters than we would expect, given the sustained and
# rapid price increase of oil palm.  This makes sense, too.  The
# moratorium restricted new concessions for deforestation, but did not
# restrict clearing activity within existing concessions.  On average,
# only 70% of existing concessions had been cleared; much of the
# concession area remained untouched, presumably stored for future
# exploitation [citation needed].

# The natural next question is "what are the assumptions that would
# cause the shift to old clusters to completely offset the overall
# reduction in new clusters?"  The data suggest that the total or
# overall rate of clearing may have increased after the moratorium was
# enacted, or equivalently that the /more than offset/ the reduction of
# clearing in new clusters.

# *Points to make* (in no particular order):

# 1. Tropical deforestation accounts for roughly 15% of annual carbon
#    emissions, more than the combined emissions from road, rail, air,
#    and marine transportation, worldwide.

# 2. Borneo is 73% Indonesia, 26% Malaysia, and 1% Brunei (which is not
#    considered in this study to keep it compact).  It is home to one of
#    the oldest rain forests in the world.

# 3. The moratorium constrained investment in new deforestation
#    clusters, shifting the spatial distribution of deforestation and
#    ultimately increasing the overall rate of deforestation.

# 4. Indonesia announced the two-year moratorium in May 2010 to be
#    enacted in January 2011, but it wasn't actually enacted until March
#    2011 after disputes between government, industry, and environmental
#    advocates.  Three stages of the moratorium.

# 5. The moratorium was catalyzed by a $1 billion promise from Norway,
#    cash on delivery to Indonesia, contingent on a reduction in the
#    deforestation rate.  The promise of aid made the government's
#    previously feeble attempts to manage deforestation much more
#    credible.

# 6. We use the island of Borneo as a social lab, of sorts, given that
#    Malaysian Borneo is similar in weather and agricultural output as
#    Indonesian Borneo, but was not subject to the moratorium.  While
#    the border was drawn based on physical attributes of the land -- to
#    divide the watersheds -- the similarity of the two sides is
#    reasonable.  The one complication may be that Indonesian Borneo is
#    three times the size of Malaysian Borneo, potentially affecting the
#    possible spatial dispersion.

# 7. The overall effect of the moratorium was an /increase/ in the rate
#    of deforestation, relative to Malaysia, but to decrease the
#    proportion of deforestation due to new clusters.  The spatial
#    pattern of deforestation became more condensed, with clearing
#    occurring disproportionately on the periphery of pre-existing
#    clusters.

# 8. The new paradigm under the moratorium resembles the short-term
#    response to increased supply of cleared land, on the outskirts of
#    existing clusters.  Lower cost to clear, no investment.  Short-term
#    response to quick changes in the demand for cleared land are met
#    with deforestation near previously cleared clusters.

# 9. Intertemporal leakage.  Induced short-term behavior in place of
#    long-term behavior, potentially waiting out the two-year
#    moratorium. Similar to spatial leakage: Restrictions on clearing in
#    a certain time or place will just induce clearing in a different
#    time or place.

# 10. The theoretical structure should have the ability to distinguish
#     between alternatives, to select a model based on testable
#     hypotheses: (a) race to the bottom? (b) lower productivity of land
#     near existing clusters? (c) freed up resources due to a lower
#     fixed cost?

# 11. Use the physical layout of the land to help distinguish between
#     hypotheses.  Examine the attributes of the land that was cleared
#     near existing clusters over time, before and after the moratorium
#     was enacted.

# 12. Potentially cluster the rate-proportion graph, looking to see if
#     the inclusion in each group was sequenced.  A different approach
#     to the standard diff-n-diff, potentially providing more intuition
#     about the way the data are clustered through time.

# 13. Disney has stopped sourcing from suppliers with a poor track
#     record on deforestation.  

# *Model Considerations*:

# 1. Areas around clusters should be modeled with option value,
#    reflecting the fact that short term supply of cleared land is
#    mainly around existing clusters.

# 2. The return on land cleared around existing clusters is lower than
#    that of new clusters.  Thus, to get the same amount of product out
#    of the land, more has to be cleared.  *Check this, ask someone
#    else.* Examine the characteristics of land cleared /around existing
#    clusters/ to see if the moratorium had an appreciable impact on,
#    say, the slope of cleared land (something related to yield).

# 3. Dynamic programming problem, with option value and stochastic
#    element.  Two types of resources and one investment term that
#    determines the next period's level of new land.

# 4. Look at the effect of increasing the risk of appropriation
#    associated with new land, drastically lowering the expected return.

# 5. There is inertia in the data, allow for time to adjust
#    expectations and to realize gains from previous investment.

# 6. Is the elasticity of supply of cleared land near /existing/
#    clusters greater than the elasticity of supply of cleared land in
#    /new/ clusters.  Different cost structures of clearing.  If so,
#    then a shock in demand will have a more than proportionate effect
#    on the land around existing clusters.  (This is seen in the data.)
#    The greater supply elasticity may be due to (a) less time to
#    mobilize resources and (b) excess capacity or inventory of land
#    near existing clusters.  Lower marginal costs will imply a greater
#    elasticity of supply.  

# 7. The supply shock that came with restricting new clearing will
#    induce a more than proportionate response in supply (?)  Inelastic
#    demand for cleared land.  Why doesn't the new supply just flood the
#    market, immediately driving back down the price?

# 8. Ultimately, the firms will have to invest in new clusters; but they
#    are content to use up their reserves now, knowing that the
#    moratorium is set to expire in May 2013.

# *Basic results*:

# 1. The moratorium had the unintended consequence of /increasing/
#    short-term clearing activity by shifting the spatial distribution of
#    deforestation to the periphery of existing clusters. Potential
#    cause: lower returns on land around existing clusters, and steady
#    demand for the yield from cleared land.

# 2. Deforesters are treating the set moratorium period as a short term
#    hit to investment activity, such that they are responding as if
#    there was a short-term increase in the demand for cleared land
#    (which would and has happened in the past).  This can be seen from
#    the stratified scatter plots.

# 3. The implication is that if the moratorium is lifted after two
#    years, then there will be temporal leakage -- restricting clearing
#    in one period only pushed it into another.  If the moratorium is
#    maintained, however, it may actually reduce long-term clearing,
#    since investment hasn't been made.  Another prediction: way more
#    outcry from industry over a long-term moratorium extension than for
#    the initial two-year enactment to respond to the Norwegian aid
#    promise.

# 4. Much of the effect happens when the moratorium was /supposed/ to be
#    enacted, the other half, so far, has occurred after the moratorium
#    was /actually/ enacted.

# Let $\xot$ and $\xtt$ be the amount of land cleared in time $t$, where
# the subscript 1 indicates that the land is on the periphery of an
# existing cluster and the 2 indicates that the land constitutes a new
# cluster.  Let $\pot$ and $\ptt$ be the respective prices for the
# cleared land, which are functions of the physical characteristics of
# the land.  We expect that $\pot < \ptt$, since new sites of land
# clearing will tend to locate in land with the highest net return.
# Landowners will progressively clear less valuable land according to an
# option value approach, effectively storing the forested land until the
# return is high enough to merit the marginal cost of clearing. For now,
# though, consider the simple dynamic programming problem to
# \begin{equation}
# \underset{x_1, x_2, I}{\max} \int^{T}_0 \pi_1 (\xot) + \pi_2 (\xtt) - I(t) \, dt 
# \hspace{8pt} \mbox{subject to} \hspace{8pt} 
# \Rtd = f(I(t)) 
# \hspace{8pt} \mbox{and} \hspace{8pt} 
# \Rod = f(I(t-1)) - \xtt
# \end{equation}

# where $I(t)$ indicates the level of investment in infrastructure or
# exploration costs in order to create new clusters of cleared land in
# the following period.  For a given amount of land, $\xb$, we assume
# that $\pi_2(\xb) > \pi_1(\xb)$.  The profit from the newly cleared
# land is greater than that of land near older clusters.  This gives
# landowners an extra incentive to clear new land, above and beyond the
# incentive to expand production.  The function $f$ is increasing and
# maps investment costs into the amount of land available in the new
# area.

# * Ideas

# 1. Use Borneo as the sample area, since a border separates the top
#    third (Malaysia) from the bottom two thirds (Indonesia).

# 2. The moratorium on new deforestation was announced in May 2010.
#    Norway promised to give $1 billion in aid to Indonesia, contingent
#    on successfully reducing the deforestation rate over a two-year
#    period.

# 3. The moratorium was actually enacted on January 1, 2011.

# 4. It is widely known that deforestation has continued despite the
#    moratorium, with industry taking advantage of loopholes and minimal
#    enforcement.  We can check to see if the deforestation rate
#    actually changed over this period, although it will be difficult to
#    ascribe any shift in the overall /rate/ to the moratorium. Why?
#    There are many issues with expectations, prices, and other sources
#    of endogeneity.

# 5. We can, however, see if there was an appreciable shift in the
#    /type/ or spatial dispersion of clearing activity.  Hypothesis: The
#    expectation of increased enforcement, or even just the cost of
#    counter-lobbying when deforestation is found out, is enough to make
#    the clusters of deforestation disperse.  Question: Did the
#    moratorium change the composition of deforestation in Indonesia?
#    Was there a shift toward smaller clusters, i.e., a break in the
#    time series of new cluster creation along preexisting roads, even
#    with potentially higher costs of clearing or lower returns to
#    agriculture?

# 6. Use a type of diff-in-diff-in-diffs approach with the rate of
#    cluster formation in Malaysia.
\end{comment}

\pagebreak

#+LATEX: \nocite{*}
#+LATEX: \bibliographystyle{abbrv}
#+LATEX: \bibliography{empiricalpaper}
