#+LATEX_HEADER: \usepackage{mathrsfs} 
#+LATEX_HEADER: \usepackage{amstex} 
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{comment} 
#+LATEX_HEADER: \usepackage{caption} 
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{dcolumn}
#+LATEX_CLASS: article
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \setlength{\parindent}{0}
#+TITLE: The effect of Indonesia's moratorium on deforestation clusters
#+AUTHOR: Dan Hammer
#+OPTIONS:     toc:nil num:nil
#+LATEX: \renewcommand{\E}{\mathbb{E}}
#+LATEX: \renewcommand{\rpp}{r^{\prime\prime}}
#+LATEX: \renewcommand{\cpp}{c^{\prime\prime}}

* Introduction

Tropical deforestation accounts for roughly 10% of annual carbon
emissions, more than the combined emissions from road, rail, air, and
marine transportation, worldwide.  Any viable effort to mitigate
climate change will have to address tropical deforestation.  The
external costs of deforestation are not incorporated into the private
decision to convert forests for agriculture, suggesting that public
intervention might be necessary to curb the rate of clearing.  An
array of alternatives have been specified to reduce new clearing
activity, ranging from portecting selected areas to a full moratorium
on new clearing activity.  To date, however, the efficacy of these
measures has been minimal.  


Deforestation in Indonesia was responsible for 25% of total emissions
from tropical deforestation between 2000 and 2005.  The proportion is
projected to be higher for 2005 through 2010.  The  



Any viable response to climate change must address the deforestation
rate, which is almost certainly above the social optimum.  Carbon
sequestration is just one of many environmental services provided by
standing forests that are not incorporated into the private cost of
clearing.  Other environmental services include nurturing biodiversity
and habitats for ranging mammals.  These services are functions of the
spatial distribution of forests, rather than just the level.


# Climate scientists warn that annual emissions must be quickly and
# drastically cut to avert severe climate change.  Any viable response
# to climate change will have to address the deforestation rate, which
# is almost certainly above the social optimum.  Forests provide many
# environmental services, including carbon sequestration, that are not
# incorporated into the private cost of clearing.  This paper estimates
# the impact of Indonesia's 2011 moratorium on deforestation.  We find
# the short-term, unintended consequences of a broad moratorium may have
# increased the deforestation rate, but created more clustering.


# The release of stored carbon is perhaps the most apparent externality
# imposed by clearing forest.  Another set of services that are
# disregarded by individual landowners is tied to the spatial
# distribution of standing forest.  Forest landscapes are becoming
# increasingly fragmented, threatening ecosystem reslience and
# biodiversity.  Contiguous forests that foster ranging mammals and
# birds are broken up for the relatively homogenous agricultural plots.
# The goods and services provided by biodiversity are invaluable, and
# often overlooked.  In the frenzy to curb the overall deforestation
# /rate/, the spatial distribution may be suffering. This paper does not
# present an argument on the relative value of ecosystem services for
# habitat destruction versus fragmentation, only that there may be
# unintended consequences of an overall prohibition of new clearing. \\

# This paper examines the effect of Indonesia's 2011 moratorium on new
# deforestation on the spatial dispersion of clearing activity.
# Specifically, it examines the choice of landowners to expand on
# previously cleared clusters or to move to new, untouched areas.  We
# find that the moratorium with weak enforcement scattered
# deforestation, disproportionately increasing the creation rate of new
# clusters in Kalimantan, the Indonesian side of the island of Borneo.
# We also examine the character of those clusters over time, how the
# physical attributes of new clusters change, potentially indicating a
# push toward more marginal land.\\

# The first section describes the socio-political context for the
# moratorium.  The second section introduces a simple, dynamic
# programming model that illustrates the choice to clear new forests.
# The third section compares the rates of cluster formation in Indonesia
# and Malaysia, proposing that the observed difference indicates a
# dispersion effect in Indonesia.  The final section offers analysis and
# limits of inference.\\

* Background

In May 2010, Indonesia announced a moratorium on new deforestation,
with an array of caveats.  Industry has used the uncertainty in land
use maps to find loopholes in the moratorium and the rate of
deforestation has fallen only slightly [insert citation, time series
graph].  Norway offered US$1 billion in aid contingent on a
demonstrated reduction in the deforestation rate.  

* Model

Let $R_t = R_{1t} + R_{2t}$ be the amount of total amount of land
available to a single agent, split between equal-sized plots $i \in
\{1,2\}$. \\

Figure (\ref{fig:diag}) illustrates the effect of reducing the
expected returns of new clusters on the composition of incremental
deforestation.  The value $\bar{\gamma}$ is a fixed level of
production targeted by the firm.  The expected profit from land that
is close to previously cleared land is given by $\gamma_0$.  The
marginal profit is diminishing, perhaps because of increasing marginal
costs or decreasing marginal returns for (marginal profit should be
zero at $\hat{\gamma}$?).

\begin{figure}[h]
\caption{Illustration}
\centering
	\vspace{10pt}
	\setlength\fboxsep{1pt}
	\setlength\fboxrule{0.5pt}
	\setlength{\unitlength}{1cm}
	\begin{picture}(6, 6)(0, 0)
		\thicklines\
		\put(5.25,0.35){\line(0,1){5.65}}


		\thinlines\
		\put(0,0){\vector(0,1){6}}
		\put(0,2){\vector(1,0){6}}

		\put(5.25,0.78){\vector(-1,0){1.4}}
		\put(5.25,0.35){\vector(-1,0){2.35}}


		\put(3.85,0.78){\line(0,1){2.55}}
		\put(2.9,0.35){\line(0,1){2.8}}

		\qbezier(0,2)(3,3.5)(5.25,3.5)
		\qbezier(0,1.25)(3,2.5)(5.25,6)
		\qbezier(0,1.25)(3,2.5)(5.25,4.5)

		\put(-.8,5.75){$\E(\pi)$}
		\put(-.6,1.2){$-f$}
		\put(5.75, 1.7){$\gamma$}
		\put(5.15, 0){$\bar{\gamma}$}

		\put(4, 0.05){$\rho$}
		\put(4.45, 0.93){$\rho^{\prime}$}

		\put(4.45, 4.3){$\gamma^{\prime}_1$}
		\put(4.45, 5.5){$\gamma_1$}
		\put(4.45, 3.2){$\gamma_0$}
	\end{picture}
\label{fig:diag}
\end{figure}


\begin{comment}
# Let $R_t = R_{1t} + R_{2t}$ be the amount of resource in plots $i \in
# \{1,2\}$.  We assume a relatively high fixed cost of clearing, so that
# $c(a_i) = F + \gamma a_i$ with $\gamma$ constant in land cleared. The
# probability of getting caught $\delta_i$ and immediately paying a fine
# is an increasing function of $a_i$, but a decreasing function of the
# size of the other plot.  The rationale is that more condensed clearing
# is more likely to raise alarms with enforcement agents; and clearing
# activity in another pixel will divert attention.  We want to study the
# decision point at which the agent decides to begin clearing in the new
# plot, and how that varies with the increased overall probability of
# paying a fine (the moratorium).\\

#  The $\delta$ parameter is plot-specific, and $$\frac{\partial
# \delta_1 (a_1, a_2)}{\partial a_1} < 0 \hspace{8pt} \mbox{and}
# \hspace{8pt} \frac{\partial \delta_1 (a_1, a_2)}{\partial a_2} > 0,$$
# which implies that the larger the proportion cleared within a plot
# (the more densely clustered), the greater the risk of expropriation by
# the government.  It's more noticeable.  Likewise, given the scarce
# resources and constant costs of enforcement, the likelihood of getting
# caught decreases in the size of /another/ cluster.  The clustering in
# another plot acts as a diversion, of sorts, and reduces the likelihood
# of enforcement agents noticing other activity.
\end{comment}

# The individual firm takes price $p(t)$ as given and, for $i \in \{1,2\}$ attempts to
# \begin{eqnarray}
# \max \int_0^T \left[ p(t)q_{i}(t) - c(R(t))q_{i}(t) \right]e^{-rt}\,dt 
# \end{eqnarray}
# The total reserves $R(t) = R_1(t) + R_2(t)$.

* Empirical strategy

\begin{figure}[h] 
        \centering
        \includegraphics[width=0.55\textwidth]{images/sample-area.png}
        \caption{Sample area, Malaysia in green and Indonesia in
        orange.  Borders indicate subprovinces.}  
\label{fig:zoom}
\end{figure}


\begin{figure}[h]
        \centering
        \begin{subfigure}[b]{0.55\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/elev.png}
                \caption{Elevation}
                \label{fig:raw}
        \end{subfigure} \hspace{-30pt} \vline
        \begin{subfigure}[b]{0.5\textwidth}
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/slope.png}
                        \caption{Slope}
                        \label{fig:raw}
                 \end{subfigure} \hspace{-25pt}
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/flow.png}
                        \caption{Flow}
                        \label{fig:smoothed}
                 \end{subfigure} \\
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/hill.png}
                        \caption{Aspect}
                        \label{fig:raw}
                 \end{subfigure} \hspace{-25pt}
                 \begin{subfigure}[b]{0.5\textwidth}
                        \centering
                        \includegraphics[width=\textwidth]{images/drop.png}
                        \caption{Drop}
                        \label{fig:smoothed}
                 \end{subfigure}
        \end{subfigure}
        
        \caption{Map of the digital elevation model (left) with
         derived data sets (right) indicating slope, hydrology, and
         terrain roughness, 90m resolution. }
        
        \label{fig:kali}
\end{figure}


\begin{figure}[h]
        \centering
        \begin{subfigure}[b]{0.45\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/shade.png}
                \caption{Hillshade}
                \label{fig:raw}
        \end{subfigure} \hspace{2pt}
        \begin{subfigure}[b]{0.45\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/fill.png}
                \caption{Flow direction}
                \label{fig:smoothed}
        \end{subfigure}
        \caption{Detailed images of two derived data sets for the same area.}
\label{fig:zoom}
\end{figure}

* Results

\begin{table}
\label{tab:reg}
\caption{Proportion of deforestation from new clusters}
\centering
\input{tables/regout.tex}
\end{table}

\begin{figure}[h]
        \centering
        \begin{subfigure}[b]{0.49\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/prop.png}
                \caption{New cluster deforestation}
                \label{fig:raw}
        \end{subfigure} \hspace{-1pt}
        \begin{subfigure}[b]{0.49\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/alert.png}
                \caption{Alerts of deforestation}
                \label{fig:smoothed}
        \end{subfigure}
        \caption{Detailed images of two derived data sets for the same area.}
\label{fig:zoom}
\end{figure}

# * Ideas

# 1. Use Borneo as the sample area, since a border separates the top
#    third (Malaysia) from the bottom two thirds (Indonesia).

# 2. The moratorium on new deforestation was announced in May 2010.
#    Norway promised to give $1 billion in aid to Indonesia, contingent
#    on successfully reducing the deforestation rate over a two-year
#    period.

# 3. The moratorium was actually enacted on January 1, 2011.

# 4. It is widely known that deforestation has continued despite the
#    moratorium, with industry taking advantage of loopholes and minimal
#    enforcement.  We can check to see if the deforestation rate
#    actually changed over this period, although it will be difficult to
#    ascribe any shift in the overall /rate/ to the moratorium. Why?
#    There are many issues with expectations, prices, and other sources
#    of endogeneity.

# 5. We can, however, see if there was an appreciable shift in the
#    /type/ or spatial dispersion of clearing activity.  Hypothesis: The
#    expectation of increased enforcement, or even just the cost of
#    counter-lobbying when deforestation is found out, is enough to make
#    the clusters of deforestation disperse.  Question: Did the
#    moratorium change the composition of deforestation in Indonesia?
#    Was there a shift toward smaller clusters, i.e., a break in the
#    time series of new cluster creation along prexisting roads, even
#    with potentially higher costs of clearing or lower returns to
#    agriculture?

# 6. Use a type of diff-in-diff-in-diffs approach with the rate of
#    cluster formation in Malaysia.

# * Data sources

# [[http://www.indexmundi.com/commodities/?commodity=palm-oil][Palm oil Monthly Price - US Dollars per Metric Ton]]

* Discussion

Policy acts on people with incentives, not on inanimate objects.  You
cannot simply legislate a reduction of deforestation.  The paper
indicates that there is some /leakage/ associated with local (not just
in space like a protected area, but in scope of policy) conservation
policy.  This paper suggests that measures should be taken to dampen
the incentives of both plots, reduce the incentive to clear at all.
Maybe that would push people to the black market, though, just as
deforestation was pushed to new areas in this study.  The scope is not
wide enough.  This also offers an argument for an overhead and
comprehensive monitoring system.

#+LATEX: \nocite{*}
#+LATEX: \bibliographystyle{abbrv}
#+LATEX: \bibliography{empiricalpaper}
