#+LATEX_HEADER: \usepackage{amsmath} 
#+LATEX_HEADER: \usepackage{amsfonts} 
#+LATEX_HEADER: \usepackage{caption}
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{comment} 
#+LATEX_HEADER: \usepackage{setspace} 
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{dcolumn}
#+LATEX_HEADER: \usepackage{wrapfig}
#+LATEX_HEADER: \usepackage[font=small,labelfont=bf]{caption}
#+LATEX_CLASS: article
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \setlength{\parindent}{0}
#+LATEX_HEADER: \usepackage{setspace} 
#+LATEX_HEADER: \definecolor{aqua}{RGB}{3,168,158}
#+TITLE: /Cease and Disperse/: The impact of targeted conservation on the optimal development of resource pools
#+AUTHOR: Dan Hammer
#+OPTIONS:     toc:nil num:nil email:on

#+EMAIL: \texttt{danhammer@berkeley.edu}, Department of Agricultural and Resource Economics, UC Berkeley and the World Resources Institute. The author thanks Jeff Hammer and David Wheeler for invaluable comments.  All mistakes are theirs alone.  Thanks also to Max Auffhammer, Peter Berck, George Judge, Robin Kraft, and Wolfram Schlenker, among others who have unwittingly helped to defer blame for mistakes made in this paper.  All code to process the data for this paper is published as an open source project at \href{http://github.com/danhammer/empirical-paper}{\texttt{github.com/danhammer/empirical-paper}} with the full revision history.

#+LATEX: \newcommand{\pix}[1]{{\bf \textcolor{red}{#1}}}
#+LATEX: \newcommand{\E}{\mathbb{E}}
#+LATEX: \newcommand{\X}{{\bf X}}
#+LATEX: \newcommand{\x}{{\bf x}}
#+LATEX: \newcommand{\K}{{\bf K}}
#+LATEX: \newcommand{\zero}{{\bf 0}}
#+LATEX: \newcommand{\I}{{\bf I}}
#+LATEX: \newcommand{\rpp}{r^{\prime\prime}}
#+LATEX: \newcommand{\cpp}{c^{\prime\prime}}
#+LATEX: \newcommand{\xb}{\bar{x}}
#+LATEX: \newcommand{\pot}{p_{1}(t)}
#+LATEX: \newcommand{\xot}{x_{1}(t)}
#+LATEX: \newcommand{\ptt}{p_{2}(t)}
#+LATEX: \newcommand{\xtt}{x_{2}(t)}
#+LATEX: \newcommand{\L}{\mathscr{L}}

#+LATEX: \newcommand{\koh}{\hat{\K}_{1}}
#+LATEX: \newcommand{\kth}{\hat{\K}_{2}}
#+LATEX: \newcommand{\kohp}{\hat{\K}_{1}^{\prime}}
#+LATEX: \newcommand{\kthp}{\hat{\K}_{2}^{\prime}}
#+LATEX: \newcommand{\kohpp}{\hat{\K}_{1}^{\prime\prime}}
#+LATEX: \newcommand{\kthpp}{\hat{\K}_{2}^{\prime\prime}}

#+LATEX: \newcommand{\wp}{w^{\prime}}
#+LATEX: \newcommand{\wpp}{w^{\prime\prime}}

#+LATEX: \newcommand{\kb}{\bar{\kappa}}
#+LATEX: \newcommand{\ob}{\bar{\omega}}
#+LATEX: \newcommand{\kp}{\kb^{\prime}}
#+LATEX: \newcommand{\op}{\ob^{\prime}}
#+LATEX: \newcommand{\kpp}{\kb^{\prime\prime}}
#+LATEX: \newcommand{\opp}{\ob^{\prime\prime}}

#+LATEX: \newcommand{\Rod}{\dot{R}_{1}}
#+LATEX: \newcommand{\Rtd}{\dot{R}_{2}}

#+LATEX: \newcommand{\st}{\hspace{8pt} \mbox{subject to} \hspace{8pt}}
#+LATEX: \newcommand{\and}{\hspace{8pt} \mbox{and} \hspace{8pt}}
#+LATEX: \newcommand{\Kd}{\dot{\K}}

#+LATEX: \begin{abstract}
This paper examines the effect of narrowly defined conservation policy
on the spatial distribution of deforestation.  Specifically, we
estimate the impact of the 2011 Indonesian moratorium on new forest
concessions for agriculture production.  The intended impact was to
reduce the rate of deforestation, but instead we find that the
aggregate rate of deforestation may have increased.  This paper offers
a possible explanation that is founded in basic optimal control and
production theory.  Cleared land is an input to agriculture, which can
be sourced from the periphery of existing deforestation or from remote
forests.  We model the moratorium as a discrete increase in the input
price of cleared land in remote forests.  The marginal rate of
technical substitution over time determines both the differentiated
and aggregate rate of capital investment, or clearing activity.  We
argue that the marginal productivity of land in remote clusters is
higher than land on the periphery of existing clusters.  The implied
rate of substitution between the two land types indicates that the
moratorium will decrease the amount of remote land used, but increase
the aggregate rate.  This conclusion is supported by an empirical
study based on an original data set derived from satellite imagery.
Our sample area is the island of Borneo, which is bisected into
Indonesia and Malaysia by a national boundary, serving as our
identifying assumption for a difference-in-differences estimator.  We
employ a series of novel robustness checks to further validate the
conclusion.
#+LATEX: \end{abstract}
\doublespace

\vspace{40pt}

Tropical deforestation accounts for almost 20% of annual carbon
emissions, which is roughly equivalent to the emissions from the
transportation sector \cite{NBERw17417}.  Any viable effort to
mitigate climate change must therefore address deforestation.
Deforestation is a distinctly economic activity. This may be a
difficult proposition, however, since most deforestation occurs in
tropical countries, which rely heavily on cleared land for
agriculture.  Indonesia, for example, is responsible for roughly 20%
of annual deforestation \cite{Hammer2012}; and Indonesia's
agricultural sector, broadly defined, contributed 14.3% to gross
domestic product in 2012, a percentage only exceeded by India
\cite{ciafact}. Indonesia's rural economy relies heavily on products
derived from cleared land, and there exist incentives at every level
to convert standing forest to a more fiscally productive land use.  As
part of a grand Coasian bargain, Norway has pledged US$1 billion in
aid to Indonesia, conditional on a significant reduction of its
deforestation rate.  The Indonesian government immediately announced
its intention to stop issuing new permits for the exploitation of
primary forest.  The two-year moratorium on new concessions was
enacted in May 2011.\\

This paper evaluates the effectiveness of the moratorium in
Indonesia. The Indonesian government claims a resounding success, with
the Minister of Forestry announcing that "the moratorium has proven to
effectively reduce forest destruction" and that the forest clearing
rate has declined by at least one-third since the moratorium was
instituted \cite{jakglobe2}.  Various environmental groups, however,
counter that the moratorium has had no effect on aggregate clearing
activity.  Greenpeace claims that deforestation has actually increased
since the moratorium.  They claim that illegal forest clearing
activity and rampant corruption has eroded the efficacy of the
moratorium.  These claims seem to be corroborated by local media
outlets.  In May 2012, the Jakarta Globe reported that 5 million
hectares of Indonesia's remaining 130 million hectares of existing
tree cover had been cleared during the previous year \cite{jakglobe1}.
The state of Kalimantan on Borneo was hardest hit, losing 1.9 million
hectares of forest cover.  The source of this information is
unclear[fn:: The Jakarta Globe cites Greenpeace as the source of this
information, but repeated interactions with geospatial team at
Greenpeace have not produced a firm estimate.  It remains unclear
where the statistic came from.] and the statistic is highly contested
by the Ministry of Forestry \cite{jakglobe1}.  The Ministry claims
that most clearing activity since 2011 has occurred outside the
boundaries of specified conservation areas.  The moratorium does not
apply to concessions that had been granted before May 2011
\cite{wri}.  \\

The boundaries of the moratorium are continuously in flux.  The
national map of affected areas in Indonesia is scheduled to change
every six months throughout the duration of the two-year moratorium in
order to "accommodate the interests of businesses" \cite{jakpost}.
The result has been a veritable mess of alleged corruption, which has
only been exacerbated by a near total lack of independent monitoring
of deforestation.  Persistent cloud cover has prevented the use of
satellite imagery to generate comprehensive maps of cleared land.
However, recent advances in distributed processing have allowed for
more computationally intensive techniques to dispatch imaging problems
due to cloud cover.  We use an original data set derived from
satellite imagery to identify deforestation at 500-meter resolution
with 16-day updates \cite{Hammer2012}.  These data allow for an
unprecedented empirical study of the spatial development of
deforestation clusters.  The theoretical support for this paper is
derived from the foundational work by Weitzman (1976, 1980, 2003) on
the optimal development of resource pools.\\


# An outright ban on a specific type of clearing is a blunt policy
# instrument with almost certain impacts beyond the directly sanctioned
# forests.  International conservation groups have focused on geographic
# "leakage" to identify the true additionality of the policy, seeking to
# answer the question of whether the deforestation rate was reduced or
# merely pushed to an unaffected country or province.  They pay little
# attention, however, to shifting spatial patterns of deforestation
# /within/ an affected administrative area.  This is still leakage, but
# it is not a common This type of behavior is consistent with basic
# trade or production theory.  There has been a surprising lack of
# attention paid to leakage across different clusters within the
# country, potentially because of a lack of detailed data.  Leakage is
# merely substitution across geographic boundaries, or even through
# time.  The focus of this paper is to examine the substitution across
# different types of clearing activity on the aggregate level of forest
# conversion, based on the net revenue structure of the cleared land.\\

Each collection of contiguous pixels that are suitable for agriculture
can be modeled as separate resource pools.  The land owner has the
choice to intensify development on the periphery of existing cluster
or to expand the number of clusters in yet untouched forest landscape.
The structure of costs and returns of /peripheral deforestation/ is
very different from that of /remote deforestation/. Deforestation in
each time period can therefore be partitioned into peripheral and
remote deforestation, based on its location relative to existing
clusters of cleared pixels.  The distinction is substantive due to the
different net benefit schedules.\\

We apply Weitzman's optimal control framework to basic producer
theory, noting that cleared land is a capital input of production for
agriculture.  The two types of clearing activity -- peripheral and
remote -- are differentiated inputs in production.  Nascent clusters,
identified by remote clearing, tend to be associated with a higher
marginal product in our sample area.  The up-front cost of
establishing a new cluster, however, is non-trivial as new,
high-volume roads have to be built through intact forest
landscapes. We focus our attention on the island of Borneo, which is
bisected into Malaysia and Indonesia.  Only the Indonesian side, the
Kalimantan province, was directly affected by the moratorium.  Our
identifying assumption is that the spatial pattern and rate of
deforestation on the Malaysian side, the Sarawak province, was
unaffected by the policy.  We argue for the validity of this
assumption in the following sections.  \\

Our primary finding is that the moratorium shifted input use away from
remote clusters and toward peripheral clearing activity, with an
overall increase in the rate of forest clearing activity in Indonesia.
A simple difference-in-differences approach is applied to compare the
spatial development of deforestation in Malaysia and Indonesia.  The
results are robust up to a wide array of variations on the parameters
of the study.  The results suggest that developers more than offset
the reduction in remote clearing with peripheral clearing activity.
Moreover, the results warn against narrowly defined conservation
policy.  Very basic principles in producer theory and optimal control
can explain this type of behavior, which was not even considered in
the initial design of the moratorium.  As with many poorly defined
policies, the moratorium treated developers as inanimate objects
rather than maximizing agents, yielding an unintended but avoidable
outcome.\\

# in peripheral clearing activity.  This behavior is consistent with a
# dynamic, two-factor production model for a cost-minimizing firm.\\

# Deforestation as a source of revenue, an input to production, rather
# than a stream of resources.

# the spatial distribution of deforestation in Indonesia, using the
# island of Borneo as our sample area.  The theoretical support for this
# study comes directly from Weitzman's (1975) model of the optimal
# development of resource pools.  Weitzman describes the optimal
# extraction rule for multiple resource pools with arbitrary extraction
# costs.  His model can be reformulated and extended to model a land
# developer's choice to expand existing clusters of deforestation or to
# begin a new cluster.  Hartwick, /et al./ (1986) extend the general
# resource pool model to an exhaustible, non-reproducible resource with
# significant set-up costs to develop a new deposit.  The authors show
# that there exist conditions that would destroy the incentive to
# develop new clusters, given the return on extraction.  \\

# The intent of the moratorium was to reduce overall deforestation, not
# just clearing activity in previously unexploited forest landscapes.
# The moratorium's scope, however, was limited to new concessions.
# Meyfroidt /et al./ (2010) show that narrowly defined conservation
# efforts will displace deforestation to other, unprotected areas.
# Busch (2011) reports that a significant portion of forest in existing
# concessions remains untouched, even as new clusters are developed.
# This land, which could be modeled with storage or option value models,
# may serve as an alternative to new clearing activity in order to
# smooth the supply of newly cleared land for agriculture.  While these
# lands may not be directly impacted by the moratorium, we examine the
# indirect effect on forests within existing and irrefutable
# concessions.  The marginal rate of technical substitution between the
# two types of clearing activity toward a final agricultural product is
# dependent on the fixed and marginal costs of extraction on both types
# of land.  The impact on the /overall/ rate of clearing is therefore an
# empirical question.\\

# Economic studies of the optimal development of resource pools have
# largely been limited to theoretical exercises.  Objective data on
# resource extraction at a time scale commensurate with economic
# decision making have not been available.  Recent developments in cloud
# computation and satellite imaging have allowed for a new class of data
# for empirical study.  Chomitz and Nelson (2011) and Burgess /et al./
# (2012) have utilized remotely sensed data to assess the impact of
# protected areas and political cycles on the conversion of forests.
# Even these studies, however, have been severely limited by the spatial
# and temporal resolution of the data on land use change.  We are able
# to overcome these constraints with an original data set on tropical
# deforestation at 500-meter, 16-day resolution from satellite imagery.
# These data provide new information on the choice to intensify
# production in current resource pools or to open new pools for
# development.  The ultimate objective of this study --- which may not
# be fully addressed in this draft --- is to provide empirical evidence
# toward or against standing theory on the pattern of resource
# extraction in the presence of large set-up costs and heterogeneous
# marginal costs..\\

The paper is organized as follows: (1) A description of the regulatory
framework behind the Indonesian moratorium, (2) A brief description of
the remotely sensed data on deforestation, (3) A presentation of the
empirical strategy and (4) the results of the impact evaluation.
Finally, we (5) suggest possible implications of the study, and its
importance in broader conservation policy design.

# http://www.pnas.org/content/early/2010/11/05/1014773107.abstract


# The evaluation of conservation policies have been severely limited by
# lack of timely data on deforestation.  Chomitz and Nelson (2011) have
# shown that strict protected areas are less effective at managing
# forests than multi-use or indigenous areas, where local actors have a
# vested interest in the long-term management of forests. The authors
# were forced to use fires as a proxy for deforestation, since data on
# deforestation in the tropics was only available at five year
# intervals.  The results may be subject to systematic measurement error
# across the sample countries, especially since the use of fires to
# clear forests differ dramatically by region.  Other studies have shown
# the relationship between deforestation and infrastructure development,
# using the results to illustrate the tradeoff between development and
# conservation [citations]. But the study of forest resource use has
# been largely theoretical, relying on the study of the time-optimal
# path of extraction.  \\

* Regulatory background

The United Nations launched a global framework in 2008 to reduce
tropical deforestation, called the REDD (Reducing Emissions from
Deforestation and Degradation) initiative.  The initial intent of REDD
was to "support countries' efforts to ... transform their forest
sectors so as to contribute to human well-being and meet climate
change mitigation and adaptation aspirations ... through
performance-based payments" \cite{unredd}.  The stated objective of
the REDD initiative is exceedingly vague, and the shortcomings of REDD
have become clear, partly stemming from the fact that the scope and
objective of the program is so poorly defined.  The prospect for a
comprehensive and global REDD program has diminished significantly
since its launch.  In its place, bilateral agreements under the REDD
framework have materialized, most notably through Norway's pledge to
support Indonesia's pledge to reduce carbon emissions by 26% between
2010 and 2020. With 80% of Indonesian carbon emissions emanating from
land use change, Norway has promised US$1 billion in aid to Indonesia,
contingent on verified emissions reductions from forest conversion
\cite{unredd}.  The first stage of the partnership was the two-year
suspension of new concessions for natural forest conversion.  The
total area affected by the moratorium amounts to 64 million hectares,
roughly twice the size of Great Britain \cite{jakglobe1}. \\

The conditions surrounding the moratorium are in constant flux. The
map of affected areas is up for review every six months
\cite{mongabay}.  These conditions create a climate of high risk for
development of remote clusters, whether or not they are in natural
forests that are eligible for new concessions.  The risk of re-zoning
may be enough to deter new development.  It is conceivable that
initial clearing activity in new forests, even forests with legal
concessions, may actually be /targeted/ for re-zoning in the presence
of rent-seeking, corrupt politicians.  A series of news reports on
corruption and bribery surrounding the moratorium gives credence to
this assertion \cite{jakglobe2} \cite{cifor}.  Given the uncertainty
of the spatial and temporal extent of the moratorium, the effect has
been to increase the relative, expected cost of developing outside of
existing concessions.  Further research into whether the moratorium
could be modeled as a fixed, two-year period can be done; but it more
likely that, since the parameters are so blurry, we would expect
developers to behave as if the cost of investment increased in these
areas.\\

There were three stages of the moratorium.  (1) Indonesia first signed
a letter of intent with Norway on May 29, 2010, pledging to halt new
land conversion concessions in primary forest.  (2) The moratorium was
supposed to take effect in January 2011, but after significant
argument between the government, industry, and environmental groups,
the moratorium was not actually implemented (3) until May 2011. Still,
the extent of the moratorium is far from settled. Many reports have
surfaced about illegal land clearing operations after May 2011 and
associated bribes, potentially forestalling the release of Norway's
pledged aid.  There have been few, if any, reports of existing
concessions being revoked.  The ultimate effect of the moratorium,
then, has been an increase in uncertainty surrounding remote and yet
unlicensed clusters of forest with the potential to be converted to
agricultural land.  The value assessments of land within existing
concessions, however, remains fairly stable.  The amount of land
within existing concessions is non-trivial.  As of 2011, only 30% of
land within the existing concessions had been cleared in Indonesia,
leaving a significant land area that could be cleared, even if no new
concessions were granted \cite{Carlson20042012}.

* Data
\label{sec:data}

#+LATEX: \begin{wrapfigure}{r}{0.38\textwidth}
#+LATEX: \centering
                                                                                
#+LATEX: \begin{picture}(100,80)(0,0)

#+LATEX: \thicklines

#+LATEX: \multiput(0,0)(10,0){3}{\line(0,1){10}}
#+LATEX: \multiput(10,10)(10,0){3}{\line(0,1){10}}

#+LATEX: \multiput(0,0)(0,10){2}{\line(1,0){30}}
#+LATEX: \put(10,20){\line(1,0){20}}

#+LATEX: \color{red}
#+LATEX: \put(30,0){\line(1,0){10}}
#+LATEX: \put(30,10){\line(1,0){10}}
#+LATEX: \put(30,0){\line(0,1){10}}
#+LATEX: \put(40,0){\line(0,1){10}}

#+LATEX: \put(0,20){\line(1,0){10}}
#+LATEX: \put(0,30){\line(1,0){10}}
#+LATEX: \put(10,20){\line(0,1){10}}
#+LATEX: \put(0,20){\line(0,1){10}}

#+LATEX: \put(20,30){\line(1,0){10}}
#+LATEX: \put(20,40){\line(1,0){10}}
#+LATEX: \put(30,30){\line(0,1){10}}
#+LATEX: \put(20,30){\line(0,1){10}}

#+LATEX: \color{red}
#+LATEX: \put(80,70){\line(1,0){10}}
#+LATEX: \put(80,80){\line(1,0){10}}
#+LATEX: \put(80,70){\line(0,1){10}}
#+LATEX: \put(90,70){\line(0,1){10}}

#+LATEX: \put(90,70){\line(1,0){10}}
#+LATEX: \put(90,80){\line(1,0){10}}
#+LATEX: \put(100,70){\line(0,1){10}}

#+LATEX: \put(0,32.5){{\bf B}}
#+LATEX: \put(42,1){{\bf A}}
#+LATEX: \put(32.25,31.5){{\bf C}}
#+LATEX: \put(81,60){{\bf D}}
#+LATEX: \put(92,60){{\bf E}}

#+LATEX: \end{picture}
#+LATEX: \caption{Illustration of clusters}
#+LATEX: \label{fig:illust}
#+LATEX: \end{wrapfigure}

The foundational data for this study is an original data set of
deforestation for each 500-meter in the humid tropics.  The data set,
described in Hammer, /et al./ (2012), reports forest clearing activity
for each 16-day interval between January 1, 2008 and September
23, 2012. Forest clearing activity is reported as a normalized measure
of clearing intensity, based on composited, daily images from NASA's
Moderate Resolution Image Spectrometer (MODIS) sensor aboard the Terra
satellite.  A pixel is flagged for clearing activity if the measure
registers above 0.50.  Only pixels that are in Malaysian or Indonesian
Borneo and that were forested in January 2000 are considered in the
study.[fn:: The definition of forest is based on the Vegetation
Continuous Field (VCF) index from the MODIS sensor, which is
consistent with many other publications in remote sensing.  Most
notably, this definition is used by Hansen /et al./ (2008), who
provide the training data set for the our algorithm.] These data
constitute a panel with $N = 2,384,095$ pixels and $T=109$ time
intervals, a total of about 260 million records.  By September 2012,
$207,578$ pixels in the sample area were tagged with forest clearing
activity, indicating that approximately 8.71% of the study area has
been subject to clearing activity since February 2000.[fn:: The
precise interpretation of the deforestation identification measure can
be found in Hammer /et al./ (2012).  MODIS data are available from
February 2000 onwards, but the incremental deforestation measure only
begins in January 2008, to allow for training of the algorithm.]  \\

Figure \ref{fig:total} reports the overall rate of deforestation for
Malaysian and Indonesian Borneo.  The The time series indicates the
level of clearing activity for each 16-day interval, measured in the
number of 500m pixels.  The shaded regions indicate the three stages
of the moratorium, noting that there may be up to a two-month lag in
the detection of clearing activity.  Within each interval, the
identified pixels are categorized into one of two groups: (1) pixels
on the periphery of existing clusters of deforestation, and (2) pixels
that constitute a new, emerging cluster.  Consider, for example, the
illustration in Figure \ref{fig:illust}. The black pixels represent
existing cleared land, while the red, labeled pixels indicate newly
cleared areas.  The five newly identified pixels are grouped according
to their distance to the nearest, existing cluster.  We employ a
distance threshold equal to twice the resolution of the pixel, or
approximately 1000m, in order to identify distinct clusters. For
example in Figure \ref{fig:illust}, pixels \pix{A}, \pix{B}, and
\pix{C} would be grouped into one cluster, while pixels \pix{D} and
\pix{E} would be grouped into another.  The distance is measured
between pixel centroids.  The threshold is arbitrary, but it is
notable that the results of this paper are robust for many different
thresholds to define clusters.  \\

\begin{figure}[h!]
        \centering

        \begin{subfigure}[b]{0.9\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/ggplot-total.png}

                \caption{Total number of alerts for each 16-day
                period.}

                \label{fig:total}
        \end{subfigure} \\

        \begin{subfigure}[b]{0.9\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/ggplot-prop.png}

                \caption{Two month moving average of proportion of new
                clearing activity that occurs in new clusters, rather
                than on the periphery of old clusters of
                deforestation.}

                \label{fig:sprop}
        \end{subfigure}

        \caption{Time series of overall deforestation and the spatial
        distribution of deforestation.  Indonesia is in
        \textcolor{red}{red} and Malaysia is in
        \textcolor{aqua}{blue}.  Shaded bars indicate the three stages
        of the moratorium.}

\label{fig:defor-ts}
\end{figure}

The decision to invest in cleared land, a capital input to
agricultural production, is determined by agricultural prices and
characteristics of the land that will effect both the cost of
clearing.  These factors effectively determine components of the
firm's profit function.  We utilize data on agricultural prices, and
specifically global palm oil prices, collapsed from daily prices to
16-day averages.  The trend in Figure \ref{fig:palm-price} shadows the
global, aggregated commodity price index --- and many individual palm
oil substitutes.  This argues against an endogenous price shift, even
though the moratorium was coincident with a price spike in palm oil
and that Indonesia accounts for about 40% of global production.  In
the broader agricultural oil market, Indonesia is still a relatively
small player, given a high degree of substitutability.  We consider
the near-term price evolution of palm oil to be exogenous to
Indonesia's production.\\

We also utilize elevation data from the Shuttle Radar Topography
Mission (SRTM) to derive a host of physical characteristics of the
landscape.  The SRTM is reported at 90m, significantly higher
resolution than the 500m deforestation pixels.  We can therefore
create a derived data set of slope, terrain roughness (variance in
slope), and water accumulation at the MODIS 500m resolution.  These
static characteristics help specify the cost structure of investment.
In addition, the deforestation data rely on spectral imagery,
collected on a daily basis, along with NOAA data on precipitation and
other dynamic data sets, which are detailed in Hammer /et al./
(2012).\\


\begin{figure}[t]
        \centering
        \includegraphics[width=0.9\textwidth]{images/price.png}

        \caption{Palm oil price.  Shaded regions indicate the three
        stages of the moratorium.}

        \label{fig:palm-price}
\end{figure}


\begin{figure}[t]
        \centering
        \begin{subfigure}[b]{0.45\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/old/sample-area.png}

                \caption{Malaysia in green and Indonesia in orange,
                borders indicate subprovinces.}

                \label{fig:sample-area}
        \end{subfigure} 
        ~
        \begin{subfigure}[b]{0.45\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/elev.png}

                \caption{Elevation in meters, black to white indicates
                low to high elevation}

                \label{fig:raw}
        \end{subfigure}
        \caption{Sample Area, Borneo}
\end{figure}

* The optimal development of deforestation clusters

Weitzman (1976) presents the basic form for the optimal extraction of
a depletable resource from an array or resource pools under general
cost conditions.  His solution revealed that the sequencing of
extraction from different resource pools dependent on the cost
structure over time, rather than just the instantaneous, marginal cost
of extraction.  Many extensions have been published to generalize his
result and to offer specific theoretical extension.  Weitzman's
original models and the subsequent extensions have been overwhelmingly
theoretical, since detailed information on the evolution of individual
resource pools has not been available.  We offer an empirical
application of Weitzman's optimal control framework, using clusters of
deforestation to indicate separate resource pools.\\

Following Weitzman's (2003) notation, define $G(\K, \I)$ as the net
current "take home" cash flow of agriculture, where $\K$ is a vector
of capital inputs and $\I$ is a vector of the associated fixed-cost
investments.  Dynamic optimization of $G(\cdot)$, or optimal control
of $\I$, will determine the time-path of capital development.  The
detailed path of development is incidental, however, in determining
the aggregate effect of a change in the investment vector.  For this
type of application, Weitzman suggests an "old economist's trick" to
collapse the dynamic problem to its stationary equivalent.  Consider
the prototypical optimal control problem:
\begin{equation}
   \max \int_{0}^{\infty} e^{-\rho t}G(\K(t), \I(t))\, dt \\
   \begin{center}
      \begin{array}{rl}
         \st  & \Kd(t) = \I(t) \\ 
         \and & \K(t) \geq 0  \nonumber
      \end{array}
   \end{center}
   \label{eq:dyn}
\end{equation}

\doublespace 

where $\K(t)$ indicates the cumulative stock of capital inputs in time
$t$ and $\I(t)$ is the instantaneous investment in the corresponding
capital inputs.  The parameter $\rho$ indicates the competitive
interest rate. Define $R(\hat{\K})$ to be the stationary rate of
capital return when optimal investment is zero.  For a stationary
solution to exist, there must also exist a time $T$ such that for any
$\epsilon_i > 0$ and $t > T$, the optimal solution maintains $\I(t) <
\epsilon$.  The vector $\hat{\K}$ is the capital input mix that
satisfies the conditions for a stationary solution.  The stationary
rate of capital return is thus defined as
\begin{equation}
R(\hat{\K}) = \frac{\partial G(\K, \zero) / \partial \K}{\partial
G(\K, \zero) / \partial \I}
\label{eq:rate}
\end{equation} Equation (\ref{eq:rate}) implies that the capital mix
$\hat{\K}$ is optimal for all time, without any additional investment.
Any deviation from $\hat{\K}$ will yield a less profitable outcome.  A
valid question, from the outset, is whether the stationary solution is
reasonable when the capital input is cleared land.  The price of
cleared land within a small country in the agricultural market will
not evolve with scarcity, just as the cost of labor will not evolve
with scarcity in a standard two-factor production model.  The derived
demand for the capital input is determined by setting marginal cost
equal to marginal revenue product.  The substitution away from inputs
with increasing costs will prevent the evolution of input price.
Unlike many exhaustible resource problems, the expansion of cleared
land is not driven by increasing returns, but rather by increases in
agricultural prices.\\

The fundamental theorem of capital theory sets the stationary rate of
return equal to the competitive interest rate, resulting in the the
system of equations
\begin{equation}
R(\hat{\K}) = \rho  
\label{eq:fund}
\end{equation} The investment mix is subject to an external valve,
such that the decision to invest in each capital input will be weighed
against the going interest rate.  Weitzman notes that the stationary
solution may never be reached, depending on the particulars of the
investment schedules; but investment decisions will push the capital
mix toward the stationary solution through time.  An implication of
Equation (\ref{eq:fund}) is that, for any two inputs $i$ and $j$,
\begin{equation}
\frac{\partial G(\K, \zero) / \partial \K_i}{\partial G(\K, \zero) / \partial \I_i} = 
\frac{\partial G(\K, \zero) / \partial \K_j}{\partial G(\K, \zero) / \partial \I_j} 
\qquad \Rightarrow \qquad
\frac{\partial G(\K, \zero) / \partial \K_i}{\partial G(\K, \zero) / \partial \K_j} = 
\frac{\partial G(\K, \zero) / \partial \I_i}{\partial G(\K, \zero) / \partial \I_j} 
\label{eq:mrts}
\end{equation} 

These equalities hold for arbitrary investment schedules, as long as
the dynamic solution tends toward a stationary input mix.  The
implications are not so different from the static, two-factor
production model.  The present value of the marginal rate of technical
substitution should equal the present value of the relative investment
costs at the optimum.  For our study, the two factors are cleared land
on the periphery of existing clusters and cleared land that would
constitute a new, remote cluster.  Let $\hat{\K}_1$ be the stationary
capital usage for peripheral land, and let $\hat{\K}_2$ be the
stationary usage of remote land. These two inputs can be combined to
produce a certain level of agricultural product at a competitive
market price.  The associated revenue, or value to the land developer,
is the gross gain Weitzman's $G(\cdot)$ function.  Call this revenue
function $v(\cdot)$ and the present value of the discounted revenue
stream $\hat{v}(\cdot) = v(\cdot)/\rho$.  At this point, the dynamic
problem has been sufficiently collapsed to use the standard insight
from a static two-factor production model.  The derivation from the
dynamic problem ensures that the subsequent insight is robust up to
the dynamic considerations faced by the land developer. \\

Figure (\ref{fig:isoquant}) graphically represents the present value
isoquant.  The two inputs, peripheral and remote cleared land, are
highly substitutable in agricultural production, such that the
isoquant is almost linear.  Some level of complementarity, through
time, may emanate from risk mitigation strategies on the part of the
agriculturalist, or other dynamic considerations where exploration is
optimal. Suppose that $\kohp$ and $\kthp$ satisfy Equation
(\ref{eq:mrts}) under an initial investment schedule.  If the required
investment for remote land increases, then the optimum input mix will
move along the isoquant to $(\kohpp, \kthpp)$; the price, broadly
defined, to hire the input increased.  This situation corresponds to
the moratorium. \\

The moratorium differentially impacted the cost of investment in
remote clusters by increasing the uncertainty surrounding the
maintenance of the capital input.  Given that the moratorium map is
uncertain and changes every six-months, the likelihood that a
concession granted after May 2011 may be revoked is non-trivial.  At
best, the moratorium increases the uncertainty of a stranded capital
asset (cleared land), and at worst, the moratorium provides leverage
to local administrators to extort money from land developers.  The
rate of corruption surrounding land tenure and development in
Indonesia has skyrocketed since the moratorium, according to various
local news reports.  Either way, the requisite investment for remote
clusters increased relative to peripheral clusters as a direct result
of the moratorium.  Figure (\ref{fig:isoquant}) indicates that the
relative intensity of remote land decreases in response to the price
increase.  \\

The effect of the moratorium on the aggregate use of cleared land
depends on the average slope of the present value isoquant, which is
in turn determined by the relative productivity of the two land types.
The dominant use for land cleared at large-scale in Borneo is palm
oil.  The palm oil production process requires that the raw kernels be
processed by a central facility within 24 hours of harvesting.  The
kernels spoil quickly, and the proportion of spoiled kernels increases
in time.  The time required to transport the harvested kernels to the
processing facility is substantial, given a network of poor, dirt
roads.  Cleared land that is close to the processing facility
therefore has a higher per-acre yield of processed oil than cleared
land that is further away.  Land on the periphery of existing clusters
is, by definition, further away from the seed of the deforestation
cluster than the seed itself.  New clusters in remote forest
landscapes therefore have a higher productivity over the course of the
plantation development.  Peripheral deforestation indicates that the
plantation is further along in its development than remote
deforestation, which indicates initial clearing activity.  The
argument is, in effect, a geometric argument, and reflects the
diminishing productivity of a unit of land as the plantation grows.\\

The characteristics of the two land types support this argument.  Note
that the tangency of the isocost line would imply that the cost of
investment tends to be higher $\kth$ than for $\koh$.  It is more
difficult to prepare cleared land for agriculture at higher elevations
and at higher slope, all else equal.  We use the elevation data from
the SRTM digital elevation model to examine the characteristics of the
two land types.  For both Indonesia and Malaysia, the slope and
elevation are significantly higher for remote deforestation than for
peripheral deforestation (with $p$-values less than 0.001).  This
result is consistent with the slope of the isoquant in Figure
(\ref{fig:isoquant}).\\

Note that, assuming the shallow isoquant in Figure
(\ref{fig:isoquant}), an increase in the cost of investment in $\kth$
will yield an increase in the aggregate level of cleared land at the
optimum, i.e.,
\begin{equation}
\kohp + \kthp < \kohpp + \kthpp
\label{fig:ineq}
\end{equation} 

The decrease in $\kth$ is more than offset by the increase in $\koh$
as land developers shift agriculture to the periphery of existing
clusters, despite the lower marginal production.  After the dynamic
investment decisions are collapsed to their stationary equivalents,
there is nothing particularly deep about this structure.  The empirics
indicate that, indeed, more land was cleared in the aggregate after
the moratorium, even with a decrease in remote clusters.

# All we need is diminishing marginal returns; but this is exaggerated
# by the distance to oil palm plantations.

# There are two levels of investment: opening a new cluster and
# clearing new land.  We can roll these together in the discounted
# cost and benefit structure of each capital input, where the x_2
# indicates the seed for further, peripheral development.  

# ; but The dynamic optimization problems detailed in his book
# define the time path of capital development; but this is extraneous
# information for our relatively straightforward application.  Instead,
# we are interested only in the aggregate impact of an investment price
# shift on the optimized input mix.\\

# For this application, Weitzman suggests an "old economist's trick" to
# collapse a dynamic problem to its stationary equivalent.  Consider the 

# The decision to clear forest is the result of a dynamic optimization
# problem.  The gain from cleared land is realized over time; and the
# initial set-up costs are a substantial component of the cost to
# increase extensive agricultural production.  Land is an input in the
# production of palm oil or rubber.  Weitzman notes that the developer
# will invest in capital as long as the stationary rate of return on
# capital exceeds the interest rate.  This is such a basic concept in
# investment that he names this decision condition "the fundamental
# equation of capital theory."  A slight re-imagining of the equation
# yields a powerful insight into the decision to clear on the periphery
# of existing deforestation clusters or to create new clusters.\\

# Weitzman presents a simple heuristic to illustrate that the rate of
# return on an investment at the margin is equal to the interest rate
# $\rho$. The interest rate in a stationary equilibrium, he explains, is
# equivalent the imputed rental price.  
# \begin{equation}

# \end{equation}

# Consider a standard two-factor production model, where $x_1$ is
# cleared land on the periphery of existing clusters and $x_2$ is land
# in still nonexistent clusters.  A developer will be indifferent
# between hiring $x_1$ and $x_2$ if the stationary rate of return on
# either investment is equivalent.  At the margin and in stationary
# terms, the input mix will be determined according to the well-known
# cost minimization problem, which ultimately sets the marginal rate of
# transformation between the two inputs equal to the relative wage
# rates.  This is what Weitzman calls an "old economist's trick" to
# collapse a dynamic problem into its stationary equivalent.



# The difference between the new and old deforestation clusters is a
# matter of timing.  The land developer has already incurred the fixed
# costs of setting up a new resource pool with any incremental clearing
# activity on the periphery of existing clusters.  The new clusters,
# however, are defined by the fixed costs.  The two types of clearing
# are disjoint sets --- resource pools already opened, and those not yet
# opened --- the difference lies in where they exist on the clearing
# curve.



# Consider a standard two-factor production model in a competitive
# market for palm oil.  The cost-minimizing firm in the long-run will
# hire each factor up to the point where the marginal cost equals the
# marginal revenue product.  Let $x_1$ indicate cleared land on the
# periphery of existing deforestation clusters and let $x_2$ indicate
# cleared land that constitutes a new cluster of deforestation.  There
# is an immense literature on the optimal development of resource pools,
# along with the decision to invest in new factories or foreign direct
# investment.  Through the context-specific algebra, there is a common
# theme of choosing the input mix based on the relative characteristics.
# This is what we develop here.\\




# The profit-maximizing firm will determine the
# optimal input mix according to the constrained minimization problem:
# \begin{equation}
# \L = w_1 x_1 + w_2 x_2 + \lambda \left[f(x_1, x_2) - q \right]
# \label{eq:lagrange}
# \end{equation}
# Let $x_1$ 

#   Let $\omega$ and $\kappa$ denote the two factors
# of production.  The derived demand for $\omega$ and $\kappa$ are based
# on a cost minimization problem, which ultimately sets cost equal to
# revenue for the last unit hired.  The common approach to this problem
# separates fixed and marginal costs to illustrate input decisions at
# the margin.  This separation, however, cannot adequately represent the
# decision to utilize land in new clusters, since the cost of the next
# unit includes the fixed costs.  Separation would mask the investment
# decision.  We will adapt the two-factor production model to account
# for the dynamic decision to invest, using the concept of stationary
# cost, developed by Weitzman (1976). \\

# Let $\omega$ denote cleared land on the periphery of existing
# deforestation clusters, and let $\kappa$ denote cleared land that
# constitutes a new cluster.  The cost of hiring the next unit of
# $\kappa$ land will, by definition, be the fixed cost of creating the
# cluster.  Any subsequent clearing activity to expand that cluster is
# considered $\omega$ land.  The decision to hire a new unit of $\kappa$
# is the manifestation of a dynamic determination to invest in a new
# cluster.\\

# The standard development of the two-factor production model can be
# extended to dynamic considerations, using concepts developed by
# Weitzman (1976). Weitzman asserts that "it is easy to characterize the
# optimal rule in a classical environment where every pool has
# non-decreasing extraction costs. At any time simply draw the required
# amount from the source with lowest marginal cost."  He then presents a
# generalization, describing the optimal rule of resource pools with
# arbitrary extraction costs.  To do so, he develops a concept that he
# calls /equivalent stationary cost/, which is effectively the average
# marginal cost over a given time horizon.  We will show that the useful
# two-factor production model can be extended to incorporate the fixed
# cost considerations.

# Following Weitzman's paper, let $F_i(m)$ be the cost of extracting one
# more unit of resource from pool $i$ after $m$ units have already been
# extracted.  The equivalent stationary cost of extracting the next $n$
# units in a row is the weighted average:
# \begin{equation}
# \Psi_i^n(m) = \frac{\sum_{j=0}^{n-1} \alpha^j F_i(m + j)}{\sum_{j=0}^{n-1} \alpha^j}
# \label{eq:stationary}
# \end{equation} Define the implicit cost to be the minimum stationary
# cost, based on the optimal time horizon $\hat{n}$:
# \begin{equation}
# \Phi_i(m) = \Psi_i^{\hat{n}}(m) = \min_{n} \Psi_i^n(m)
# \label{eq:implicit}
# \end{equation} Weitzman's rule is to \textit{always extract the next
# resource unit from the pool with lowest implicit cost}.  If $F_i(m)$
# is non-decreasing everywhere, then this is equivalent to the
# marginalist rule. \\

# We can prove this by induction.  Let $P(0)$ indicate the truth of the
# the proposition when $j = 0$.  


# In the standard cost minimization problem, the firm will hire a factor
# until its marginal productivity is equal to its marginal cost.
# Consider the same problem, except over an infinite time horizon.
# Intuitively, the firm should hire a factor up to the point where its
# implicit productivity is equal to its implicit cost.  If the time
# horizon is prematurely halted, then this rule may not hold.
# \begin{equation}
# TC_n = \kappa \Phi_\kappa(m) + \omega \Phi_\omega(m)
# \end{equation}

# The difference is introduced through
# the flexible specification of time; a unit of time over which
# "marginal" costs are incurred varies and is optimized by the firm. We
# will utilize this concept to extend the two-factor production model in
# order to understand the effect of a change in the relative extraction
# cost associated with different resource pools.\\

# close substitutes, indicating that the marginal rate of technical
# substitution (MRTS) is near constant along the isoquant.  This
# relationship is exhibited by $q(\kappa, \omega)$ in Figure
# \ref{fig:isoquant}.  The rate of substitution between new and old
# cluster deforestation is based on empirical observation, something to
# be estimated.\\

# It is reasonable to assume, however, that the marginal product of new
# clusters is greater than the marginal product of old clusters.

# The magnitude of the substitution may not be one-to-one,
# however, and the production of palm oil suggests that.  Let $\wp$ be
# the price of input $\omega$ relative to the price of $\kappa$.

# The regulation differentially impacts the expected price of
# utilization of land in new clusters.  The relative input price of
# $\kappa$ increases.  With a low and constant marginal rate of
# technical substitution the aggregate use of the two inputs --- in the
# same units --- increases.

# \begin{equation} \op + \kp < \opp + \kpp \Leftrightarrow
# -\frac{\kp - \kpp}{\op - \opp} = -\frac{\Delta \kappa}{\Delta \omega} < 1
# \end{equation}

# Note that $- \Delta \kappa / \Delta \omega$ is the average marginal
# rate of substitution between the optimized input mixes $(\op, \kp)$
# and $(\opp, \kpp)$.  By assumption, the marginal rate of substitution
# is near constant, such that the marginal rate of technical
# substitution is less than one over the range of input mixes,
# conditional on a well-behaved production function.  Land in new
# clusters tends to be more productive toward oil palm, since the land
# is by definition closer to the center of the cluster --- and
# presumably the oil palm processing plant.  More travel over poor roads
# and lost product in the rough terrain back to the center of clusters
# implies a less productive yield per acre.\\

# The marginal cost of utilizing land in new clusters tends to be
# higher, as shown by the difference in the physical attributes of the
# land.  The cost to clear and ready the land for production is higher;
# but the yield is also higher, making the higher rate paid for the
# input worth it (i.e., holding $pMP_\kappa = 1/w$).  The question, now,
# is how to show that the new clusters are subject to expectations on
# price, that in fact the optimal development of resource pools will
# restrict new pools if the prices becomes excessively high.  This is
# shown in Hartwick, Kemp, et al. (1980).

\begin{figure}[t]
        \centering
        
        \begin{picture}(300,150)(0,0)
        
        \put(-20,140){$\kth$}
        \put(307,8){$\koh$}

        \put(-17,76){$\kthp$}
        \put(105,8){$\kohp$}

        \put(-17,46){$\kthpp$}
        \put(213,8){$\kohpp$}

        \put(307,37){$\hat{v}(\koh, \kth) = \bar{v}$}

        \thicklines

        \put(0,20){\vector(1,0){300}}
        \put(0,20){\vector(0,1){130}}

        \thinlines
        
        \qbezier(0,140)(130,45)(300,40)

        \put(110,20){\line(0,1){58}}
        \put(0,78){\line(1,0){110}}

        \put(218,20){\line(0,1){28}}
        \put(0,48){\line(1,0){218}}

        \end{picture}

        \caption{Illustration of an isoquant where the inputs exhibit
        a high degree of substitution in production and a low marginal
        rate of technical substitution.}

        \label{fig:isoquant}
\end{figure}

* Empirical strategy

Our goal is to identify the impact of the moratorium on the
spatiotemporal patterns of deforestation in Indonesia.  Specifically,
we attempt to identify the impact of the moratorium on

1. The overall rate of deforestation $R_t$
2. The proportion $P_t$ of deforestation that occurs in new clusters

Our sample is the island of Borneo, which is bisected into Indonesia
(73%) and Malaysia (26%) along the central highlands, seen in Figure
\ref{fig:sample-area}.  Forest conversion on both sides of the border
is primarily driven by large-scale palm oil production. Together,
Malaysia and Indonesia produce 65% of the world's oil palm, much of it
coming from the island of Borneo.  The climate and terrain are ideal
for palm oil production.  The border was established between Great
Britain and the Netherlands in 1891, based on coastal trade positions.
The conflict over trade routes the generated the border was
independent of the land characteristics that affect palm oil
production, although we acknowledge that the partition may have
subsequently and differentially influenced palm oil production on
either side of the border.  We utilize a difference-in-differences
approach to estimate the impact, with modifications introduced for
robustness checks.  Only the Indonesian side was directly impacted by
the moratorium.  Let $M$ be a binary variable indicating the time
period after the moratorium was established.  We will allow the
defining interval to vary in order to reflect the three-stage
enactment of the moratorium.  Let $C$ be a country indicator for
Indonesia.  The standard difference-in-differences model for the
overall rate of deforestation is given by

\begin{equation}
R_{it} = \gamma_0 + \gamma_1 M_t + \gamma_2 C_i + \delta (M_t \cdot C_i) +
\beta\x + \epsilon_{it},
\label{eq:total}
\end{equation} 

where $\x$ is a vector of cofactors.  The identifying assumption is
that in the absence of the moratorium, the time trends in $R_{it}$ and
$P_{it}$ are stable for the control and treatment groups after
controlling for relevant covariates.  The relevant covariates that may
affect the trends are the price of palm oil and the relative value of
the Indonesian and Malaysian currency.  Both measures have been shown
to substantially impact the rate of deforestation, and presumably the
spatial pattern of deforestation, although empirical research is
lacking. The price of palm oil peaked soon after the second stage of
the moratorium, as shown in Figure \ref{fig:total}.  We argue that the
price change was exogenous, and not affected by the moratorium.  As a
supporting illustration, consider the regression of palm oil prices on
the prices of copper, silver, and salmon.  Indonesia has no impact on
the price of these commodities. These commodities, however, explain
almost 85% of the variation in the palm oil price, and the addition of
$M_{it}$ lowers the adjusted $R^2$ value.  It is clear that the trend
in palm oil price was coincident with global commodity prices; and the
spike is unlikely to have been caused by the moratorium.  In fact,
including the price of oats in Canada has greater explanatory power on
the palm oil price than the moratorium in Indonesia.  The vector $\x$
therefore includes the price of palm oil and the relative exchange
rate of Indonesia's rupiah to the Malaysian ringgit.\\

We employ a similar strategy to identify the impact of the moratorium
on the spatial dispersion of deforestation.  The reference model is
almost identical to the model reported in Equation (\ref{eq:total}),
except that the proportion of new deforestation in new clusters is the
dependent variable:

\begin{equation}
P_{it} = \alpha_0 + \alpha_1 M_t + \alpha_2 C_i + \tau (M_t \cdot C_i) +
\beta\x + \epsilon_{it}
\label{eq:prop}
\end{equation} 

The average effect of the moratorium in Indonesia is estimated by
$\hat{\tau}$. The estimate will only be consistent if the identifying
assumption holds, specifically that the outcome would have followed
parallel paths over time.  Abadie (2005) outlines the severe
assumptions that underlie difference-in-differences estimation,
especially with respect to lag structure of the response variable in
the presence of unobserved shocks.  Suppose, for example, that the
time required to adjust the expectations in response to changes in
agricultural prices is different for Indonesian and Malaysian
developers.  The length of time that the global price must remain high
before a developer invests in a new deforestation cluster may be
different, based on domestic price guarantees or other stabilization
policies.  This difference may be enough to induce non-parallel
transformations of the outcome variable $P_{it}$, which would thereby
render the estimate $\hat{\tau}$ inconsistent.  A visual inspection of
Figure $\ref{}$ may support this situation, given that the superficial
patterns in $P_{it}$ for Indonesia seems to lag behind the $P_{it}$
measure for Malaysia.  Abadie proposes a semi-parametric correction
based on the observables in $\x$ to account for non-parallel effects
in the outcome variable.  But even this correction assumes a constant
shift between the outcome variable for the treatment and control
groups.  Moreover, the semi-parametric correction is based on the
trends of observable characteristics, whereas there may be dynamics
that are within the error that drive the shifts.  Any non-parallel
stretching or compressing in the outcome variable will not be
addressed by the Abadie (2005) correction.  \\

We propose a robustness check to the standard
difference-in-differences approach by way of a first-stage alignment
algorithm.  It is beyond the scope of this empirical paper to describe
in detail the non-parametric algorithm.  The basic objective, however,
is to uncover broad trends in the difference between the outcome
variables by matching corresponding, temporal patterns in the residual
variation.  We employ a matching technique called dynamic time warping
to "snap" the treated series to comparable observations in the control
series.  This method is commonly used in time series classification
and language detection, searching for discernible patterns in speech
waveforms.  We present an illustration of the matching procedure in
Figure \ref{fig:match}. A standard, uncorrected
difference-in-differences estimator relies on a perfectly vertical
comparison of observations.  In other words, for the standard
difference-in-differences estimator, the dashed matching lines in
Figure \ref{fig:match} would all be vertical, associating values
within the same time period only. Time warping allows for flexible
slopes.  Figure \ref{fig:match} shows the result of the matching
algorithm between the treatment and control $P_{it}$ series.  The
matching procedure defines a correspondence between the two series
that is based on the broad trends, rather than idiosyncratic noise.
\\

We reconstruct the Indonesia $P_{it}$ series based on the dynamic time
warping procedure in order estimate $\tau$ using the same model in
Equation (\ref{eq:prop}).  This new series, the aligned series, may
better characterize the comparable differences between the treatment
and control groups that directly result from the moratorium.  The
assumption, now, is that the unobserved micro-dynamics are /similar/
across groups; but we don't need to assume that they are parallel or
constant.  This is a much looser assumption.  The dynamic time warping
algorithm is only applied to Equation (\ref{eq:prop}) and not Equation
(\ref{eq:total}) as a robustness check.  The systematic stretching and
compression is much more apparent between the $P_{it}$ series for the
control and treatment groups.  The application of the matching
algorithm to the $R_{it}$ does not yield any appreciable change in the
results, since there does not seem to be any systematic but shifting
correspondence.

\begin{figure}[t] 
        \centering
        \includegraphics[width=0.95\textwidth]{images/match.png}

        \caption{Dynamic time warping of the Indonesian (black, solid)
        series and the Malaysian (red, dashed) series.  The gray
        matching lines match similar values across the two series,
        based on a set of matching penalties.  The dates are replaced
        with index values.}

        \label{fig:match}
\end{figure}

* Results

The results of the aggregate deforestation regression in Equation
(\ref{eq:total}) are reported in Table \ref{tab:total}. Column (1)
defines the treatment period as occurring after the first stage of the
moratorium, when it was first announced.  This specification
acknowledges that investment in new clusters is affected by expected
returns.  A credible announcement six months prior to enactment of a
policy that could affect a long-term investment process could have
just as much impact as the enforcement of the policy.  Column (2)
defines the treatment period as occurring after the second stage, and
Column (3) after the final stage, when it was actually enacted.  After
May 20, 2011, no new concessions for clearing activity in primary
forests should have been granted by local governments.  There were
some highly criticized exceptions; but the issuance of such
concessions in the specified areas abruptly decreased.\\

The results in Table \ref{tab:total} suggest that the overall rate of
deforestation /increased/ as a result of the moratorium in Indonesia,
after controlling for palm oil price.  The price spiked when the
moratorium was enacted and remained high throughout the treatment
period, such that much of the variation in price is collinear with the
treatment period indicator.  Thus, given the multicollinearity, the
price effect is not significant, but the parameters suggest that the
effect of contemporaneous price is positive but with diminishing
marginal effect.  The somewhat surprising insignificance may also be
the result of the lagged effect of a price change, which is not
accounted for in the regression.\\

Deforestation in Indonesian and Malaysian Borneo is highly
concentrated into superclusters, clusters with more than 0.5% of total
deforestation on the island.  In Indonesian Borneo, for example,
almost 5% of total deforestation in September 2012 was concentrated in
the top 10 largest clusters of the 2,861 total clusters.  A concern
may be that these superclusters drive the result.  However, the
results in Table \ref{tab:total} are robust after iteratively
screening out the top 10 clusters in each country.  And, in fact, the
results become stronger as the superclusters are removed from the
analysis.\\

The results of the regression described by Equation \ref{eq:prop} are
reported in Table \ref{tab:prop}, and the results of the dynamically
warped regression are reported in Table \ref{tab:warped-prop} as a
robustness check.  The proportion of deforestation in new clusters is
persistently higher in Indonesian Borneo than in Malaysian Borneo,
revealed by the coefficient on =country=.  This is surely derived from
the relative sizes of the two countries in Borneo: the opportunity to
create new clusters of deforestation is higher in Indonesian Borneo
than in Malaysian Borneo because it is three times larger.  The effect
of the moratorium, however, was to reduce the responsiveness of
$P_{it}$ in Indonesia to economic indicators that generally drive
dispersion of deforestation.  Table \ref{tab:prop} presents the
results for the raw $P_{it}$ with the columns specified to reflect the
three stages of the moratorium.  Given the high prices of oil palm,
and the associated incentive to create new clusters of deforestation,
the proportion in Indonesia /should have/ increased to about 8.5%; but
instead it has remained at around 7.5%, as if the price did not
increase at all.  The moratorium wiped out the dispersion we would
expect from an increase in agricultural prices. \\

\begin{minipage}{\textwidth}
  \singlespace
  \begin{minipage}[b]{0.49\textwidth}
    \centering
    \input{tables/screened-rates.tex}
    \captionof{table}{Total deforestation, $R_{it}$}
    \label{tab:total}
  \end{minipage}
  \hfill
  \begin{minipage}[b]{0.49\textwidth}
    \centering
    \input{tables/prop-res.tex}
    \captionof{table}{Proportion in new clusters, $P_{it}$}
    \label{tab:prop}
  \end{minipage}
\\ \vspace{20pt}
\end{minipage}

The results for the warped $P_{it}$ series in Table
\ref{tab:warped-prop} further support the results in Table
\ref{tab:prop}. In fact, the correction increased the magnitude of the
moratorium's impact.  The coefficient on =country:post=, the
interaction between the country and post-moratorium indicators, is
negative and highly significant in all specifications.  As in the
previous tables, Columns (1), (2), and (3) define the treatment period
based on the three different phases of the moratorium.  The magnitude
of the impact decreases as the treatment period is shortened.  One
possible explanation is that, as time has progressed, the threat of
enforcement of the moratorium has become less credible.  Developers
have begun to resume their involvement in remote forest landscapes.
The rate of violations reported in the Jakarta Post has certainly
increased dramatically, with little official response.  The impact is
both statistically and economically significant, indicating that the
moratorium reduced dispersion of forest clearing activity.\\

The decreasing magnitude of the treatment in Columns (1), (2), and (3)
of Table \ref{tab:warped-prop} could also be a statistical artifact.
The time series plots in Figure \ref{fig:sprop} suggest that there may
be multiple but discrete equilibria for investment patterns, based
primarily on the return to investment in Indonesia.  The difference
between the Malaysian and Indonesian time series is first very large,
and is commensurate the 2008 palm oil price spike and the subsequent
rupiah devaluation.  The difference does not respond to the 2010 price
increase; but instead hovers at the lower equilibrium levels.  In this
context, extending the treatment period back to the first phase in May
2010 may falsely ascribe the persistent, lower equilibrium to the
treatment.  Columns (4), (5), and (6) add the relative exchange rate,
the Indonesian rupiah over the Malaysian ringgit.  The treatment
effect does not change at all, but the price effect becomes more
discernible as positive with diminishing marginal effect.\\

\begin{table}[t!]
    \centering
    \input{tables/warped-prop.tex}
    \caption{Warped proportion of deforestation in new clusters}
    \label{tab:warped-prop}
\end{table}

In order to check that the observed impact is not spurious, we
simulate a placebo group in Indonesia.  Specifically, we randomly
select half of the subprovinces in Indonesia as a control group,
assigning the other half to a placebo treatment group. The plotted
points in Figure \ref{fig:placebo} are, in effect, the first
difference in the difference-in-differences estimation described in
Equation (\ref{eq:prop}).  The solid black line indicates the average
difference over time for 100 simulated treatment groups, or the
average of the plotted points for each period.  There is no observed
difference over time, as we would expect for a stable treatment group.
The red line, by contrast, is the observed difference betwween
Malaysian and Indonesian Borneo for the same measure, namely the
proportion of peripheral clearing activity over total clearing
activity for each time interval.  It is clear that (1) the level of
dispersion in Indonesia is persistently higher than in Malaysia, and
(2) there was an increase in relative dispersion during the period of
high commodity prices through 2009.  The results in Table
\ref{tab:prop} suggest that we would expect to see a similar
difference with the commodity price increases in 2011 between Malaysia
and Indonesia, but in fact the results are consistent with the
hypothesis that the moratorium suppressed peripheral clearing activity
in Indonesia; the red line remains stable and low, despite the high
commodity prices in 2011.

\begin{figure}[t]
        \centering
        \includegraphics[width=0.9\textwidth]{images/placebo.png}

        \caption{Robustness check. Black line indicates the average
        difference of input proportions between simulated, placebo
        groups.  Red line indicates the true difference of input
        proportions between Malaysian and Indonesian Borneo, the full
        sample.}

        \label{fig:placebo}
\end{figure}

* Policy implications

The primary objective of the 2011 moratorium was to reduce the overall
rate of forest clearing activity in Indonesia.  The direct and blunt
policy instrument was to ban new concessions for forest conversion.
In response, land developers merely shifted clearing activity away
from the directly impacted areas and toward forests within existing
concessions.  The result was an increase in aggregate deforestation,
given the relative productivity of land on the periphery of existing
clusters, within existing concessions.  The narrowly defined
conservation policy had the unintended consequence of increasing
deforestation, strictly counter to the expressed intentions.\\


The analysis also suggests that efforts to extend the two-year
moratorium will be met with strong industry resistance, perhaps at an
even greater intensity than was exhibited after the announcement of
the original plan.  Instead of pursuing new clusters of deforestation,
developers may have used forest stock within existing concessions to
smooth the supply of cleared land for agriculture.  Extending the
moratorium may actually disrupt the supply of cleared land, rather
than forcing a short-term depletion of forested land.  The fight over
extending the moratorium has already begun; and we can expect that the
agriculture sector will not accept further disruptions to development
of primary forests.  The Jakarta Post reported on December 7, 2012
that "Indonesias Forestry Minister announced that he will recommend
to the President that the moratorium be extended when it expires in
May 2013.  But in response, lawmakers in the House of Representatives
threatened to freeze the budget for reforestation projects should
Yudhoyono decide to extend the ban until the end of his term in 2014."
Taken together, recent newspaper articles suggest that aggregate
supply of cleared land was not significantly impacted by the
moratorium, but merely reallocated through space and time.  Extending
the moratorium may actually have an appreciable effect on agriculture,
as indicated by the increasing resistance to further conservation.\\

Reducing dispersion of deforestation may have secondary environmental
benefits that run counter to the environmental degradation of
aggregate clearing activity.  Forest fragmentation threatens ecosystem
resilience and biodiversity, and condensing deforestation may actually
mitigate other unintended consequences of REDD programs that focus
exclusively on aggregate forest clearing. Forest scientists assert
that REDD may have "disastrous consequences for biodiversity" because
of a singular focus on aggregate forest stocks, rather than the
spatial distribution of clearing activity.  At the very least, this
fact supports the further study of the spatial distribution of
deforestation, rather than a relatively narrow view of conservation.


\begin{comment}

# "The worst thing about the moratorium," according to the REDD monitor,
# "is that it has not reduced deforestation."  

# Empirical evidence suggests that the cost of extraction is constant
# within a cluster.  That is, pixels deforested at a later time tend to
# have the same physical attributes (e.g., slope and elevation) as
# pixels deforested earlier.  This indicates constant cost of extraction
# within a cluster.  Between clusters, however, there are increasing
# costs. 

# We cannot assume that deforestation is a classically exhaustible
# resource, since the decrease in available (read: profitable) clusters
# goes down with the moratorium.  An exhaustible resource situation
# would imply that the rate of extraction in current clusters would
# decrease, since it has to last longer.  However, we don't see this.  I
# think that this has to do with the temporary nature of the moratorium,
# that $t_1$ is now restricted.  More of the resource in cluster 1 may
# be consumed before switching -- does this imply that the short term
# rate increases in a discrete way?\\

# What about the factors of "production" of deforestation.  If there is
# a decrease in demand on one type of production, the factors become
# cheaper for the other -- for existing clusters.  The lower marginal
# cost will also mean that more can be produced with factors that had
# previously been working in higher-cost extraction.\\

# Increase in price implies shorter time frame to switch to new
# clusters.  Higher rate of clearing in new and on the periphery of old
# clusters.  Shorter time frame to switch.

# Option value?  Storage models?

# The palm prices track the general trend in global agricultural
# prices, suggesting that the price increases were exogenous, despite
# the fact that Indonesian palm oil accounts for about 40% of global
# supply. 

# Empirical evidence suggests that the moratorium shifted the spatial
# distribution of clearing away from the counter factual.  Increases in
# output price generally increase the spatial dispersion of clearing.  A
# larger proportion of clearing activity takes place in new clusters,
# rather than on the periphery of existing clusters when the price is
# high.  This makes sense.  A higher price will slowly begin to shift
# developers' expectations on the return to cleared land, which is an
# input to production of agricultural products.  Assuming a constant and
# stable marginal cost of clearing, the fixed costs of clearing become
# more palatable as the price of agricultural products increase: there
# is more of a chance of a positive return on investment (all in
# expectation).  The proportion of new clearing in /new/ clusters, then,
# will increase with the expected return (price of oil palm) --- there
# is more of a chance that the investment will be made.  There will be
# some lag, some time for developers' expectations to adjust, but even
# looking at the contemporaneous data, the signal is reasonably
# clear. 

# The moratorium reduced the price responsiveness of deforestation in
# new clusters, relative to old clusters.  Less of incremental clearing
# occurred in new clusters than we would expect, given the sustained and
# rapid price increase of oil palm.  This makes sense, too.  The
# moratorium restricted new concessions for deforestation, but did not
# restrict clearing activity within existing concessions.  On average,
# only 70% of existing concessions had been cleared; much of the
# concession area remained untouched, presumably stored for future
# exploitation [citation needed].

# The natural next question is "what are the assumptions that would
# cause the shift to old clusters to completely offset the overall
# reduction in new clusters?"  The data suggest that the total or
# overall rate of clearing may have increased after the moratorium was
# enacted, or equivalently that the /more than offset/ the reduction of
# clearing in new clusters.

# *Points to make* (in no particular order):

# 1. Tropical deforestation accounts for roughly 15% of annual carbon
#    emissions, more than the combined emissions from road, rail, air,
#    and marine transportation, worldwide.

# 2. Borneo is 73% Indonesia, 26% Malaysia, and 1% Brunei (which is not
#    considered in this study to keep it compact).  It is home to one of
#    the oldest rain forests in the world.

# 3. The moratorium constrained investment in new deforestation
#    clusters, shifting the spatial distribution of deforestation and
#    ultimately increasing the overall rate of deforestation.

# 4. Indonesia announced the two-year moratorium in May 2010 to be
#    enacted in January 2011, but it wasn't actually enacted until March
#    2011 after disputes between government, industry, and environmental
#    advocates.  Three stages of the moratorium.

# 5. The moratorium was catalyzed by a $1 billion promise from Norway,
#    cash on delivery to Indonesia, contingent on a reduction in the
#    deforestation rate.  The promise of aid made the government's
#    previously feeble attempts to manage deforestation much more
#    credible.

# 6. We use the island of Borneo as a social lab, of sorts, given that
#    Malaysian Borneo is similar in weather and agricultural output as
#    Indonesian Borneo, but was not subject to the moratorium.  While
#    the border was drawn based on physical attributes of the land -- to
#    divide the watersheds -- the similarity of the two sides is
#    reasonable.  The one complication may be that Indonesian Borneo is
#    three times the size of Malaysian Borneo, potentially affecting the
#    possible spatial dispersion.

# 7. The overall effect of the moratorium was an /increase/ in the rate
#    of deforestation, relative to Malaysia, but to decrease the
#    proportion of deforestation due to new clusters.  The spatial
#    pattern of deforestation became more condensed, with clearing
#    occurring disproportionately on the periphery of pre-existing
#    clusters.

# 8. The new paradigm under the moratorium resembles the short-term
#    response to increased supply of cleared land, on the outskirts of
#    existing clusters.  Lower cost to clear, no investment.  Short-term
#    response to quick changes in the demand for cleared land are met
#    with deforestation near previously cleared clusters.

# 9. Intertemporal leakage.  Induced short-term behavior in place of
#    long-term behavior, potentially waiting out the two-year
#    moratorium. Similar to spatial leakage: Restrictions on clearing in
#    a certain time or place will just induce clearing in a different
#    time or place.

# 10. The theoretical structure should have the ability to distinguish
#     between alternatives, to select a model based on testable
#     hypotheses: (a) race to the bottom? (b) lower productivity of land
#     near existing clusters? (c) freed up resources due to a lower
#     fixed cost?

# 11. Use the physical layout of the land to help distinguish between
#     hypotheses.  Examine the attributes of the land that was cleared
#     near existing clusters over time, before and after the moratorium
#     was enacted.

# 12. Potentially cluster the rate-proportion graph, looking to see if
#     the inclusion in each group was sequenced.  A different approach
#     to the standard diff-n-diff, potentially providing more intuition
#     about the way the data are clustered through time.

# 13. Disney has stopped sourcing from suppliers with a poor track
#     record on deforestation.  

# *Model Considerations*:

# 1. Areas around clusters should be modeled with option value,
#    reflecting the fact that short term supply of cleared land is
#    mainly around existing clusters.

# 2. The return on land cleared around existing clusters is lower than
#    that of new clusters.  Thus, to get the same amount of product out
#    of the land, more has to be cleared.  *Check this, ask someone
#    else.* Examine the characteristics of land cleared /around existing
#    clusters/ to see if the moratorium had an appreciable impact on,
#    say, the slope of cleared land (something related to yield).

# 3. Dynamic programming problem, with option value and stochastic
#    element.  Two types of resources and one investment term that
#    determines the next period's level of new land.

# 4. Look at the effect of increasing the risk of appropriation
#    associated with new land, drastically lowering the expected return.

# 5. There is inertia in the data, allow for time to adjust
#    expectations and to realize gains from previous investment.

# 6. Is the elasticity of supply of cleared land near /existing/
#    clusters greater than the elasticity of supply of cleared land in
#    /new/ clusters.  Different cost structures of clearing.  If so,
#    then a shock in demand will have a more than proportionate effect
#    on the land around existing clusters.  (This is seen in the data.)
#    The greater supply elasticity may be due to (a) less time to
#    mobilize resources and (b) excess capacity or inventory of land
#    near existing clusters.  Lower marginal costs will imply a greater
#    elasticity of supply.  

# 7. The supply shock that came with restricting new clearing will
#    induce a more than proportionate response in supply (?)  Inelastic
#    demand for cleared land.  Why doesn't the new supply just flood the
#    market, immediately driving back down the price?

# 8. Ultimately, the firms will have to invest in new clusters; but they
#    are content to use up their reserves now, knowing that the
#    moratorium is set to expire in May 2013.

# *Basic results*:

# 1. The moratorium had the unintended consequence of /increasing/
#    short-term clearing activity by shifting the spatial distribution of
#    deforestation to the periphery of existing clusters. Potential
#    cause: lower returns on land around existing clusters, and steady
#    demand for the yield from cleared land.

# 2. Deforesters are treating the set moratorium period as a short term
#    hit to investment activity, such that they are responding as if
#    there was a short-term increase in the demand for cleared land
#    (which would and has happened in the past).  This can be seen from
#    the stratified scatter plots.

# 3. The implication is that if the moratorium is lifted after two
#    years, then there will be temporal leakage -- restricting clearing
#    in one period only pushed it into another.  If the moratorium is
#    maintained, however, it may actually reduce long-term clearing,
#    since investment hasn't been made.  Another prediction: way more
#    outcry from industry over a long-term moratorium extension than for
#    the initial two-year enactment to respond to the Norwegian aid
#    promise.

# 4. Much of the effect happens when the moratorium was /supposed/ to be
#    enacted, the other half, so far, has occurred after the moratorium
#    was /actually/ enacted.

# Let $\xot$ and $\xtt$ be the amount of land cleared in time $t$, where
# the subscript 1 indicates that the land is on the periphery of an
# existing cluster and the 2 indicates that the land constitutes a new
# cluster.  Let $\pot$ and $\ptt$ be the respective prices for the
# cleared land, which are functions of the physical characteristics of
# the land.  We expect that $\pot < \ptt$, since new sites of land
# clearing will tend to locate in land with the highest net return.
# Landowners will progressively clear less valuable land according to an
# option value approach, effectively storing the forested land until the
# return is high enough to merit the marginal cost of clearing. For now,
# though, consider the simple dynamic programming problem to
# \begin{equation}
# \underset{x_1, x_2, I}{\max} \int^{T}_0 \pi_1 (\xot) + \pi_2 (\xtt) - I(t) \, dt 
# \hspace{8pt} \mbox{subject to} \hspace{8pt} 
# \Rtd = f(I(t)) 
# \hspace{8pt} \mbox{and} \hspace{8pt} 
# \Rod = f(I(t-1)) - \xtt
# \end{equation}

# where $I(t)$ indicates the level of investment in infrastructure or
# exploration costs in order to create new clusters of cleared land in
# the following period.  For a given amount of land, $\xb$, we assume
# that $\pi_2(\xb) > \pi_1(\xb)$.  The profit from the newly cleared
# land is greater than that of land near older clusters.  This gives
# landowners an extra incentive to clear new land, above and beyond the
# incentive to expand production.  The function $f$ is increasing and
# maps investment costs into the amount of land available in the new
# area.

# * Ideas

# 1. Use Borneo as the sample area, since a border separates the top
#    third (Malaysia) from the bottom two thirds (Indonesia).

# 2. The moratorium on new deforestation was announced in May 2010.
#    Norway promised to give $1 billion in aid to Indonesia, contingent
#    on successfully reducing the deforestation rate over a two-year
#    period.

# 3. The moratorium was actually enacted on January 1, 2011.

# 4. It is widely known that deforestation has continued despite the
#    moratorium, with industry taking advantage of loopholes and minimal
#    enforcement.  We can check to see if the deforestation rate
#    actually changed over this period, although it will be difficult to
#    ascribe any shift in the overall /rate/ to the moratorium. Why?
#    There are many issues with expectations, prices, and other sources
#    of endogeneity.

# 5. We can, however, see if there was an appreciable shift in the
#    /type/ or spatial dispersion of clearing activity.  Hypothesis: The
#    expectation of increased enforcement, or even just the cost of
#    counter-lobbying when deforestation is found out, is enough to make
#    the clusters of deforestation disperse.  Question: Did the
#    moratorium change the composition of deforestation in Indonesia?
#    Was there a shift toward smaller clusters, i.e., a break in the
#    time series of new cluster creation along preexisting roads, even
#    with potentially higher costs of clearing or lower returns to
#    agriculture?

# 6. Use a type of diff-in-diff-in-diffs approach with the rate of
#    cluster formation in Malaysia.
\end{comment}

\pagebreak

#+LATEX: \nocite{*}
#+LATEX: \bibliographystyle{abbrv}
#+LATEX: \bibliography{empiricalpaper}
